"""Campaign workspace models and helpers."""

from .workspace import CampaignWorkspace
from .schemas import (
    CampaignConfig,
    CampaignBrief,
    PlacementRef,
    RouteSeed,
    VariantDefaults,
    PlacementManifest,
    CampaignRoute,
    DeterministicBatchSpec,
    ExportManifest,
)
from .planner import (
    CampaignBriefDraft,
    CollectCampaignBriefPayload,
    RoutePlanInput,
    PlacementPlanInput,
    PlanCampaignRoutesPayload,
    PlanBatchGenerationPayload,
    normalize_collect_campaign_brief_payload,
    normalize_plan_campaign_routes_payload,
    normalize_plan_batch_generation_payload,
    collect_campaign_brief,
    plan_campaign_routes,
    plan_batch_generation,
)
from .orchestrator import CliAction, execute_cli_actions
from .status import (
    CampaignStatusPayload,
    CampaignStatusReport,
    CampaignTotals,
    PlacementStatus,
    RoutePlacementStatus,
    RouteStatus,
    PendingVariant,
    build_campaign_status,
    normalize_campaign_status_payload,
)

__all__ = [
    "CampaignWorkspace",
    "CampaignConfig",
    "CampaignBrief",
    "PlacementRef",
    "RouteSeed",
    "VariantDefaults",
    "PlacementManifest",
    "CampaignRoute",
    "DeterministicBatchSpec",
    "ExportManifest",
    "CampaignBriefDraft",
    "CollectCampaignBriefPayload",
    "RoutePlanInput",
    "PlacementPlanInput",
    "PlanCampaignRoutesPayload",
    "PlanBatchGenerationPayload",
    "normalize_collect_campaign_brief_payload",
    "normalize_plan_campaign_routes_payload",
    "normalize_plan_batch_generation_payload",
    "collect_campaign_brief",
    "plan_campaign_routes",
    "plan_batch_generation",
    "CliAction",
    "execute_cli_actions",
    "CampaignStatusReport",
    "CampaignTotals",
    "PlacementStatus",
    "RoutePlacementStatus",
    "RouteStatus",
    "PendingVariant",
    "build_campaign_status",
    "CampaignStatusPayload",
    "normalize_campaign_status_payload",
]
