CITY_TO_PROVINCE = {"Madrid": "Madrid"}

POSTCODES = {
    "01": "Álava",
    "02": "Albacete",
    "03": "Alicante",
    "04": "Almería",
    "05": "Ávila",
    "06": "Badajoz",
    "07": "Baleares",
    "08": "Barcelona",
    "09": "Burgos",
    "10": "Cáceres",
    "11": "Cádiz",
    "12": "Castellón",
    "13": "Ciudad Real",
    "14": "Córdoba",
    "15": "La Coruña",
    "16": "Cuenca",
    "17": "Gerona",
    "18": "Granada",
    "19": "Guadalajara",
    "20": "Guipúzcoa",
    "21": "Huelva",
    "22": "Huesca",
    "23": "Jaén",
    "24": "León",
    "25": "Lérida",
    "26": "La Rioja",
    "27": "Lugo",
    "28": "Madrid",
    "29": "Málaga",
    "30": "Murcia",
    "31": "Navarra",
    "32": "Orense",
    "33": "Asturias",
    "34": "Palencia",
    "35": "Las Palmas",
    "36": "Pontevedra",
    "37": "Salamanca",
    "38": "Santa Cruz de Tenerife",
    "39": "Cantabria",
    "40": "Segovia",
    "41": "Sevilla",
    "42": "Soria",
    "43": "Tarragona",
    "44": "Teruel",
    "45": "Toledo",
    "46": "Valencia",
    "47": "Valladolid",
    "48": "Vizcaya",
    "49": "Zamora",
    "50": "Zaragoza",
    "51": "Ceuta",
    "52": "Melilla",
}

# Mapping of normalized names (for comparison) to standardized names (for storing)
# for each corresponding country code
STATES = {
    "es": {
        "andalucia": "Andalucía",
        "aragon": "Aragón",
        "asturias": "Asturias",
        "baleares": "Baleares",
        "canarias": "Canarias",
        "cantabria": "Cantabria",
        "castilla la mancha": "Castilla-La Mancha",
        "castilla y leon": "Castilla y León",
        "cataluna": "Cataluña",
        "ceuta": "Ceuta",
        "comunidad valenciana": "Comunidad Valenciana",
        "extremadura": "Extremadura",
        "galicia": "Galicia",
        "la rioja": "La Rioja",
        "madrid": "Comunidad de Madrid",
        "melilla": "Melilla",
        "murcia": "Murcia",
        "navarra": "Navarra",
        "pais vasco": "País Vasco",
        "euskadi": "País Vasco",    # Alias not caught by rapidfuzz
    }
}

PROVINCES = {
    "es": {
        "alava": "Álava",
        "araba": "Álava", # Alias not caught by rapidfuzz
        "albacete": "Albacete",
        "alicante": "Alicante",
        "almeria": "Almería",
        "asturias": "Asturias",
        "avila": "Ávila",
        "badajoz": "Badajoz",
        "barcelona": "Barcelona",
        "bizkaia": "Vizcaya",
        "burgos": "Burgos",
        "caceres": "Cáceres",
        "cadiz": "Cádiz",
        "cantabria": "Cantabria",
        "castellon": "Castellón",
        "ceuta": "Ceuta", # Considered province by opensm and/or geonames
        "ciudad real": "Ciudad Real",
        "cordoba": "Córdoba",
        "cuenca": "Cuenca",
        "gipuzkoa": "Gipuzkoa",
        "gerona": "Gerona",
        "granada": "Granada",
        "guadalajara": "Guadalajara",
        "huelva": "Huelva",
        "huesca": "Huesca",
        "islas baleares": "Islas Baleares",
        "jaen": "Jaén",
        "la coruna": "La Coruña",
        "la rioja": "La Rioja",
        "las palmas": "Las Palmas",
        "leon": "León",
        "lerida": "Lérida",
        "lugo": "Lugo",
        "madrid": "Madrid",
        "malaga": "Málaga",
        "melilla": "Melilla", # Considered province by opensm and/or geonames
        "murcia": "Murcia",
        "navarra": "Navarra",
        "orense": "Orense",
        "palencia": "Palencia",
        "pontevedra": "Pontevedra",
        "salamanca": "Salamanca",
        "santa cruz de tenerife": "Santa Cruz de Tenerife",
        "segovia": "Segovia",
        "sevilla": "Sevilla",
        "soria": "Soria",
        "tarragona": "Tarragona",
        "teruel": "Teruel",
        "toledo": "Toledo",
        "valencia": "Valencia",
        "valladolid": "Valladolid",
        "zamora": "Zamora",
        "zaragoza": "Zaragoza",
    }
}

# Cutoff score for rapidfuzz in the name standardization function
STANDARD_THRESHOLD = 40