# generated by puzl.cloud generator:
#   filename:  apis__resource.k8s.io__v1alpha3_openapi.json
#   timestamp: 2025-10-20T15:38:45+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import ClassVar, List, Set

from k8s_models.const import *
from k8s_models.loader import *
from k8s_models.loader import LazyLoadModel
from k8s_models.resource import *

from ...apimachinery.pkg.apis.meta.v1 import ListMeta, ObjectMeta, Time


@dataclass(kw_only=True, frozen=True)
class CELDeviceSelector(LazyLoadModel):
    expression: str


@dataclass(kw_only=True, frozen=True)
class DeviceSelector(LazyLoadModel):
    cel: CELDeviceSelector | None = None


@dataclass(kw_only=True, frozen=True)
class DeviceTaintSelector(LazyLoadModel):
    device: str | None = None
    deviceClassName: str | None = None
    driver: str | None = None
    pool: str | None = None
    selectors: List[DeviceSelector] | None = None


@dataclass(kw_only=True, frozen=True)
class DeviceTaint(LazyLoadModel):
    effect: str
    key: str
    timeAdded: Time | None = None
    value: str | None = None


@dataclass(kw_only=True, frozen=True)
class DeviceTaintRuleSpec(LazyLoadModel):
    taint: DeviceTaint
    deviceSelector: DeviceTaintSelector | None = None


@dataclass(kw_only=True, frozen=True)
class DeviceTaintRule(K8sResource):
    spec: DeviceTaintRuleSpec
    apiVersion: str = 'resource.k8s.io/v1alpha3'
    kind: str = 'DeviceTaintRule'
    metadata: ObjectMeta = field(default_factory=ObjectMeta)
    api_path_: ClassVar[str] = 'apis/resource.k8s.io/v1alpha3/devicetaintrules'
    plural_: ClassVar[str] = 'devicetaintrules'
    is_namespaced_: ClassVar[bool] = False
    group_: ClassVar[Optional[str]] = 'resource.k8s.io'
    apiVersion_: ClassVar[str] = 'resource.k8s.io/v1alpha3'
    kind_: ClassVar[str] = 'DeviceTaintRule'
    patch_strategies_: ClassVar[Set[PatchRequestType]] = {
        'application/merge-patch+json',
        'application/json-patch+json',
        'application/apply-patch+yaml',
        'application/strategic-merge-patch+json',
        'application/apply-patch+cbor',
    }


@dataclass(kw_only=True, frozen=True)
class DeviceTaintRuleList(LazyLoadModel):
    items: List[DeviceTaintRule]
    apiVersion: str = 'resource.k8s.io/v1alpha3'
    kind: str = 'DeviceTaintRuleList'
    metadata: ListMeta = field(default_factory=ObjectMeta)
