#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2506-20-gcd974c3b"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2506
#define NETGEN_VERSION_TWEAK 20
#define NETGEN_VERSION_HASH "gcd974c3b"
#endif // NETGEN_VERSION_HPP_INCLUDED
