"""
BIPS CLI Entrypoint
"""

from ps_cli.controllers import (
    AccessLevels,
    AccessPolicy,
    AddressGroup,
    Aliases,
    APIRegistration,
    Application,
    Asset,
    Attributes,
    AttributeTypes,
    Credential,
    Database,
    DSSKeyPolicies,
    Entitlement,
    EntityType,
    EPMPolicies,
    Folder,
    FunctionalAccount,
    ISARequest,
    Keystroke,
    ManagedAccount,
    ManagedSystem,
    OperatingSystem,
    Organization,
    PasswordRule,
    Permission,
    Platform,
    PropagationActions,
    PropagationActionTypes,
    QuickRule,
    RawRequest,
    Request,
    Roles,
    Safe,
    Secret,
    Session,
    SessionLocking,
    SessionTermination,
    Settings,
    SmartRule,
    SubscriptionDelivery,
    TicketSystems,
    User,
    UserGroupRoles,
    Usergroups,
    Workgroup,
)
from ps_cli.core.app import App


def main() -> None:
    controllers = [
        Application,
        AccessPolicy,
        AddressGroup,
        AccessLevels,
        Aliases,
        APIRegistration,
        Attributes,
        AttributeTypes,
        Safe,
        Folder,
        Secret,
        Session,
        SessionLocking,
        SessionTermination,
        ManagedAccount,
        FunctionalAccount,
        ManagedSystem,
        Workgroup,
        User,
        Usergroups,
        Roles,
        UserGroupRoles,
        Keystroke,
        Database,
        DSSKeyPolicies,
        Organization,
        Settings,
        Asset,
        Credential,
        Entitlement,
        EntityType,
        ISARequest,
        OperatingSystem,
        TicketSystems,
        Platform,
        Request,
        PasswordRule,
        Permission,
        PropagationActionTypes,
        PropagationActions,
        QuickRule,
        SmartRule,
        EPMPolicies,
        SubscriptionDelivery,
        RawRequest,
    ]

    app = App(controllers=controllers)
    app.run()


if __name__ == "__main__":
    main()
