#!/usr/bin/env python
# This file is automatically generated by pywf script
# based on the content in pyproject.toml file

__version__ = "0.1.5"
__short_description__ = "DocPack efficiently consolidates documentation from GitHub, Confluence, and files into a structured knowledge base for AI access."
__license__ = "MIT"
__author__ = "Sanhe Hu"
__author_email__ = "husanhe@gmail.com"
__maintainer__ = "Sanhe Hu"
__maintainer_email__ = "husanhe@gmail.com"

# run this script to print out the version number
if __name__ == "__main__":  # pragma: no cover
    print(__version__)
