from ydata.pipeline.identity import Identity as IdentityPipeline
from ydata.preprocessors.base import Preprocessor

class Identity(Preprocessor, IdentityPipeline):
    def __init__(self, **_) -> None: ...
    def output_dtypes(self, step: int): ...
    def input_dtypes(self, step: int): ...
    def fit(self, X, input_dtypes): ...
    def fit_transform(self, X, input_dtypes): ...
    def transform(self, X): ...
    def inverse_transform(self, X): ...
