"""
db4e/Constants/DForm.py

    Database 4 Everything
    Author: Nadim-Daniel Ghaznavi
    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
    GitHub: https://github.com/NadimGhaznavi/db4e
    License: GPL 3.0
"""

from db4e.Modules.ConstGroup import ConstGroup


class DForm(ConstGroup):
    BLOCKCHAIN_DIR_LABEL: str = "blockchain_dir_label"
    BUTTON_ROW: str = "button_row"
    CHAIN_RADIO_SET: str = "chain_radio_set"
    CONFIG_FILE_LABEL: str = "config_file_label"
    CONFIG_LABEL: str = "config_label"
    FORM_0: str = "form_0"
    FORM_1: str = "form_1"
    FORM_2: str = "form_2"
    FORM_3: str = "form_3"
    FORM_4: str = "form_4"
    FORM_5: str = "form_5"
    FORM_6: str = "form_6"
    FORM_7: str = "form_7"
    FORM_8: str = "form_8"
    FORM_16: str = "form_16"
    FORM_DATA: str = "form_data"
    FORM_BOX: str = "form_box"
    FORM_FIELD: str = "form_field"
    HASHRATE_LABEL: str = "hashrate_label"
    HEALTH_LABEL: str = "health_label"
    INFO_MSG: str = "info_msg"
    INTRO: str = "form_intro"
    INPUT_7: str = "form_input_7"
    INPUT_15: str = "form_input_15"
    INPUT_30: str = "form_input_30"
    INPUT_40: str = "form_input_40"
    INPUT_70: str = "form_input_70"
    INSTANCE_INPUT: str = "instance_input"
    INSTANCE_LABEL: str = "instance_label"
    IP_ADDR_INPUT: str = "ip_addr_input"
    IP_ADDR_LABEL: str = "ip_addr_label"
    IN_PEERS_INPUT: str = "in_peers_input"
    IN_PEERS_LABEL: str = "in_peers_label"
    FORM_LABEL: str = "form_label"
    FORM_LABEL_15: str = "form_label_15"
    FORM_LABEL_20: str = "form_label_20"
    FORM_LABEL_25: str = "form_label_25"
    GROUP_NAME_LABEL: str = "group_name_label"
    HEADER: str = "header"
    HEALTH_BOX: str = "health_box"
    INSTALL_DIR_LABEL: str = "install_dir_label"
    LOG_LEVEL_INPUT: str = "log_level_input"
    LOG_LEVEL_LABEL: str = "log_level_label"
    LOG_WIDGET: str = "log_widget"
    LOGROTATE_CONFIG_LABEL: str = "logrotate_config_label"
    MAX_LOG_FILES_INPUT: str = "max_log_files_input"
    MAX_LOG_SIZE_INPUT: str = "max_log_size_input"
    NUM_THREADS_INPUT: str = "num_threads_input"
    OUT_PEERS_INPUT: str = "out_peers_input"
    OUT_PEERS_LABEL: str = "out_peers_label"
    P2P_BIND_PORT_INPUT: str = "MAX_LOG_SIZE_INPUT"
    P2P_PORT_INPUT: str = "p2p_port_input"
    P2P_PORT_LABEL: str = "p2p_port_label"
    PANE_BOX: str = "pane_box"
    PARENT_LABEL: str = "parent_label"
    PRIORITY_NODE_1_INPUT: str = "priority_node_1_input"
    PRIORITY_NODE_2_INPUT: str = "priority_node_2_input"
    PRIORITY_PORT_1_INPUT: str = "priority_port_1_input"
    PRIORITY_PORT_2_INPUT: str = "priority_port_2_input"
    RADIO_BUTTON_TYPE: str = "radio_button_type"
    RADIO_SET: str = "radio_set"
    RPC_BIND_PORT_INPUT: str = "rpc_bind_port_input"
    SELECT_BOX: str = "select_box"
    SHARES_FOUND_PLOT: str = "shares_found_plot"
    STATIC: str = "static_content"
    STRATUM_PORT_INPUT: str = "stratum_port_input"
    STRATUM_PORT_LABEL: str = "stratum_port_label"
    TIMES: str = "times"
    UPTIME_LABEL: str = "uptime_label"
    USER_NAME_LABEL: str = "user_name_label"
    USER_WALLET_INPUT: str = "user_wallet_input"
    VENDOR_DIR_INPUT: str = "vendor_dir_input"
    ZMQ_PUB_PORT_INPUT: str = "zmq_pub_port_input"
    ZMQ_RPC_PORT_INPUT: str = "zmq_rpc_port_input"
