# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        GET: Retrieve billing info
        """
        pass

    def test_post_user(self) -> None:
        """Test case for post_user

        POST: Insert billing info
        """
        pass

    def test_put_user(self) -> None:
        """Test case for put_user

        PUT: Update billing info
        """
        pass


if __name__ == '__main__':
    unittest.main()
