# generated by https://github.com/puzl-cloud/kubesdk
#   filename:  apis__storage.k8s.io__v1beta1_openapi.json
#   timestamp: 2025-10-21T10:17:20+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import ClassVar, Dict, List, Set

from kube_models.const import *
from kube_models.loader import *
from kube_models.loader import LazyLoadModel
from kube_models.resource import *

from ...apimachinery.pkg.apis.meta.v1 import ListMeta, ObjectMeta


@dataclass(kw_only=True, frozen=True)
class VolumeAttributesClass(K8sResource):
    driverName: str
    apiVersion: str = 'storage.k8s.io/v1beta1'
    kind: str = 'VolumeAttributesClass'
    metadata: ObjectMeta = field(default_factory=ObjectMeta)
    parameters: Dict[str, str] | None = None
    api_path_: ClassVar[str] = 'apis/storage.k8s.io/v1beta1/volumeattributesclasses'
    plural_: ClassVar[str] = 'volumeattributesclasses'
    is_namespaced_: ClassVar[bool] = False
    group_: ClassVar[Optional[str]] = 'storage.k8s.io'
    apiVersion_: ClassVar[str] = 'storage.k8s.io/v1beta1'
    kind_: ClassVar[str] = 'VolumeAttributesClass'
    patch_strategies_: ClassVar[Set[PatchRequestType]] = {
        'application/json-patch+json',
        'application/merge-patch+json',
        'application/strategic-merge-patch+json',
        'application/apply-patch+cbor',
        'application/apply-patch+yaml',
    }


@dataclass(kw_only=True, frozen=True)
class VolumeAttributesClassList(LazyLoadModel):
    items: List[VolumeAttributesClass]
    apiVersion: str = 'storage.k8s.io/v1beta1'
    kind: str = 'VolumeAttributesClassList'
    metadata: ListMeta = field(default_factory=ObjectMeta)
