
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-20T19:06:35+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc430542d0596394c30ce2505294318a7094aa24",
 "version": "1.11.0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
