import pandas as pd
from _typeshed import Incomplete
from ydata.report.metrics import MetricType
from ydata.report.metrics.base_metric import BaseMetric

def reduce_dimensionality(df: pd.DataFrame, k: int = 50): ...

class MutualInformationMatrix(BaseMetric):
    def __init__(self, formatter=..., include_plots: bool = True) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> MetricType: ...
    @staticmethod
    def get_heatmap(df, title: Incomplete | None = None): ...
