from sklearn.pipeline import Pipeline as skPipeline

class Pipeline(skPipeline):
    def __init__(self, steps) -> None: ...
    def fit(self, X, input_dtypes, **fit_params): ...
    def fit_transform(self, X, input_dtypes, **fit_params): ...
