
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-20T15:20:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "db5d9b8a1823f7ec5f3107137a15b781bbf72f12",
 "version": "1.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
