from _typeshed import Incomplete

def get_aws_access_key_id(keys: Incomplete | None = None): ...
def get_aws_secret_access_key(keys: Incomplete | None = None): ...
def get_aws_security_token(keys: Incomplete | None = None): ...
def get_region(keys: Incomplete | None = None): ...
def get_endpoint_url(keys: Incomplete | None = None): ...
def get_aws_use_ssl(keys: Incomplete | None = None): ...
def get_aws_verify_ssl(keys: Incomplete | None = None): ...
def get_aws_session(aws_access_key_id: Incomplete | None = None, aws_secret_access_key: Incomplete | None = None, aws_session_token: Incomplete | None = None, region_name: Incomplete | None = None): ...
def get_aws_client(client_type, endpoint_url: Incomplete | None = None, aws_access_key_id: Incomplete | None = None, aws_secret_access_key: Incomplete | None = None, aws_session_token: Incomplete | None = None, region_name: Incomplete | None = None, aws_use_ssl: bool = True, aws_verify_ssl: Incomplete | None = None): ...
def get_aws_filesystem(credentials): ...
def get_aws_resource(resource_type, endpoint_url: Incomplete | None = None, aws_access_key_id: Incomplete | None = None, aws_secret_access_key: Incomplete | None = None, aws_session_token: Incomplete | None = None, region_name: Incomplete | None = None, aws_use_ssl: bool = True, aws_verify_ssl: Incomplete | None = None): ...
