from __future__ import annotations
from panda_math import ivec2

class Terminal:
    def __init__(self, seperate: bool, double_buffer: bool = True) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def ansi(self, ansi: str): ...
    def clear(self): ...
    @property
    def size(self) -> ivec2: ...
    @property
    def show_cursor(self) -> bool: ...
    @show_cursor.setter
    def show_cursor(self, value: bool): ...
    @property
    def cursor_pos(self) -> ivec2: ...
    def move_cursor(self, position: ivec2): ...
    def write(self, x: int, y: int, text: str): ...
    def set_char(self, x: int, y: int, char: str): ...
    def render(self): ...
    def resize_buffer(self): ...
