from _typeshed import Incomplete
from ydata.__models._cartmodel._methods import BaseMethod

class EmptyMethod(BaseMethod):
    def __init__(self, *args, **kwargs) -> None: ...
    def fit(self, X, y, *args, **kwargs) -> None: ...
    def predict(self, X, *args, **kwargs): ...

class SeqEmptyMethod(BaseMethod):
    values: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def fit(self, X, y, autoregressive: list = None, *args, **kwargs): ...
    def predict(self, X, autoregressive: list = None, *args, **kwargs): ...
