# This file was auto-generated by Fern from our API Definition.

import typing

from .templates_create_agents_from_template_response_agents_item_memory_blocks_item_deployment_id_item import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemMemoryBlocksItemDeploymentIdItem,
)

TemplatesCreateAgentsFromTemplateResponseAgentsItemMemoryBlocksItemDeploymentId = typing.Union[
    str,
    typing.Optional[str],
    typing.List[typing.Optional[TemplatesCreateAgentsFromTemplateResponseAgentsItemMemoryBlocksItemDeploymentIdItem]],
    typing.Optional[typing.Any],
]
