key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIK0WLpup4aS0ns4iRT73pJ3o+1S5nRfQLXcl0LzdBVeToAoGCCqGSM49
AwEHoUQDQgAEUJkjZ+uWW0RonMrPMon5VNtJxwkv/LDaUT459b4qs9pVxSdWh7I+
VEiEGi4VFA1C6skQ3Y1/wXZNingP5mDHgA==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6TCCAY8CFBpddKStys9t7lTgfWr8RmQU4WzAMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTEwMTgxNDEzMzJaFw0zNTEwMTYxNDEz
MzJaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABFCZI2frlltEaJzKzzKJ+VTbSccJL/yw2lE+OfW+KrPaVcUnVoeyPlRI
hBouFRQNQurJEN2Nf8F2TYp4D+Zgx4AwCgYIKoZIzj0EAwIDSAAwRQIgElTlgE2V
okzrbMjCVUIfAPF1eaWtHHJTDpRazfinoR4CIQDcEaKfsqMxYGP7emLo0wursGEB
fn0f6Anb0c6eszSCsg==
-----END CERTIFICATE-----
"""