# generated by https://github.com/puzl-cloud/kubesdk
#   timestamp: 2025-10-21T10:17:24+00:00

from kube_models.loader import loader as __loader

from .v1 import FieldSelectorAttributes, LabelSelectorAttributes, LocalSubjectAccessReview, NonResourceAttributes, NonResourceRule, ResourceAttributes, ResourceRule, SelfSubjectAccessReview, SelfSubjectAccessReviewSpec, SelfSubjectRulesReview, SelfSubjectRulesReviewSpec, SubjectAccessReview, SubjectAccessReviewSpec, SubjectAccessReviewStatus, SubjectRulesReviewStatus


FieldSelectorAttributes = __loader(FieldSelectorAttributes)
LabelSelectorAttributes = __loader(LabelSelectorAttributes)
LocalSubjectAccessReview = __loader(LocalSubjectAccessReview)
NonResourceAttributes = __loader(NonResourceAttributes)
NonResourceRule = __loader(NonResourceRule)
ResourceAttributes = __loader(ResourceAttributes)
ResourceRule = __loader(ResourceRule)
SelfSubjectAccessReview = __loader(SelfSubjectAccessReview)
SelfSubjectAccessReviewSpec = __loader(SelfSubjectAccessReviewSpec)
SelfSubjectRulesReview = __loader(SelfSubjectRulesReview)
SelfSubjectRulesReviewSpec = __loader(SelfSubjectRulesReviewSpec)
SubjectAccessReview = __loader(SubjectAccessReview)
SubjectAccessReviewSpec = __loader(SubjectAccessReviewSpec)
SubjectAccessReviewStatus = __loader(SubjectAccessReviewStatus)
SubjectRulesReviewStatus = __loader(SubjectRulesReviewStatus)

__all__ = ['FieldSelectorAttributes', 'LabelSelectorAttributes', 'LocalSubjectAccessReview', 'NonResourceAttributes', 'NonResourceRule', 'ResourceAttributes', 'ResourceRule', 'SelfSubjectAccessReview', 'SelfSubjectAccessReviewSpec', 'SelfSubjectRulesReview', 'SelfSubjectRulesReviewSpec', 'SubjectAccessReview', 'SubjectAccessReviewSpec', 'SubjectAccessReviewStatus', 'SubjectRulesReviewStatus']



