# Generated by Django 5.1.6 on 2025-08-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfchelseru', '0013_payment_authority_payment_data_payment_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
