# generated by https://github.com/puzl-cloud/kubesdk
#   timestamp: 2025-10-21T10:17:24+00:00

from kube_models.loader import loader as __loader

from .v1 import CustomResourceColumnDefinition, CustomResourceConversion, CustomResourceDefinition, CustomResourceDefinitionCondition, CustomResourceDefinitionList, CustomResourceDefinitionNames, CustomResourceDefinitionSpec, CustomResourceDefinitionStatus, CustomResourceDefinitionVersion, CustomResourceSubresourceScale, CustomResourceSubresourceStatus, CustomResourceSubresources, CustomResourceValidation, ExternalDocumentation, JSON, JSONSchemaProps, JSONSchemaPropsOrArray, JSONSchemaPropsOrBool, JSONSchemaPropsOrStringArray, SelectableField, ServiceReference, ValidationRule, WebhookClientConfig, WebhookConversion


CustomResourceColumnDefinition = __loader(CustomResourceColumnDefinition)
CustomResourceConversion = __loader(CustomResourceConversion)
CustomResourceDefinition = __loader(CustomResourceDefinition)
CustomResourceDefinitionCondition = __loader(CustomResourceDefinitionCondition)
CustomResourceDefinitionList = __loader(CustomResourceDefinitionList)
CustomResourceDefinitionNames = __loader(CustomResourceDefinitionNames)
CustomResourceDefinitionSpec = __loader(CustomResourceDefinitionSpec)
CustomResourceDefinitionStatus = __loader(CustomResourceDefinitionStatus)
CustomResourceDefinitionVersion = __loader(CustomResourceDefinitionVersion)
CustomResourceSubresourceScale = __loader(CustomResourceSubresourceScale)
CustomResourceSubresourceStatus = __loader(CustomResourceSubresourceStatus)
CustomResourceSubresources = __loader(CustomResourceSubresources)
CustomResourceValidation = __loader(CustomResourceValidation)
ExternalDocumentation = __loader(ExternalDocumentation)
JSONSchemaProps = __loader(JSONSchemaProps)
SelectableField = __loader(SelectableField)
ServiceReference = __loader(ServiceReference)
ValidationRule = __loader(ValidationRule)
WebhookClientConfig = __loader(WebhookClientConfig)
WebhookConversion = __loader(WebhookConversion)

__all__ = ['CustomResourceColumnDefinition', 'CustomResourceConversion', 'CustomResourceDefinition', 'CustomResourceDefinitionCondition', 'CustomResourceDefinitionList', 'CustomResourceDefinitionNames', 'CustomResourceDefinitionSpec', 'CustomResourceDefinitionStatus', 'CustomResourceDefinitionVersion', 'CustomResourceSubresourceScale', 'CustomResourceSubresourceStatus', 'CustomResourceSubresources', 'CustomResourceValidation', 'ExternalDocumentation', 'JSON', 'JSONSchemaProps', 'JSONSchemaPropsOrArray', 'JSONSchemaPropsOrBool', 'JSONSchemaPropsOrStringArray', 'SelectableField', 'ServiceReference', 'ValidationRule', 'WebhookClientConfig', 'WebhookConversion']



