from rdkit.Chem import SDMolSupplier as SDMolSupplier
from rdkit.Chem.rdchem import Mol as Mol

class SDFLoader:
    @staticmethod
    def closeWarning() -> None: ...
    @staticmethod
    def openWarning() -> None: ...
    @staticmethod
    def readDataFromFile(sdfDoc: str, startIndex: int = 0, endIndex: int = -1, ignore_error: bool = True) -> tuple[list[Mol], int, int]: ...
    @staticmethod
    def readDataFromDir(sdfDir: str, recursive: bool = True, ignore_error: bool = True) -> tuple[list[Mol], int, int]: ...
    @staticmethod
    def readDataFromText(sdfText: str, ignore_error: bool = True) -> tuple[list[Mol], int, int]: ...
    @staticmethod
    def splitDataByMarker(sdfText: str, marker: str = '$$$$\n', strict: bool = True) -> list[str]: ...
