# Generated by Django 4.2.23 on 2025-10-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autosrp', '0002_alter_appsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created'], 'permissions': [('basic_access', 'Can access Auto SRP'), ('manage', 'Can manage Auto SRP settings'), ('submit', 'Can submit Auto SRP requests'), ('review', 'Can review Auto SRP batches')], 'verbose_name': 'Battle Report', 'verbose_name_plural': 'Battle Reports'},
        ),
    ]
