import pandas as pd
from _typeshed import Incomplete
from ydata.utils.random import RandomSeed as RandomSeed

NAN_KEY: str
NUMTOCAT_KEY: str

class Preprocessor:
    processing_dict: Incomplete
    dt_cols: Incomplete
    cat_cols_encoder: Incomplete
    cat_str_encoder: Incomplete
    def __init__(self) -> None: ...
    def preprocess_cat_str(self, X, dtypes): ...
    def postprocess_cat_str(self, X): ...
    def preprocess(self, X, synth, columns_info): ...
    def postprocess(self, X: pd.DataFrame, random_state: RandomSeed = None): ...

class SeqPreprocessor(Preprocessor):
    processing_dict: Incomplete
    dt_cols: Incomplete
    cat_cols_encoder: Incomplete
    def __init__(self) -> None: ...
    def preprocess(self, X, synth, columns_info) -> tuple[pd.DataFrame, dict]: ...
    def postprocess(self, X, synth, columns_info, random_state: RandomSeed = None): ...
