# This file was auto-generated by Fern from our API Definition.

import typing

from .templates_create_agents_from_template_response_agents_item_tool_rules_item_child_output_mapping_prompt_template_item import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemChildOutputMappingPromptTemplateItem,
)

TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemChildOutputMappingPromptTemplate = typing.Union[
    str,
    typing.Optional[str],
    typing.List[
        typing.Optional[
            TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemChildOutputMappingPromptTemplateItem
        ]
    ],
    typing.Optional[typing.Any],
]
