from _typeshed import Incomplete
from pandas import DataFrame as pdDataFrame
from ydata.quality.outlier.prototype import BaseProjectionOperator

class PCA(BaseProjectionOperator):
    """PCA projector."""
    model: Incomplete
    columns: Incomplete
    n_components: int
    def __init__(self) -> None: ...
    def fit_transform(self, X: pdDataFrame, n_components: int = 2, columns: list[str] | None = None) -> pdDataFrame: ...
    def fit(self, X: pdDataFrame, n_components: int = 2, columns: list[str] | None = None): ...
    def transform(self, X: pdDataFrame) -> pdDataFrame: ...
    def summary(self) -> dict: ...
