MAJOR_VERSION = 1
MINOR_VERSION = 17
PATCH_VERSION = 17
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version']
