from _typeshed import Incomplete

def get_account_key(keys: Incomplete | None = None): ...
def get_connection_string(keys: Incomplete | None = None): ...
def get_blob_service_connection(connection_string: Incomplete | None = None): ...
def get_datalake_service_connection(connection_string: Incomplete | None = None): ...
def parse_path(path): ...
