# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_fiscal_document.models.create_invoice_request import CreateInvoiceRequest

class TestCreateInvoiceRequest(unittest.TestCase):
    """CreateInvoiceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInvoiceRequest:
        """Test CreateInvoiceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInvoiceRequest`
        """
        model = CreateInvoiceRequest()
        if include_optional:
            return CreateInvoiceRequest(
                transaction_ids = [
                    56
                    ],
                source_id = 56,
                sequence_id = 56,
                source_kind = 'GROUP_PROFILE',
                user_id = 56,
                guest_id = 56
            )
        else:
            return CreateInvoiceRequest(
                transaction_ids = [
                    56
                    ],
                source_id = 56,
                source_kind = 'GROUP_PROFILE',
                guest_id = 56,
        )
        """

    def testCreateInvoiceRequest(self):
        """Test CreateInvoiceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
