from typing import Any, ItemsView, Iterator, KeysView, MutableSequence, Sequence, ValuesView

from typing_extensions import Protocol


class GetSequence(Protocol):
    def __getitem__(self, key: str, /) -> Sequence[Any]: ...

class GetMutableSequence(Protocol):
    def __getitem__(self, key: str, /) -> MutableSequence[Any]: ...

class GetItem(Protocol):
    def __getitem__(self, key: str, /) -> Any: ...

class SetSequence(Protocol):
    def __setitem__(self, key: str, value: Sequence[Any]) -> None: ...

class KeyNames(Protocol):
    def keys(self) -> KeysView[str]: ...

class SequenceItems(Protocol):
    def items(self) -> ItemsView[str, Sequence[Any]]: ...

class SequenceValues(Protocol):
    def values(self) -> ValuesView[Sequence[Any]]: ...

class Clear(Protocol):
    def clear(self) -> None: ...

class DeleteItem(Protocol):
    def __delitem__(self, key: str, /) -> None: ...

class KeyNamesSequenceValues(KeyNames, SequenceValues, Protocol):
    ...

class KeyNamesGetSequence(KeyNames, GetSequence, Protocol):
    ...

class DataMapping(GetSequence, KeyNames, SequenceValues, SequenceItems, Protocol):
    ...

class MutableDataMapping(DataMapping, SetSequence, DeleteItem, Clear, Protocol):
    ...

class KeyNamesGetItem(KeyNames, GetItem, Protocol):
    def __iter__(self) -> Iterator[str]: ...

class KeyNamesGetMutableSequence(KeyNames, GetMutableSequence, Protocol):
    ...

class KeyNamesGetMutableSequenceSequenceValues(KeyNamesGetMutableSequence, SequenceValues, Protocol):
    def __contains__(self, key: str) -> bool: ...

class SequenceItemsGetMutableSequence(SequenceItems, GetMutableSequence, Protocol):
    ...
