# generated by puzl.cloud generator:
#   filename:  apis__certificates.k8s.io__v1beta1_openapi.json
#   timestamp: 2025-10-20T15:38:48+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import ClassVar, List, Set

from k8s_models.const import *
from k8s_models.loader import *
from k8s_models.loader import LazyLoadModel
from k8s_models.resource import *

from ...apimachinery.pkg.apis.meta.v1 import ListMeta, ObjectMeta


@dataclass(kw_only=True, frozen=True)
class ClusterTrustBundleSpec(LazyLoadModel):
    trustBundle: str
    signerName: str | None = None


@dataclass(kw_only=True, frozen=True)
class ClusterTrustBundle(K8sResource):
    spec: ClusterTrustBundleSpec
    apiVersion: str = 'certificates.k8s.io/v1beta1'
    kind: str = 'ClusterTrustBundle'
    metadata: ObjectMeta = field(default_factory=ObjectMeta)
    api_path_: ClassVar[str] = 'apis/certificates.k8s.io/v1beta1/clustertrustbundles'
    plural_: ClassVar[str] = 'clustertrustbundles'
    is_namespaced_: ClassVar[bool] = False
    group_: ClassVar[Optional[str]] = 'certificates.k8s.io'
    apiVersion_: ClassVar[str] = 'certificates.k8s.io/v1beta1'
    kind_: ClassVar[str] = 'ClusterTrustBundle'
    patch_strategies_: ClassVar[Set[PatchRequestType]] = {
        'application/merge-patch+json',
        'application/json-patch+json',
        'application/apply-patch+yaml',
        'application/strategic-merge-patch+json',
        'application/apply-patch+cbor',
    }


@dataclass(kw_only=True, frozen=True)
class ClusterTrustBundleList(LazyLoadModel):
    items: List[ClusterTrustBundle]
    apiVersion: str = 'certificates.k8s.io/v1beta1'
    kind: str = 'ClusterTrustBundleList'
    metadata: ListMeta = field(default_factory=ObjectMeta)
