"""Minimal warning stubs for BeautifulSoup."""

class AttributeResemblesVariableWarning(UserWarning): ...
class GuessedAtParserWarning(UserWarning): ...
class MarkupResemblesLocatorWarning(UserWarning): ...
class UnusualUsageWarning(UserWarning): ...
class XMLParsedAsHTMLWarning(UserWarning): ...