class StyleHTML:
    @staticmethod
    def apply(format: str, string: str): ...
    @staticmethod
    def bold(string: str): ...
    @staticmethod
    def strong(string: str): ...
    @staticmethod
    def italic(string: str): ...
    @staticmethod
    def h1(string: str): ...
    @staticmethod
    def h2(string: str): ...
    @staticmethod
    def paragraph(string: str): ...
