from pygments.lexers.robotframework import Setting as Setting
from ydata_profiling.config import Settings as Settings
from ydata_profiling.report.presentation.core.renderable import Renderable as Renderable

def render_categorical_frequency(config: Settings, summary: dict, varid: str) -> Renderable: ...
def render_dirty_categories(config: Settings, summary: dict, varid: str) -> Renderable: ...
def render_categorical_length(config: Settings, summary: dict, varid: str) -> tuple[Renderable, Renderable]: ...
def render_categorical_unicode(config: Settings, summary: dict, varid: str) -> tuple[Renderable, Renderable]: ...
def render_categorical(config: Settings, summary: dict) -> dict: ...
