from ydata.pipeline.base import Pipeline

class Identity(Pipeline):
    def __init__(self) -> None: ...
    def fit(self, X, input_dtypes): ...
    def fit_transform(self, X, input_dtypes): ...
    def transform(self, X): ...
    def inverse_transform(self, X): ...
