# This file was auto-generated by Fern from our API Definition.

import typing

TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigCompatibilityTypeItem = typing.Union[
    typing.Literal["gguf"], typing.Literal["mlx"], typing.Optional[str]
]
