# This file was auto-generated by Fern from our API Definition.

import typing

from .templates_create_agents_from_template_response_agents_item_tool_rules_item_item_child_arg_nodes_child_arg_nodes_item import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesChildArgNodesItem,
)

TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesChildArgNodes = typing.Union[
    typing.List[TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesChildArgNodesItem],
    typing.Optional[str],
    typing.List[
        typing.Optional[
            TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesChildArgNodesItem
        ]
    ],
    typing.Optional[typing.Any],
]
