# This file was auto-generated by Fern from our API Definition.

import typing

from .templates_create_agents_from_template_response_agents_item_multi_agent_group_agent_ids_hidden_item import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsHiddenItem,
)

TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsHidden = typing.Union[
    bool,
    typing.Optional[str],
    typing.List[typing.Optional[TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsHiddenItem]],
    typing.Optional[typing.Any],
]
