from _typeshed import Incomplete

DEFAULT_SCOPES: Incomplete

def get_key_path(keys: Incomplete | None = None): ...
def get_keyfile_dict(keys: Incomplete | None = None): ...
def get_scopes(keys: Incomplete | None = None): ...
def get_gc_credentials(key_path: Incomplete | None = None, keyfile_dict: Incomplete | None = None, scopes: Incomplete | None = None):
    """Returns the Credentials object for Google API."""
def get_gc_client(project_id: Incomplete | None = None, key_path: Incomplete | None = None, keyfile_dict: Incomplete | None = None, credentials: Incomplete | None = None, scopes: Incomplete | None = None): ...
def get_bq_client(project_id: Incomplete | None = None, key_path: Incomplete | None = None, keyfile_dict: Incomplete | None = None, credentials: Incomplete | None = None, scopes: Incomplete | None = None): ...
def get_gc_filesystem(client, bucket_name): ...
