from _typeshed import Incomplete
from ydata.dataset import Dataset as Dataset
from ydata.report.metrics.score import MetricScore, MetricType

class BaseMetric:
    exclude_entity_col: Incomplete
    def __init__(self, formatter, exclude_entity_col: bool = True) -> None: ...
    def evaluate(self, source, synthetic, **kwargs) -> MetricScore: ...
    @property
    def type(self) -> MetricType: ...
    @property
    def name(self) -> str: ...
