
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-19T02:35:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "612f3dd3cba4d73cfcea4b5329079e20aa31523d",
 "version": "1.6.dev2542"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
