import _cython_3_0_11
from _typeshed import Incomplete

BatchFunctionCaller_abort: _cython_3_0_11.cython_function_or_method
BatchFunctionCaller_currentIndex: _cython_3_0_11.cython_function_or_method
BatchFunctionCaller_execute: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_freezingPoint: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_saturationPartialPressure_T: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificAbsoluteGasEntropy_pTn: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificAbsoluteLiquidEntropy_pTn: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificAbsoluteSolidEntropy_pTn: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificEnthalpyOfDesublimation_T: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificEnthalpyOfFormation_n: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificEnthalpyOfPureGas_Tn: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificEnthalpyOfVaporisation_T: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificEntropyOfPureGas_pTxin: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificGasEnthalpy_refStateHf_Tn: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificIsobaricHeatCapacityOfPureGas_Tn: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificLiquidEnthalpy_refStateHf_Tn: _cython_3_0_11.cython_function_or_method
GasObjectFunctions_specificSolidEnthalpy_refStateHf_Tn: _cython_3_0_11.cython_function_or_method
Gas_isValid_getInfo_errorInterface: _cython_3_0_11.cython_function_or_method
Gas_maximalTemperature: _cython_3_0_11.cython_function_or_method
Gas_minimalTemperature: _cython_3_0_11.cython_function_or_method
Gas_molarMass: _cython_3_0_11.cython_function_or_method
Liquid_isValid_getInfo_errorInterface: _cython_3_0_11.cython_function_or_method
Liquid_maximalTemperature_xi_: _cython_3_0_11.cython_function_or_method
Liquid_minimalTemperature_xi_: _cython_3_0_11.cython_function_or_method
VLEFluid_Cached_molarMass: _cython_3_0_11.cython_function_or_method
VLEFluid_isValid_getInfo_errorInterface: _cython_3_0_11.cython_function_or_method
VLEFluid_meanDensity_phAhB: _cython_3_0_11.cython_function_or_method
__reduce_cython__: _cython_3_0_11.cython_function_or_method
__setstate_cython__: _cython_3_0_11.cython_function_or_method
__test__: dict
clear_medium_name_cache: _cython_3_0_11.cython_function_or_method
free_all_memory: _cython_3_0_11.cython_function_or_method
getGasInformation_pointer: _cython_3_0_11.cython_function_or_method
getLiquidInformation_pointer: _cython_3_0_11.cython_function_or_method
getVLEFluidInformation_pointer: _cython_3_0_11.cython_function_or_method
get_all_adsorption_and_absorption_names: _cython_3_0_11.cython_function_or_method
get_all_condensing_gas_names: _cython_3_0_11.cython_function_or_method
get_all_gas_names: _cython_3_0_11.cython_function_or_method
get_all_liquid_mixture_names: _cython_3_0_11.cython_function_or_method
get_all_liquid_names: _cython_3_0_11.cython_function_or_method
get_all_vleFluid_names: _cython_3_0_11.cython_function_or_method
get_closest_vleFluid_dpT: _cython_3_0_11.cython_function_or_method
get_data_path: _cython_3_0_11.cython_function_or_method
get_fit_config: _cython_3_0_11.cython_function_or_method
get_fit_config_eo: _cython_3_0_11.cython_function_or_method
get_fit_data: _cython_3_0_11.cython_function_or_method
get_fit_data_eo: _cython_3_0_11.cython_function_or_method
get_fluid_information: _cython_3_0_11.cython_function_or_method
get_fluid_information_eo: _cython_3_0_11.cython_function_or_method
license_is_valid: _cython_3_0_11.cython_function_or_method
logger_flush_messages: _cython_3_0_11.cython_function_or_method
revision: _cython_3_0_11.cython_function_or_method
set_data_path: _cython_3_0_11.cython_function_or_method
version: _cython_3_0_11.cython_function_or_method

class ExternalObject:
    identifier_value: Incomplete
    ptr: Incomplete
    py_session: Incomplete
    @classmethod
    def __init__(cls, *args, **kwargs) -> None:
        """
        Initialize self.  See help(type(self)) for accurate signature.
        """
    def __reduce__(self): ...
