# Copyright (C) 2025 <UTN FRA>
#
# Author: Facundo Falcone <f.falcone@sistemas-utnfra.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import pygame as pg

class AnimatedLifeBar:
    def __init__(self, screen: pg.Surface, current_healt: float, maximum_healt: float, health_bar_length, pos: tuple[int,int], health_speed: int=20, bar_type: str = 'vitality') -> None: ...
    def set_damage(self, amount: int) -> None: ...
    def set_health(self, amount: int) -> None: ...
    def get_max_amount(self) -> int: ...
    def get_actual_amount(self) -> int: ...
    def advanced_health(self) -> None: ...
    def update_target_health(self, amount: int) -> None: ...
    def update(self, actual_health: int) -> None: ...
    def draw(self) -> None: ...