# generated by https://github.com/puzl-cloud/kubesdk
#   timestamp: 2025-10-21T10:17:24+00:00

from kube_models.loader import loader as __loader

from .v1 import NodeSelector, NodeSelectorRequirement, NodeSelectorTerm


NodeSelector = __loader(NodeSelector)
NodeSelectorRequirement = __loader(NodeSelectorRequirement)
NodeSelectorTerm = __loader(NodeSelectorTerm)

__all__ = ['NodeSelector', 'NodeSelectorRequirement', 'NodeSelectorTerm']



