# ruff: noqa
# type: ignore
# Copyright (c) OpenMMLab. All rights reserved.
from .optimizer import (
    OPTIM_WRAPPER_CONSTRUCTORS,
    OPTIMIZERS,
    AmpOptimWrapper,
    BaseOptimWrapper,
    DefaultOptimWrapperConstructor,
    OptimWrapper,
    OptimWrapperDict,
    build_optim_wrapper,
)

# yapf: disable
from .scheduler import (ConstantLR, ConstantMomentum, ConstantParamScheduler,
                        CosineAnnealingLR, CosineAnnealingMomentum,
                        CosineAnnealingParamScheduler, ExponentialLR,
                        ExponentialMomentum, ExponentialParamScheduler,
                        LinearLR, LinearMomentum, LinearParamScheduler,
                        MultiStepLR, MultiStepMomentum,
                        MultiStepParamScheduler, OneCycleLR,
                        OneCycleParamScheduler, PolyLR, PolyMomentum,
                        PolyParamScheduler, ReduceOnPlateauLR,
                        ReduceOnPlateauMomentum, ReduceOnPlateauParamScheduler,
                        StepLR, StepMomentum, StepParamScheduler,
                        _ParamScheduler)

# yapf: enable
__all__ = [
    "OPTIMIZERS",
    "OPTIM_WRAPPER_CONSTRUCTORS",
    "AmpOptimWrapper",
    "BaseOptimWrapper",
    "ConstantLR",
    "ConstantMomentum",
    "ConstantParamScheduler",
    "CosineAnnealingLR",
    "CosineAnnealingMomentum",
    "CosineAnnealingParamScheduler",
    "DefaultOptimWrapperConstructor",
    "ExponentialLR",
    "ExponentialMomentum",
    "ExponentialParamScheduler",
    "LinearLR",
    "LinearMomentum",
    "LinearParamScheduler",
    "MultiStepLR",
    "MultiStepMomentum",
    "MultiStepParamScheduler",
    "OneCycleLR",
    "OneCycleParamScheduler",
    "OptimWrapper",
    "OptimWrapperDict",
    "PolyLR",
    "PolyMomentum",
    "PolyParamScheduler",
    "ReduceOnPlateauLR",
    "ReduceOnPlateauMomentum",
    "ReduceOnPlateauParamScheduler",
    "StepLR",
    "StepMomentum",
    "StepParamScheduler",
    "_ParamScheduler",
    "build_optim_wrapper",
]
