"""
Useless facts database and functions
"""

import random
from typing import List, Dict, Optional

# Database of useless facts organized by category
USELESS_FACTS = {
    "animals": [
        "A group of flamingos is called a 'flamboyance'.",
        "Octopuses have three hearts and blue blood.",
        "A shrimp's heart is in its head.",
        "Dolphins have names for each other.",
        "A group of owls is called a 'parliament'.",
        "Butterflies taste with their feet.",
        "A group of crows is called a 'murder'.",
        "Elephants are the only animals that can't jump.",
        "A group of rhinos is called a 'crash'.",
        "Cows have best friends and get stressed when separated.",
        "A group of giraffes is called a 'tower'.",
        "Penguins propose to their mates with pebbles.",
        "A group of kangaroos is called a 'mob'.",
        "Sloths only poop once a week.",
        "A group of hedgehogs is called a 'prickle'.",
        "Bats are the only mammals that can fly.",
        "A group of zebras is called a 'dazzle'.",
        "Wombat poop is cube-shaped.",
        "A group of hippos is called a 'bloat'.",
        "Dolphins sleep with one eye open.",
        "A group of peacocks is called a 'muster'.",
        "Cats spend 70% of their lives sleeping.",
        "A group of turkeys is called a 'rafter'.",
        "Pigs can't look up at the sky.",
        "A group of swans is called a 'lamentation'.",
        "Rabbits can't vomit.",
        "A group of eagles is called a 'convocation'.",
        "Horses can't burp.",
        "A group of ravens is called a 'conspiracy'.",
        "Koalas have fingerprints almost identical to humans.",
        "A group of pelicans is called a 'squadron'.",
        "Sharks have been around longer than trees.",
        "A group of starlings is called a 'murmuration'.",
        "Giraffes have the same number of neck vertebrae as humans.",
        "A group of geese is called a 'gaggle'.",
        "Polar bears are left-handed.",
        "A group of lions is called a 'pride'.",
        "Turtles can breathe through their butts.",
        "A group of elephants is called a 'herd'.",
        "Dogs have a sense of time.",
        "A group of monkeys is called a 'troop'.",
        "Cats have a third eyelid.",
        "A group of bears is called a 'sleuth'.",
        "Rats laugh when tickled.",
        "A group of wolves is called a 'pack'.",
        "Chickens can remember over 100 different faces.",
        "A group of deer is called a 'herd'.",
        "Squirrels plant thousands of trees by forgetting where they buried nuts.",
        "A group of foxes is called a 'skulk'.",
        "Bees can recognize human faces.",
        "A group of badgers is called a 'cete'.",
        "Dolphins have been observed using tools.",
        "A group of otters is called a 'romp'.",
        "Crows can recognize human faces for years.",
        "A group of beavers is called a 'colony'.",
        "Parrots can live up to 80 years.",
        "A group of seals is called a 'pod'.",
        "Whales are the largest animals to have ever lived.",
        "Sharks have been around for 400 million years.",
        "A group of sharks is called a 'shiver'.",
        "Jellyfish have been around for 500 million years.",
        "Starfish can regenerate lost arms.",
        "A group of starfish is called a 'galaxy'.",
        "Octopuses have 9 brains.",
        "Squid have the largest eyes of any animal.",
        "Lobsters can live up to 100 years.",
        "Crabs can walk in any direction.",
        "Shrimp can make a sound louder than a jet engine.",
        "Lobsters pee out of their faces.",
        "A snail can sleep for 3 years.",
        "Hummingbirds are the only birds that can fly backwards.",
        "A crocodile cannot stick its tongue out.",
        "Ants never sleep.",
        "Frogs can't swallow with their eyes open.",
        "A group of porcupines is called a 'prickle'.",
        "Moths have no stomach.",
        "Blue whales hearts can weigh as much as a car.",
        "Seahorses mate for life.",
        "A tiger's skin is striped like its fur.",
        "Cats have over 20 different vocalizations.",
        "Dogs noses are as unique as human fingerprints.",
        "Gorillas can catch human colds.",
        "A single elephant tooth can weigh 9 pounds.",
        "Owls can rotate their heads 270 degrees.",
        "Penguins only have one mate their entire lives.",
        "Chimpanzees can recognize themselves in mirrors.",
        "Dolphins can call each other by name.",
        "Bees do a waggle dance to communicate.",
        "Wolves can hear sounds up to 6 miles away.",
        "Kangaroos can't walk backwards.",
        "A group of locusts is called a 'plague'.",
        "Butterflies have four wings not two.",
        "Goldfish can live up to 40 years.",
        "A sloth takes two weeks to digest its food.",
        "Armadillos always give birth to identical quadruplets.",
        "A group of cobras is called a 'quiver'.",
        "Polar bear fur is actually transparent.",
        "A chameleon's tongue is twice as long as its body.",
        "Platypuses don't have stomachs.",
        "Bats always turn left when leaving a cave.",
        "A woodpecker's tongue wraps around its brain.",
        "Cows can walk upstairs but not downstairs.",
    ],
    "science": [
        "Bananas are berries, but strawberries aren't.",
        "Honey never spoils.",
        "The human brain is 80% water.",
        "There are more possible chess games than atoms in the universe.",
        "The human body contains enough carbon to make 9,000 pencils.",
        "Water can boil and freeze at the same time.",
        "A day on Venus is longer than a year on Venus.",
        "The Eiffel Tower can be 15 cm taller during summer.",
        "Glass is actually a liquid, not a solid.",
        "Lightning strikes the Earth 100 times every second.",
        "The sun makes up 99.86% of the solar system's mass.",
        "A teaspoon of neutron star would weigh 6 billion tons.",
        "There are more stars in space than grains of sand on Earth.",
        "Hot water freezes faster than cold water.",
        "The human body glows in the dark but the light is too weak to see.",
        "Stomach acid is strong enough to dissolve razor blades.",
        "Your blood makes up about 8% of your body weight.",
        "Humans share 50% of their DNA with bananas.",
        "The Earth's core is as hot as the sun's surface.",
        "Sound travels 15 times faster through steel than air.",
        "A single bolt of lightning contains enough energy to toast 100,000 slices of bread.",
        "The speed of light is 299,792,458 meters per second.",
        "Water expands by 9% when it freezes.",
        "The average cloud weighs 1.1 million pounds.",
        "A cubic inch of human bone can bear a weight of 19,000 lbs.",
        "Your fingernails grow four times faster than your toenails.",
        "The human eye can distinguish about 10 million different colors.",
        "Your stomach produces a new layer of mucus every two weeks.",
        "Helium can work against gravity.",
        "The strongest muscle in the body is the tongue.",
        "Babies have 300 bones but adults only have 206.",
        "It takes 8 minutes for light from the sun to reach Earth.",
        "The human heart beats about 100,000 times per day.",
        "Your left lung is smaller than your right lung to make room for your heart.",
        "The human nose can detect over 1 trillion scents.",
        "Humans lose about 50-100 hairs per day.",
        "The average person produces enough saliva in their lifetime to fill two swimming pools.",
        "Your bones are 4 times stronger than concrete.",
        "The human body has enough fat to make seven bars of soap.",
        "Blood cells travel through your body in about 60 seconds.",
        "The human brain can read up to 1,000 words per minute.",
        "Corneas are the only body part with no blood supply.",
        "Your skin completely replaces itself every 28 days.",
        "The human body contains about 37 trillion cells.",
        "You blink about 20,000 times per day.",
        "The human skeleton is constantly being renewed.",
        "Your ears never stop growing.",
        "The human body produces 25 million new cells each second.",
        "Your fingertips can detect vibrations as small as one billionth of a meter.",
        "The human body has enough iron to make a 3-inch nail.",
        "Your brain uses 20% of your body's oxygen.",
        "The human jaw can exert 200 pounds of pressure.",
        "Your heartbeat changes and mimics the music you listen to.",
        "Diamonds rain on Jupiter and Saturn.",
        "A year on Mercury is just 88 days long.",
        "Mars appears red because of iron oxide on its surface.",
        "Neptune has the fastest winds in the solar system.",
        "Saturn could float in water because it's less dense.",
        "Uranus rotates on its side.",
        "The moon is moving away from Earth at 3.78 cm per year.",
        "Venus rotates backwards compared to other planets.",
        "The sun is 109 times wider than Earth.",
        "Jupiter has 79 known moons.",
        "The Milky Way galaxy contains 100-400 billion stars.",
        "A black hole's gravitational pull is so strong that light can't escape.",
        "Neutron stars can spin 600 times per second.",
        "The universe is about 13.8 billion years old.",
        "Space is completely silent.",
        "A day on Pluto is equal to 153 hours on Earth.",
        "The footprints on the moon will be there for 100 million years.",
        "The sun's mass decreases by 4 million tons every second.",
        "Mercury has ice despite being the closest planet to the sun.",
        "The Great Red Spot on Jupiter is a storm that has raged for centuries.",
        "Saturn's rings are made of ice and rock.",
        "Mars has the largest volcano in the solar system.",
        "Venus has more volcanoes than any other planet.",
        "Earth is the only planet not named after a god.",
        "The Andromeda galaxy is on a collision course with the Milky Way.",
        "The coldest place in the universe is the Boomerang Nebula.",
        "White dwarfs are so dense that a teaspoon would weigh 5 tons.",
        "The sun will eventually become a red giant and engulf Earth.",
        "Black holes can evaporate through Hawking radiation.",
        "Time passes slower near massive objects due to gravity.",
        "The universe is expanding faster than the speed of light.",
        "Quantum particles can exist in multiple places at once.",
        "Electrons can tunnel through barriers they shouldn't be able to cross.",
        "The universe's temperature is 2.7 Kelvin.",
        "Antimatter exists but is extremely rare.",
        "Neutrons in atoms are held together by the strong nuclear force.",
        "The Higgs boson is known as the God particle.",
        "Dark matter makes up 85% of the universe's mass.",
        "Dark energy causes the universe's expansion to accelerate.",
        "The observable universe is 93 billion light-years in diameter.",
        "Gravity is the weakest of the four fundamental forces.",
        "Photons have no mass.",
        "Absolute zero is -273.15 degrees Celsius.",
        "Superconductors have zero electrical resistance.",
        "Graphene is the strongest material known to man.",
        "Water is the only substance that is less dense as a solid.",
        "Helium is the only element that cannot be solidified by lowering temperature alone.",
    ],
    "history": [
        "Cleopatra lived closer to the Moon landing than to the pyramids.",
        "Oxford University is older than the Aztec Empire.",
        "The shortest war lasted 38-45 minutes.",
        "Napoleon was actually average height.",
        "The Great Wall of China is not visible from space.",
        "Romans brushed their teeth with urine.",
        "The first recorded use of 'hello' was in 1827.",
        "Ancient Egyptians shaved their eyebrows to mourn cats.",
        "The first computer bug was an actual moth.",
        "The Eiffel Tower was originally intended for Barcelona.",
        "The Great Pyramid was the tallest structure for 3,800 years.",
        "Vikings never wore horned helmets.",
        "Albert Einstein's brain was stolen after his death.",
        "The Apollo 11 mission had less computing power than a modern phone.",
        "The last execution by guillotine in France was in 1977.",
        "The Colosseum was originally called the Flavian Amphitheatre.",
        "Mummies were once used as medicine in Europe.",
        "The Leaning Tower of Pisa never stood straight.",
        "Leonardo da Vinci could write with one hand and draw with the other simultaneously.",
        "Pyramids were originally white and shiny.",
        "The first alarm clock could only ring at 4 AM.",
        "Ancient Romans used crushed mouse brains as toothpaste.",
        "The chainsaw was originally invented to assist in childbirth.",
        "Ketchup was sold as medicine in the 1830s.",
        "Coca-Cola originally contained cocaine.",
        "The fortune cookie was invented in San Francisco.",
        "Hawaii was once an independent kingdom.",
        "Alaska was purchased from Russia for just $7.2 million.",
        "The first email was sent in 1971.",
        "The fax machine was invented before the telephone.",
        "The first computer was invented in the 1940s and took up an entire room.",
        "The first video game was created in 1958.",
        "The microwave was invented by accident.",
        "The first mobile phone weighed 2 pounds.",
        "The first webcam was created to monitor a coffee pot.",
        "Nintendo was founded in 1889 as a playing card company.",
        "The first credit card was introduced in 1950.",
        "Sliced bread was invented in 1928.",
        "The first television was invented in 1927.",
        "Bubble wrap was originally designed to be wallpaper.",
        "Play-Doh was originally a wallpaper cleaner.",
        "Frisbees were originally pie tins from a bakery.",
        "Slinky was invented by accident.",
        "Post-it notes were invented by accident.",
        "Velcro was invented after a man noticed burrs sticking to his dog.",
        "The popsicle was invented by an 11-year-old.",
        "Potato chips were invented out of spite.",
        "The sandwich was invented by the Earl of Sandwich.",
        "Donuts with holes were invented by a ship captain.",
        "The ice cream cone was invented at the 1904 World's Fair.",
        "Chewing gum has been around for 9,000 years.",
        "The Statue of Liberty was originally copper-colored.",
        "Mount Rushmore was never completed.",
        "The White House wasn't always called the White House.",
        "George Washington never lived in Washington, D.C.",
        "Thomas Jefferson invented the swivel chair.",
        "Abraham Lincoln is in the Wrestling Hall of Fame.",
        "John Tyler, the 10th President, has living grandchildren.",
        "Ronald Reagan was a lifeguard who saved 77 people.",
        "JFK's assassin Lee Harvey Oswald was killed on live TV.",
        "The first President to appear on TV was Franklin D. Roosevelt.",
        "Richard Nixon's original career plan was to become an FBI agent.",
        "Gerald Ford was a male model in his youth.",
        "Jimmy Carter is a speed-reading champion.",
        "Bill Clinton sent only 2 emails during his presidency.",
        "Barack Obama collects Spider-Man and Conan the Barbarian comics.",
        "The first photograph ever taken required an 8-hour exposure time.",
        "The first movie ever made was less than 3 seconds long.",
        "Charlie Chaplin once lost a Charlie Chaplin look-alike contest.",
        "Marilyn Monroe had a higher IQ than Albert Einstein.",
        "Bruce Lee was so fast that they had to slow down film of him.",
        "Elvis Presley was naturally blonde.",
        "Michael Jackson wanted to play Spider-Man in a movie.",
        "The Beatles used the word 'love' 613 times in their songs.",
        "Bob Marley's last words were 'Money can't buy life'.",
        "Jimi Hendrix couldn't read music.",
        "Mozart wrote Twinkle Twinkle Little Star.",
        "Beethoven was completely deaf when he composed his 9th Symphony.",
        "Bach had 20 children.",
        "Vivaldi was also a priest.",
        "Handel's Messiah was composed in just 24 days.",
        "Chopin's heart is buried separately from his body.",
        "The Mona Lisa has no eyebrows.",
        "Van Gogh only sold one painting during his lifetime.",
        "Picasso could draw before he could walk.",
        "Salvador Dali avoided paying restaurant bills by drawing on checks.",
        "Michelangelo wrote poetry on the Sistine Chapel ceiling.",
        "Shakespeare invented over 1,700 English words.",
        "Mark Twain was born and died when Halley's Comet was visible.",
        "Ernest Hemingway survived two plane crashes in two days.",
        "Edgar Allan Poe married his 13-year-old cousin.",
        "J.K. Rowling wrote Harry Potter on napkins.",
        "Dr. Seuss's editor bet him he couldn't write a book using only 50 words.",
        "Roald Dahl was a spy for the British during WWII.",
        "Agatha Christie once disappeared for 11 days.",
        "Lewis Carroll invented the word processor prototype.",
        "Charles Dickens had to be facing north to write.",
        "Oscar Wilde died broke in a Paris hotel room.",
    ],
    "food": [
        "Carrots were originally purple.",
        "The world's most expensive pizza costs $12,000.",
        "Ketchup was sold as medicine in the 1830s.",
        "Honey never spoils.",
        "The most expensive coffee is made from animal poop.",
        "The world's largest chocolate bar weighed 12,770 pounds.",
        "The average person eats 35,000 cookies in their lifetime.",
        "Peanuts aren't nuts, they're legumes.",
        "Almonds are seeds, not nuts.",
        "Cashews grow on the bottom of cashew apples.",
        "Pineapples take two years to grow.",
        "Strawberries aren't berries but bananas are.",
        "Raspberries are members of the rose family.",
        "Apples float because they're 25% air.",
        "Cranberries bounce when they're ripe.",
        "Watermelons are 92% water.",
        "Cucumbers are 96% water.",
        "Tomatoes have more genes than humans.",
        "Potatoes were the first vegetable grown in space.",
        "Corn is grown on every continent except Antarctica.",
        "Broccoli is a man-made food.",
        "Cauliflower comes in orange and purple varieties.",
        "Lettuce is a member of the sunflower family.",
        "Celery has negative calories (it takes more to digest than it provides).",
        "Avocados are toxic to birds.",
        "Chocolate was once used as currency.",
        "White chocolate isn't really chocolate.",
        "M&Ms were created for soldiers to eat without melting.",
        "The pretzel was invented by monks.",
        "Donuts were originally called oily cakes.",
        "Bagels were given to women in childbirth in the 1600s.",
        "The Caesar salad was invented in Mexico.",
        "Fortune cookies were invented in California.",
        "Hawaiian pizza was invented in Canada.",
        "French fries were invented in Belgium.",
        "Chicken tikka masala was invented in Scotland.",
        "German chocolate cake is not from Germany.",
        "Swiss cheese is called Emmental in Switzerland.",
        "Buffalo wings are from Buffalo, New York.",
        "The sandwich was named after the Earl of Sandwich.",
        "Beef Wellington is named after the Duke of Wellington.",
        "Eggs Benedict origin story involves a hangover cure.",
        "The BLT sandwich became popular during WWII.",
        "Club sandwiches got their name from club cars on trains.",
        "Submarine sandwiches were named after their shape.",
        "The hot dog got its name from dachshund sausages.",
        "Hamburgers come from Hamburg, Germany.",
        "Turkey the bird is not from Turkey the country.",
        "Brussels sprouts are named after Brussels, Belgium.",
        "Peking duck is from Beijing (formerly Peking).",
        "Champagne must come from Champagne, France.",
        "Parmesan cheese must come from Parma, Italy.",
        "Cognac must come from Cognac, France.",
        "Tequila must come from Tequila, Mexico.",
        "Port wine must come from Porto, Portugal.",
        "The world's most expensive spice is saffron.",
        "Vanilla is the second most expensive spice.",
        "Black pepper was once worth its weight in gold.",
        "Salt was once used as currency.",
        "Sugar was once more valuable than silver.",
        "Truffles can cost $3,000 per pound.",
        "Wagyu beef can cost $200 per pound.",
        "Kobe beef comes from Kobe, Japan.",
        "Iberico ham comes from Spain and can cost $100 per pound.",
        "Beluga caviar can cost $3,500 per pound.",
        "Matsutake mushrooms can cost $1,000 per pound.",
        "Bird's nest soup is made from actual bird nests.",
        "Fugu (pufferfish) must be prepared by licensed chefs.",
        "Casu marzu is cheese with live maggots.",
        "Hakarl is fermented shark from Iceland.",
        "Durian is banned in many hotels due to its smell.",
        "Surstromming is fermented herring so smelly it's banned on planes.",
        "Balut is a fertilized duck egg with a partially developed embryo.",
        "Century eggs are preserved for months, not a century.",
        "Escamoles are ant larvae eaten in Mexico.",
        "Witchetty grubs are eaten in Australia.",
        "Mopane worms are eaten in Africa.",
        "Crickets are eaten in many countries and high in protein.",
        "Scorpions are eaten in China and Thailand.",
        "Tarantulas are eaten in Cambodia.",
        "Bees and wasps are eaten in Japan.",
        "Ants are eaten in Colombia.",
        "Grasshoppers are eaten in Mexico.",
        "Termites are eaten in Africa.",
        "Stink bugs are eaten in southern Africa.",
        "Water bugs are eaten in Thailand.",
        "Bamboo worms are eaten in Southeast Asia.",
        "Silkworm pupae are eaten in Korea.",
        "Grubs are eaten by indigenous Australians.",
        "Mealworms are being considered as sustainable protein.",
        "Cockroaches are farmed for medicine in China.",
        "The hottest chili pepper is the Carolina Reaper.",
        "Bell peppers have zero Scoville heat units.",
        "Wasabi served in most restaurants is actually horseradish.",
        "Real maple syrup comes from maple tree sap.",
        "Honey is basically bee vomit.",
        "Yogurt is milk fermented by bacteria.",
        "Cheese is milk that's been curdled and aged.",
        "Vinegar is the result of fermentation by acetic acid bacteria.",
        "Kombucha is tea fermented with a SCOBY.",
        "Kimchi is fermented vegetables.",
        "Sauerkraut is fermented cabbage.",
        "Miso is fermented soybeans.",
    ],
    "random": [
        "A group of unicorns is called a 'blessing'.",
        "The average person spends 6 months waiting for red lights.",
        "A group of pandas is called an 'embarrassment'.",
        "The average person walks past 36 murderers in their lifetime.",
        "Alaska is the only state whose name is on one row on a keyboard.",
        "The dot over the 'i' is called a tittle.",
        "The plastic tips on shoelaces are called aglets.",
        "The metal part of a pencil is called a ferrule.",
        "The space between your eyebrows is called a glabella.",
        "The smell of rain is called petrichor.",
        "The day after tomorrow is called overmorrow.",
        "The fear of long words is called hippopotomonstrosesquippedaliophobia.",
        "The phobia of palindromes is called aibohphobia (which is a palindrome).",
        "A jiffy is an actual unit of time (1/100th of a second).",
        "A fortnight is 14 days.",
        "The symbol '&' is called an ampersand.",
        "The '#' symbol is called an octothorpe.",
        "The '!' is called a bang in computer programming.",
        "The '@' symbol is called an at sign.",
        "The '*' symbol is called an asterisk.",
        "The '~' symbol is called a tilde.",
        "The '^' symbol is called a caret.",
        "The'%' symbol is called a percent sign.",
        "The '$' symbol is called a dollar sign.",
        "The '€' symbol is called a euro sign.",
        "The '£' symbol is called a pound sign.",
        "The '¥' symbol is called a yen sign.",
        "The '₹' symbol is called a rupee sign.",
        "Q is the only letter that doesn't appear in any U.S. state name.",
        "Maine is the only state with one syllable.",
        "No number before 1,000 contains the letter 'A'.",
        "Four is the only number with the same number of letters as its value.",
        "The word 'swims' upside-down is still 'swims'.",
        "The word 'racecar' spelled backwards is 'racecar'.",
        "The word 'noon' spelled backwards is 'noon'.",
        "The word 'radar' is a palindrome.",
        "The word 'kayak' is a palindrome.",
        "The word 'level' is a palindrome.",
        "The word 'refer' is a palindrome.",
        "The word 'rotor' is a palindrome.",
        "The word 'civic' is a palindrome.",
        "The word 'deified' is a palindrome.",
        "The word 'redivider' is a palindrome.",
        "The word 'detartrated' is a palindrome.",
        "The longest English word without a vowel is 'rhythms'.",
        "The longest one-syllable word in English is 'screeched'.",
        "The shortest complete sentence in English is 'I am'.",
        "The most commonly used letter in English is 'E'.",
        "The least commonly used letter in English is 'Q'.",
        "Typewriter is the longest word you can type using only one row of a keyboard.",
        "Stewardesses is the longest word typed with only the left hand.",
        "Lollipop is the longest word typed with the right hand only.",
        "The word 'uncopyrightable' uses each letter exactly once.",
        "The word 'queue' is pronounced the same with just the first letter.",
        "The word 'facetious' contains all vowels in alphabetical order.",
        "The word 'abstemious' also contains all vowels in order.",
        "The word 'rhythms' is the longest without traditional vowels.",
        "The word 'strengths' is the longest one-syllable word.",
        "The word 'dreamt' is the only English word ending in 'mt'.",
        "The word 'set' has 464 definitions in the Oxford English Dictionary.",
        "The word 'run' has 645 definitions.",
        "The word 'go' has over 300 uses.",
        "The plural of 'moose' is 'moose', not 'meese'.",
        "The plural of 'goose' is 'geese', but the plural of 'mongoose' is 'mongooses'.",
        "The plural of 'ox' is 'oxen', but the plural of 'box' is 'boxes'.",
        "The plural of 'mouse' is 'mice', but the plural of 'house' is 'houses'.",
        "The English language has borrowed words from over 350 languages.",
        "Shakespeare added over 1,700 words to the English language.",
        "The word 'OK' is the most recognized word on Earth.",
        "The word 'goodbye' comes from 'God be with you'.",
        "The word 'nice' originally meant 'silly' or 'foolish'.",
        "The word 'awful' originally meant 'full of awe'.",
        "The word 'terrific' originally meant 'terrifying'.",
        "The word 'meat' used to mean any solid food.",
        "The word 'girl' used to mean any young person.",
        "The word 'Guy' was once an insult.",
        "The hashtag symbol is technically called an octothorpe.",
        "Thetilde (~) was originally written over letters to indicate abbreviation.",
        "The ampersand (&) was once the 27th letter of the alphabet.",
        "The exclamation mark was originally called the 'note of admiration'.",
        "The question mark originated from the Latin 'quaestio'.",
        "The @ symbol has different names in different languages.",
        "In Swedish, @ is called 'snabel-a' (elephant trunk A).",
        "In Hebrew, @ is called 'shtrudel' (like the pastry).",
        "In Italian, @ is called 'chiocciola' (snail).",
        "In Greek, @ is called 'papaki' (little duck).",
        "In Finnish, @ is called 'miukumauku' (meow-meow).",
        "In German, @ is called 'klammeraffe' (spider monkey).",
        "In Dutch, @ is called 'apenstaartje' (monkey tail).",
        "In Danish, @ is called 'snabel-a' (elephant's trunk A).",
        "In Russian, @ is called 'sobaka' (dog).",
        "In Spanish, @ is called 'arroba' (a unit of weight).",
        "The oldest known joke is from ancient Sumer.",
        "The oldest recorded joke is about bodily functions.",
        "Laughter is contagious due to mirror neurons.",
        "The average person laughs 15 times per day.",
        "Children laugh about 400 times per day.",
        "Laughing for 15 minutes can burn 40 calories.",
        "Babies start laughing at around 4 months old.",
        "Rats laugh when tickled (at ultrasonic frequencies).",
        "Primates laugh when tickled.",
        "Dogs have a play laugh.",
    ],
}


def get_random_fact(category: Optional[str] = None) -> str:
    """
    Get a random useless fact from the database.
    
    Args:
        category (str, optional): The category to get a fact from. 
                                If None, selects from all categories.
                                Valid categories: 'animals', 'science', 'history', 'food', 'random'
    
    Returns:
        str: A random useless fact
    
    Raises:
        ValueError: If the specified category doesn't exist
    """
    if category is None:
        # Select from all facts
        all_facts = []
        for facts_list in USELESS_FACTS.values():
            all_facts.extend(facts_list)
        return random.choice(all_facts)
    
    if category not in USELESS_FACTS:
        raise ValueError(f"Category '{category}' not found. Available categories: {list(USELESS_FACTS.keys())}")
    
    return random.choice(USELESS_FACTS[category])


def get_all_facts() -> Dict[str, List[str]]:
    """
    Get all useless facts organized by category.
    
    Returns:
        Dict[str, List[str]]: A dictionary with categories as keys and lists of facts as values
    """
    return USELESS_FACTS.copy()


def get_fact_by_category(category: str) -> List[str]:
    """
    Get all facts from a specific category.
    
    Args:
        category (str): The category to get facts from
    
    Returns:
        List[str]: A list of facts from the specified category
    
    Raises:
        ValueError: If the specified category doesn't exist
    """
    if category not in USELESS_FACTS:
        raise ValueError(f"Category '{category}' not found. Available categories: {list(USELESS_FACTS.keys())}")
    
    return USELESS_FACTS[category].copy()


def get_categories() -> List[str]:
    """
    Get all available categories.
    
    Returns:
        List[str]: A list of all available categories
    """
    return list(USELESS_FACTS.keys())


def get_fact_count() -> int:
    """
    Get the total number of facts in the database.
    
    Returns:
        int: The total number of facts
    """
    return sum(len(facts) for facts in USELESS_FACTS.values())
