# generated by puzl.cloud generator:
#   filename:  apis__networking.k8s.io__v1beta1_openapi.json
#   timestamp: 2025-10-20T15:38:47+00:00

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import ClassVar, Set

from k8s_models.const import *
from k8s_models.loader import *
from k8s_models.loader import LazyLoadModel
from k8s_models.resource import *


@dataclass(kw_only=True, frozen=True)
class RawExtension(LazyLoadModel):
    pass
