# This file was auto-generated by Fern from our API Definition.

import typing

from .templates_create_agents_from_template_response_agents_item_multi_agent_group_item_agent_ids_turns_counter_item import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsTurnsCounterItem,
)

TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsTurnsCounter = typing.Union[
    float,
    typing.Optional[str],
    typing.List[
        typing.Optional[TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsTurnsCounterItem]
    ],
    typing.Optional[typing.Any],
]
