# This file was auto-generated by Fern from our API Definition.

import typing

from .templates_create_agents_from_template_response_agents_item_sources_item_embedding_config_embedding_chunk_size_item import (
    TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemEmbeddingConfigEmbeddingChunkSizeItem,
)

TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemEmbeddingConfigEmbeddingChunkSize = typing.Union[
    float,
    typing.Optional[str],
    typing.List[
        typing.Optional[
            TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemEmbeddingConfigEmbeddingChunkSizeItem
        ]
    ],
    typing.Optional[typing.Any],
]
