import unittest
from unittest.mock import patch
from core.client import CtyunClient
from core.credential import Credential
from core.exception import CtyunRequestException
from apis.apis import Apis
from apis.ctecs_query_products_in_region_v41_api import (
    CtecsQueryProductsInRegionV41Api,
    CtecsQueryProductsInRegionV41Request,
    CtecsQueryProductsInRegionV41Response,
)


class TestCtecsQueryProductsInRegionV41Api(unittest.TestCase):
    def setUp(self):
        self.client = CtyunClient()
        self.credential = Credential('<YOUR_AK>', '<YOUR_SK>')
        self.endpoint = 'https://<YOUR_ENDPOINT>'
        self.apis = Apis(self.endpoint, self.client)

    def test_request_construction(self):
        """测试请求参数构造"""
        region_id = '81f7728662dd11ec810800155d307d5b'
        request = CtecsQueryProductsInRegionV41Request(regionID=region_id)
        self.assertEqual(request.regionID, region_id)
        self.assertEqual(request.to_dict(), {'regionID': region_id})

    def test_successful_request(self):
        """测试成功的API调用"""
        test_region_id = '81f7728662dd11ec810800155d307d5b'
        request = CtecsQueryProductsInRegionV41Request(regionID=test_region_id)

        # 准备模拟响应
        mock_response = {
            "message": "SUCCESS",
            "description": "成功",
            "errorCode": "",
            "returnObj": {
                "acl": {
                    "hasAcl": "yes"
                },
                "azList": [
                    {
                        "azDisplayName": "西北-内蒙演示1",
                        "azId": "1150345d-1388-45a5-b9bf-466271c96e7d_az1",
                        "azName": "az1",
                        "azProxyUrl": "cn-nm-region1-az1-sdk-proxy.az1.svc.cluster.net:8775",
                        "azVncDomain": "wss://sit1.consoletest.ctyun.cn/vm_vnc/neimeng8/az1",
                        "details": {
                            "GPU": "1",
                            "IR3LocaldiskPolicy": "prefer",
                            "IR3LocaldiskType": "STANDARD",
                            "IsCreateSnapshotReturnUUID": "1",
                            "IsCreateVolumeReturnUUID": "0",
                            "KIR32dLocaldiskPolicy": "prefer",
                            "KIR32dLocaldiskType": "KUNPENG-EXTEND1",
                            "KIR34dLocaldiskPolicy": "prefer",
                            "KIR34dLocaldiskType": "KUNPENG-EXTEND2",
                            "XSSDFlavorType": "s8,c8,m8,s8e,c8e,m8e,ks1se,kc1se,km1se,c8ne.hc3,hm3,hs3,hc3ne,hm3ne,hs3ne",
                            "azPmVncDomain": "wss://sit1.consoletest.ctyun.cn/serial/bm/cn-nm8-2A-public-ctcloud/",
                            "azVncDomain": "ws://10.150.66.248:30088",
                            "c3Hasctlimit": "1",
                            "has2DKIR3": "1",
                            "has4DKIR3": "1",
                            "hasC3": "1",
                            "hasC6M6": "1",
                            "hasC7": "0",
                            "hasC7NE": "1",
                            "hasC8": "1",
                            "hasC8E": "1",
                            "hasC8NE": "1",
                            "hasD3": "1",
                            "hasE": "1",
                            "hasEbsFromImage": "1",
                            "hasEbsKms": "1",
                            "hasEcsDriver": "1",
                            "hasFS1": "1",
                            "hasFeiteng": "1",
                            "hasG7": "1",
                            "hasGpuFlavorChange": "1",
                            "hasGpuQuantityPay": "1",
                            "hasGpuTurnCycle": "1",
                            "hasHC3": "1",
                            "hasHM3": "1",
                            "hasHPFSAZ": "1",
                            "hasHS1": "1",
                            "hasHS3": "1",
                            "hasHaiguang": "1",
                            "hasIP3": "1",
                            "hasIR3": "1",
                            "hasKM1SE": "1",
                            "hasKM2NE": "1",
                            "hasKS1": "1",
                            "hasKunpeng": "1",
                            "hasLITE1": "1",
                            "hasLITE1Band": "1",
                            "hasLiveResize": "1",
                            "hasM3": "1",
                            "hasM7": "1",
                            "hasM8": "1",
                            "hasM8E": "1",
                            "hasNVIDIAGPUInstalldriver": "1",
                            "hasP2V": "1",
                            "hasP8A": "1",
                            "hasP8AS": "1",
                            "hasP8AV": "1",
                            "hasPAK1": "1",
                            "hasPCH1": "1",
                            "hasPI2": "1",
                            "hasPI7": "1",
                            "hasPN8R": "1",
                            "hasPn8s": "1",
                            "hasS2M2": "1",
                            "hasS3": "1",
                            "hasS6": "1",
                            "hasS7": "1",
                            "hasS8": "1",
                            "hasS8R": "1",
                            "hasSoldOutCheck": "1",
                            "hasSupportP2vs": "1",
                            "hasXSSD": "1",
                            "hasXSSD0": "2",
                            "hasXSSD1": "1",
                            "hasXSSD2": "0",
                            "hasazISCSIHDD": "1",
                            "hasazISCSISSD": "1",
                            "m3Hasctlimit": "1",
                            "m6VolEnhance": "0",
                            "resourceSoldout": "1",
                            "s2VolEnhance": "1",
                            "s6AzName": "1",
                            "ssdIopsCal": "50000,1800,50",
                            "storageType": [
                                {
                                    "name": "普通IO",
                                    "type": "SATA"
                                },
                                {
                                    "name": "高IO",
                                    "type": "SAS"
                                },
                                {
                                    "name": "通用型SSD",
                                    "type": "SSD-genric"
                                },
                                {
                                    "name": "超高IO",
                                    "type": "SSD"
                                },
                                {
                                    "name": "XSSD-0",
                                    "type": "XSSD-0"
                                },
                                {
                                    "name": "XSSD-1",
                                    "type": "XSSD-1"
                                },
                                {
                                    "name": "XSSD-2",
                                    "type": "XSSD-2"
                                }
                            ],
                            "test-key10": "2",
                            "test-key14": "2"
                        },
                        "flag": "local"
                    },
                    {
                        "azDisplayName": "西北-内蒙演示2",
                        "azId": "1150345d-1388-45a5-b9bf-466271c96e7d_az2",
                        "azName": "az2",
                        "azProxyUrl": "cn-nm-region1-az2-sdk-proxy.az2.svc.cluster.net:8775",
                        "azVncDomain": "wss://sit1.consoletest.ctyun.cn/vm_vnc/neimeng8/az2",
                        "details": {
                            "IsCreateBackupReturnUUID": "1",
                            "IsCreateSnapshotReturnUUID": "1",
                            "IsCreateVolumeReturnUUID": "1",
                            "KIR32dLocaldiskPolicy": "prefer",
                            "KIR32dLocaldiskType": "KUNPENG-EXTEND1",
                            "KIR34dLocaldiskPolicy": "prefer",
                            "KIR34dLocaldiskType": "KUNPENG-EXTEND2",
                            "XSSDFlavorType": "c8,s8,m8,c8ne,m8ne,km2ne,ks2ne,kc2ne,hc3ne,hm3ne,hs3ne",
                            "az": "az2",
                            "azPmVncDomain": "ws://10.246.116.78/pm_vnc/neimeng/az2",
                            "azVncDomain": "ws://10.150.66.248:30089",
                            "c8neHasctlimit": "1",
                            "has2DKIR3": "1",
                            "has4DKIR3": "1",
                            "hasC3": "1",
                            "hasC6M6": "1",
                            "hasC7": "1",
                            "hasC7NE": "1",
                            "hasC8": "1",
                            "hasC8NE": "1",
                            "hasD3": "1",
                            "hasE": "1",
                            "hasEbsFromImage": "1",
                            "hasEcsDriver": "1",
                            "hasG7": "1",
                            "hasGpuFlavorChange": "1",
                            "hasGpuQuantityPay": "1",
                            "hasGpuTurnCycle": "1",
                            "hasHC3": "0",
                            "hasHC3NE": "1",
                            "hasHM3NE": "1",
                            "hasHPFSAZ": "0",
                            "hasHS3": "1",
                            "hasHS3NE": "1",
                            "hasKC1": "1",
                            "hasKC2": "1",
                            "hasKC2NE": "1",
                            "hasKM1SE": "1",
                            "hasKM2": "1",
                            "hasKM2NE": "1",
                            "hasKS1": "1",
                            "hasKS2": "1",
                            "hasKS2NE": "1",
                            "hasKunpeng": "1",
                            "hasLITE1": "1",
                            "hasLITE1Band": "1",
                            "hasM3": "1",
                            "hasM7": "1",
                            "hasM8": "1",
                            "hasM8NE": "1",
                            "hasNVIDIAGPUInstalldriver": "1",
                            "hasP8AS": "1",
                            "hasPAK1": "1",
                            "hasPCH1": "0",
                            "hasPI7": "1",
                            "hasPn8s": "1",
                            "hasS2M2": "1",
                            "hasS3": "1",
                            "hasS6": "1",
                            "hasS7": "1",
                            "hasS8": "1",
                            "hasSupportP2vs": "1",
                            "hasXSSD": "1",
                            "hasXSSD0": "1",
                            "hasXSSD1": "1",
                            "hasXSSD2": "1",
                            "hasazISCSISSD": "1",
                            "m3Hasctlimit": "1",
                            "m6VolEnhance": "0",
                            "region": "cn-huhehaote-t11",
                            "regionCode": "cn-neimeng-8",
                            "resourceSoldout": "1",
                            "s2VolEnhance": "0",
                            "storageType": [
                                {
                                    "name": "普通IO",
                                    "type": "SATA"
                                },
                                {
                                    "name": "高IO",
                                    "type": "SAS"
                                },
                                {
                                    "name": "通用型SSD",
                                    "type": "SSD-genric"
                                },
                                {
                                    "name": "超高IO",
                                    "type": "SSD"
                                },
                                {
                                    "name": "极速型SSD",
                                    "type": "FAST-SSD"
                                },
                                {
                                    "name": "XSSD-0",
                                    "type": "XSSD-0"
                                },
                                {
                                    "name": "XSSD-1",
                                    "type": "XSSD-1"
                                },
                                {
                                    "name": "XSSD-2",
                                    "type": "XSSD-2"
                                }
                            ],
                            "test-key10-1": "2"
                        },
                        "flag": "local"
                    },
                    {
                        "azDisplayName": "西北-内蒙演示3",
                        "azId": "1150345d-1388-45a5-b9bf-466271c96e7d_az3",
                        "azName": "az3",
                        "azProxyUrl": "cn-nm-region1-az3-sdk-proxy.az3.svc.cluster.net:8775",
                        "azVncDomain": "wss://sit1.consoletest.ctyun.cn/vm_vnc/neimeng8/az3",
                        "details": {
                            "GPU": "1",
                            "HasVolumePool": "2",
                            "XSSDFlavorType": "c8e,m8e,s8e",
                            "azVncDomain": "ws://10.150.66.248:30090",
                            "gpuAzName": "1",
                            "hasC3": "1",
                            "hasC6M6": "1",
                            "hasC7": "1",
                            "hasC7NE": "1",
                            "hasC8": "1",
                            "hasC8E": "1",
                            "hasC8NE": "1",
                            "hasE": "1",
                            "hasEbsFromImage": "1",
                            "hasEcsDriver": "1",
                            "hasFS1": "1",
                            "hasFeiteng": "1",
                            "hasG7": "1",
                            "hasGpuFlavorChange": "1",
                            "hasGpuTurnCycle": "1",
                            "hasHPFSAZ": "0",
                            "hasHaiguang": "1",
                            "hasKM1SE": "1",
                            "hasKM2NE": "1",
                            "hasKunpeng": "1",
                            "hasLITE1": "1",
                            "hasLITE1Band": "1",
                            "hasM3": "1",
                            "hasM7": "1",
                            "hasM8E": "1",
                            "hasM8NE": "1",
                            "hasNVIDIAGPUInstalldriver": "1",
                            "hasNewUpgradeRules": "1",
                            "hasP8A": "0",
                            "hasP8AS": "1",
                            "hasP8AV": "1",
                            "hasPAK1": "1",
                            "hasPI7": "0",
                            "hasS2M2": "1",
                            "hasS3": "1",
                            "hasS6": "1",
                            "hasS7": "1",
                            "hasS8E": "1",
                            "hasS8R": "1",
                            "hasSoldOutCheck": "1",
                            "hasSupportP2vs": "1",
                            "hasXSSD": "1",
                            "hasXSSD0": "1",
                            "hasXSSD1": "1",
                            "hasXSSD2": "0",
                            "hasazISCSISSD": "1",
                            "m3Hasctlimit": "1",
                            "m6VolEnhance": "0",
                            "pm": "2",
                            "resourceSoldout": "1",
                            "s2VolEnhance": "0",
                            "storageType": [
                                {
                                    "name": "普通IO",
                                    "type": "SATA"
                                },
                                {
                                    "name": "高IO",
                                    "type": "SAS"
                                },
                                {
                                    "name": "通用型SSD",
                                    "type": "SSD-genric"
                                },
                                {
                                    "name": "超高IO",
                                    "type": "SSD"
                                },
                                {
                                    "name": "极速型SSD",
                                    "type": "FAST-SSD"
                                },
                                {
                                    "name": "XSSD-0",
                                    "type": "XSSD-0"
                                },
                                {
                                    "name": "XSSD-1",
                                    "type": "XSSD-1"
                                },
                                {
                                    "name": "XSSD-2",
                                    "type": "XSSD-2"
                                }
                            ]
                        },
                        "flag": "local"
                    }
                ],
                "caas": {
                    "caasApiUrl": "http://10.150.66.248:31136",
                    "caasShareNetworkTenantId": "0a92ed48a2fb4ec18bb9b03c6a70f6ac",
                    "computedCaas": "yes",
                    "computedCaasUrl": "https://cci.ctyun.cn",
                    "computedCce": "yes",
                    "computedCceUrl": "https://cce.container.ctyun.cn:10443",
                    "computedCcr": "yes",
                    "computedCcrUrl": "https://ccr.container.ctyun.cn:10443/"
                },
                "cda": {
                    "hasCda": "no",
                    "hasCda2": "yes",
                    "hasCdaGrant": "yes",
                    "hasCdaMonitor": "yes",
                    "hasCdaPermission": "yes"
                },
                "ch": {
                    "hasCh": "yes",
                    "hasChBandwidthOrder": "yes",
                    "hasChMonitor": "no",
                    "hasChReconsitution": "yes"
                },
                "cnssl": {
                    "hasCnssl": "no",
                    "subnetOfferingIdWithLbNosnat": "public"
                },
                "dec": {
                    "hasDec": "yes"
                },
                "ebs": {
                    "HasVolumePool": "yes",
                    "hasAutoSnapPolicy": "yes",
                    "hasBks": "yes",
                    "hasEbsFromBks": "yes",
                    "hasEbsFromSnap": "yes",
                    "hasEbsKms": "yes",
                    "hasEbsSnapshot": "yes",
                    "hasEbsUpdateDisk": "yes",
                    "hasExportDiskImage": "yes",
                    "hasFCSAN": "yes",
                    "hasISCSI": "yes",
                    "hasISCSIHDD": "yes",
                    "hasISCSISSD": "yes",
                    "hasMakeDiskImage": "yes",
                    "shareEbs": "yes",
                    "storageType": [
                        {
                            "name": "普通IO",
                            "type": "SATA"
                        },
                        {
                            "name": "高IO",
                            "type": "SAS"
                        },
                        {
                            "name": "超高IO",
                            "type": "SSD"
                        },
                        {
                            "name": "极速型SSD",
                            "type": "FAST-SSD"
                        },
                        {
                            "name": "XSSD-0",
                            "type": "XSSD-0"
                        },
                        {
                            "name": "XSSD-1",
                            "type": "XSSD-1"
                        },
                        {
                            "name": "XSSD-2",
                            "type": "XSSD-2"
                        }
                    ],
                    "upgradeSysVolume": "yes"
                },
                "ecs": {
                    "flavorTypes": {
                        "2": [
                            "s6",
                            "test"
                        ],
                        "c": [
                            "c8e",
                            "c8",
                            "c7",
                            "c6",
                            "c3"
                        ],
                        "d": [
                            "d3"
                        ],
                        "e": [
                            "e"
                        ],
                        "fc": [
                            "fc1"
                        ],
                        "fm": [
                            "fm1"
                        ],
                        "fs": [
                            "fs1"
                        ],
                        "g": [
                            "g7"
                        ],
                        "hc": [
                            "hc1"
                        ],
                        "hm": [
                            "hm1",
                            "hm3"
                        ],
                        "hne": [
                            "hc3ne",
                            "hm3ne",
                            "hs3ne"
                        ],
                        "hs": [
                            "hs1",
                            "hs3"
                        ],
                        "i": [
                            "ip3",
                            "ir3"
                        ],
                        "kc": [
                            "kc1"
                        ],
                        "kir": [
                            "kir3"
                        ],
                        "km": [
                            "km1"
                        ],
                        "kne": [
                            "ks2ne",
                            "kc2ne",
                            "km2ne"
                        ],
                        "ks": [
                            "ks2",
                            "ks1"
                        ],
                        "m": [
                            "m8e",
                            "m8",
                            "m7",
                            "m6",
                            "m3",
                            "m2",
                            "m8ne"
                        ],
                        "ne": [
                            "c8ne",
                            "c7ne"
                        ],
                        "p": [
                            "pi7",
                            "p8a",
                            "pch1",
                            "pi2",
                            "p8av",
                            "pn8r",
                            "p2v",
                            "p8as",
                            "pn8s",
                            "p2vs",
                            "pak1"
                        ],
                        "s": [
                            "s8e",
                            "s8",
                            "s8r",
                            "s7",
                            "m7",
                            "s6",
                            "s3",
                            "s2",
                            "s9"
                        ]
                    },
                    "hasAddNic": "yes",
                    "hasAdvancedConfiguration": "yes",
                    "hasC6M6": "no",
                    "hasC7": "yes",
                    "hasC7NE": "yes",
                    "hasC8": "yes",
                    "hasC8NE": "yes",
                    "hasChangeNetwork": "yes",
                    "hasChangeV6Network": "yes",
                    "hasCloneVM": "yes",
                    "hasCloneVMNew": "yes",
                    "hasCreateVMByBackup": "yes",
                    "hasCsbs": "yes",
                    "hasFS1": "yes",
                    "hasG7": "yes",
                    "hasGroup": "yes",
                    "hasIP3": "yes",
                    "hasIR3": "no",
                    "hasM8": "yes",
                    "hasM8NE": "yes",
                    "hasP8A": "yes",
                    "hasP8AV": "yes",
                    "hasPCH1": "no",
                    "hasPI7": "yes",
                    "hasS2M2": "yes",
                    "hasS3": "yes",
                    "hasS6": "yes",
                    "hasS7": "yes",
                    "hasS8": "yes",
                    "hasS8R": "yes",
                    "hasSnapshot": "yes",
                    "hasVmGroupPowerAntiAffinity": "yes",
                    "hasVnc": "yes",
                    "hasVncByConsole": "yes"
                },
                "efs": {
                    "hasEfsKms": "yes",
                    "hasEfsPay": "yes",
                    "hasEfsPermission": "yes"
                },
                "eip": {
                    "hasEipMonitor": "yes",
                    "hasPayByTraffic": "yes",
                    "publicIpV6OsLimit": "yes"
                },
                "hpc": {
                    "computedHpc": "no",
                    "computedHpcUrl": "https://www.baidu.com"
                },
                "image": {
                    "hasExportDiskImage": "yes",
                    "hasMakeDiskImage": "yes",
                    "hasPrivateImageExport": "yes",
                    "safeImage": "yes",
                    "selectionImage": "yes",
                    "shareImage": "yes"
                },
                "kms": {
                    "hasKms": "yes",
                    "hasKmsServer": "yes"
                },
                "lb": {
                    "hasElb": "yes",
                    "hasElbCert": "yes",
                    "hasElbClientRealSourceIp": "yes",
                    "hasElbCrossVpc": "yes",
                    "hasElbCustomTimeout": "yes",
                    "hasElbGslb": "yes",
                    "hasElbHttp2": "yes",
                    "hasElbListenerHttpRedirect": "yes",
                    "hasElbMonitor": "yes",
                    "hasElbPackYearDiscount": "no",
                    "hasElbPgHigh2": "yes",
                    "hasElbPgSupper1": "yes",
                    "hasElbPgSupper2": "yes",
                    "hasElbProtocolPort": "yes",
                    "hasElbProtocolProto": "yes",
                    "hasElbSubnetIpv6": "yes",
                    "hasKeepSession": "yes",
                    "hasLBSupportSession": "yes",
                    "hasLBUrlTransmit": "yes",
                    "hasLBWhiteBlack": "yes",
                    "hasListenerOnHttp": "yes",
                    "hasListenerOnHttps": "yes",
                    "hasUdpLB": "yes",
                    "subnetOfferingIdWithInternalLbNosnat": "public",
                    "subnetOfferingIdWithLbNosnat": "public"
                },
                "monitor": {
                    "hasAuditLog": "no",
                    "hasEventMonitor": "yes",
                    "hasFGMonitor": "yes",
                    "hasLoackDiskMonitor": "yes",
                    "hasMonitor": "yes",
                    "hasMonitorOverview": "yes",
                    "hasPrometheusMonitor": "yes",
                    "hasSiteMonitor": "no"
                },
                "order": {
                    "billingByQuantity": "yes",
                    "hasAutoRenew": "yes",
                    "hasChBandwidthOrder": "yes",
                    "hasCycleTerminate": "yes",
                    "hasRecoveredOrder": "yes",
                    "supportDownConfig": "yes"
                },
                "oss": {
                    "hasMakeImageByOss": "yes",
                    "hasOSSWebSite": "yes",
                    "hasOss": "yes",
                    "hasOssCrr": "yes",
                    "hasOssFc": "yes",
                    "hasOssIa": "yes",
                    "hasOssIpv6": "yes",
                    "hasOssKms": "yes",
                    "hasOssQuota": "yes",
                    "hasOssResource": "yes",
                    "hasOssServerOpen": "yes",
                    "hasOssSts": "yes",
                    "hasOssVpc": "yes"
                },
                "other": {
                    "1": "yes",
                    "EBSAutoWithdrawOrderTime": "15",
                    "ENISupportPrivateIPv4DNSName": "yes",
                    "FLAVORCahngeApecSupportType": "m8ne=m8ne,c8ne,s8ne\u0026c8ne=m8ne,c8ne,s8ne\u0026hc1=hs3,hc3,hm3\u0026hm1=hs3,hc3,hm3\u0026hc3=hs3,hc3,hm3\u0026hm3=hs3,hc3,hm3\u0026e=e,s3,m3,c3,s6,m6,c6,s7,m7,c7,s8,m8,c8,s8r,c8e,m8e,s8e\u0026km2ne=km2ne,ks2ne,kc2ne\u0026pn8s=pn8s\u0026s8e=s3,m3,c3,s6,m6,c6,s7,m7,c7,s8,m8,c8,s8r,c8e,m8e,s8e\u0026c8e=s8r,c8e,m8e,s8e\u0026m8e=c8e,m8e,s8e\u0026hc3ne=hs3ne,hc3ne,hm3ne\u0026hm3ne=hs3ne,hc3ne,hm3ne",
                    "FLAVORNotSupportVolumeType": "hs1=SSD,FAST-SSD\u0026hc1=SSD,FAST-SSD\u0026hm1=SSD,FAST-SSD\u0026fs1=SSD\u0026fc1=SSD\u0026fm1=SSD\u0026c8ne=SATA,SAS,SSD-genric,SSD,FAST-SSD,XSSD-2\u0026m8ne=SATA,SAS,SSD-genric,SSD,FAST-SSD,XSSD-2\u0026kc2ne=FAST-SSD\u0026km2ne=FAST-SSD\u0026ks2ne=FAST-SSD\u0026e=FAST-SSD,XSSD-0,XSSD-1,XSSD-2\u0026hs3ne=FAST-SSD\u0026hc3ne=FAST-SSD\u0026hm3ne=FAST-SSD",
                    "FLAVORNotSupportXssdebsKms": "c8ne,m8ne,kc2ne,km2ne,ks2ne,hc3ne,hm3ne,hs3ne",
                    "FLAVORSupportThreadsPerCore": "c8=1,2",
                    "GPU": "yes",
                    "HasAzWorkOrder": "http://gw1.yacos.ctyun.com:12090",
                    "HasVpnLabel": "yes",
                    "IMSPmFileDoc": "https://www.baidu.com",
                    "IsVBSReplicationRepository": "no",
                    "LineTypeCN2": "yes",
                    "NEWSgz": "yes",
                    "NumberofImExExecutedConcurrently": "10",
                    "SecurityGroupNameDescriptionLength255": "yes",
                    "VBSReplicationRegionSource": "贵阳测试池8,贵阳12",
                    "VOLUMENotSupportFlavorType": "SSD=c8ne,m8ne\u0026FAST-SSD=c8ne,m8ne,kc2ne,km2ne,ks2ne,hs3ne,hc3ne,hm3ne\u0026SATA=c8ne,m8ne\u0026SAS=c8ne,m8ne\u0026SSD-genric=c8ne,m8ne",
                    "VPCSupportEnableInstanceDNS": "yes",
                    "VnetVpcMask29": "yes",
                    "VolBakHT": "no",
                    "VpcExtendedOptionZosvpcendpoint": "no",
                    "XSSDFlavorType": "s8,c8,m8,c8ne,m8ne,m8e,c8e,s8e,hs3,hc3ne,hm3ne,hs3ne,ks2ne,kc2ne,km2ne",
                    "addLogTime": "probation",
                    "agentType": "telegraf",
                    "aiSaasContentdetection": "yes",
                    "aiSaasContentdetectionUrl": "https://www.baidu.com",
                    "aiSaasFacedetection": "yes",
                    "aiSaasFacedetectionUrl": "https://ai.ctyun.cn/console/my-capability/list?categoryId=006001",
                    "aiSaasIntelligentcomputingservice": "yes",
                    "aiSaasIntelligentcomputingserviceUrl": "https://www.huiju.ctyun.cn",
                    "aiSaasNaturallanguageprocess": "yes",
                    "aiSaasPrintedcharacterrecognition": "yes",
                    "aiSaasSafeproduction": "yes",
                    "aiSaasXirang": "yes",
                    "aiSaasXirangUrl": "https://ctxirang.ctyun.cn",
                    "area": "east",
                    "az": "az2",
                    "azName": [
                        {
                            "availabilityZone": "public",
                            "name": "可用区public"
                        }
                    ],
                    "bksExcludeXssd": "no",
                    "bmRefactoringNetwork": "yes",
                    "cacheNum": "3",
                    "cdaConnectOrder": "yes",
                    "cdaConnectOrderNetwork": "yes",
                    "cdaDataflowIP": "yes",
                    "cdaDataflowIncloud": "yes",
                    "cdaDataflowPacket": "yes",
                    "cdaGatewayBGPAutoRoutes": "yes",
                    "cdaGatewayOrder": "no",
                    "cdaLineQos": "yes",
                    "cdaMulticast": "yes",
                    "cdnAppServer": "yes",
                    "cdnCloudVod": "yes",
                    "cdnEcx": "yes",
                    "cdnEcxSgt": "no",
                    "cdnFastLive": "yes",
                    "cdnFastLiveSgt": "no",
                    "cdnLiveSpeedup": "yes",
                    "cdnSafeFastPlatform": "yes",
                    "cdnSafeFastPlatformSgt": "no",
                    "cdnServer": "yes",
                    "cdnServerSgt": "no",
                    "cdnSmartEdgecloud": "no",
                    "cdnSmartEdgecloudUrl": "https://sit1.admin.ctyun.cn/aio/manage/systemadmin/sysplatformdetailnames/",
                    "cdnSpeedup": "yes",
                    "cdnSpeedupSgt": "no",
                    "cdnSpeedupSgtUrl": "https://cdn-console.ctyun.cn/h5/cdn/index.html#/",
                    "cdnSpeedupUrl": "https://cdn.ctyun.cn/h5/cdn/index.html#/",
                    "cdrExcludeXssd": "yes",
                    "checkPaasInfo": "probation",
                    "checkRealTimeSupport": "no",
                    "closeSazOss": "no",
                    "closeSazOssIa": "no",
                    "cloudType": "no",
                    "cloudVod": "yes",
                    "cloudVodSgt": "no",
                    "computedCloudDesktop": "yes",
                    "computedCloudDesktopUrl": "https://desk.ctyun.cn/cloudB/#/buy",
                    "computedCloudEcw": "yes",
                    "computedCloudPhone": "no",
                    "computedCloudPhoneUrl": "https://www.baidu.com",
                    "computedCloudWarriorAi": "yes",
                    "computedCloudWarriorAiUrl": "https://yunxiao-ui.ctyun.cn:10004/queue/list",
                    "computedCloudfunction": "yes",
                    "computedCloudfunctionUrl": "https://cf.ctyun.cn/dy/faas/?region=bb9fdb42056f11eda1610242ac110002#/overview",
                    "computedDcs": "no",
                    "computedDcsUrl": "https://www.ctyun.cn/products/domain",
                    "computedFlowResourcePackage": "yes",
                    "computedHpcNew": "yes",
                    "computedHpcNewUrl": "https://sit1.consoletest.ctyun.cn/hpc",
                    "computedMultiActivityDisasterRecovery": "yes",
                    "computedMultiActivityDisasterRecoveryUrl": "https://sit1.consoletest.ctyun.cn/mdr#/home/main",
                    "computedPaasCcse": "yes",
                    "computedPaasCcseUrl": "https://www.baidu.com",
                    "computedPaasCrs": "yes",
                    "computedPaasEci": "yes",
                    "csgNum": "no",
                    "ctyunId": "81f7728662dd11ec810800155d307d5b",
                    "currentVersionIsReconfigGuration": "yes",
                    "customerPlatformAttributes": [
                        {
                            "name": "exclusive_eip_pool",
                            "value": "[{\"deleted\":0,\"exclusive_name\":\"for-test-bgp-3\",\"eip_type\":\"bgp-3\",\"cidr\":\"100.124.38.192/26\",\"segment_id\":\"seg-g3glo55ziy\"}]"
                        },
                        {
                            "name": "free_eip_pool",
                            "value": "[]"
                        }
                    ],
                    "cutover": "yes",
                    "dataCloudsearch": "yes",
                    "dataCloudsearchUrl": "https://www.ctyun.cn/products/es",
                    "dataPaasMapreduceMr": "yes",
                    "dataSaasDatawings": "probation",
                    "datasassDatawings": "yes",
                    "datasassDatawingsUrl": "https://console.datawings.ctyun.cn/overview",
                    "dbNewAbc": "no",
                    "dbPaasAbcSgt": "yes",
                    "dbPaasAbcdSgt": "no",
                    "dbPaasDas": "yes",
                    "dbPaasDasUrl": "https://teledb.ctyun.cn/teledb-app/teledb-dms",
                    "dbPaasDbes": "yes",
                    "dbPaasDm": "yes",
                    "dbPaasDmUrl": "www.baidu.com",
                    "dbPaasDts": "yes",
                    "dbPaasSqlserver": "no",
                    "dedicatedCloudType": "storage",
                    "dnatSuportCustomIP": "yes",
                    "dnsServers": "100.95.0.1",
                    "ebs": "yes",
                    "ecm": "yes",
                    "ecmUseEipCard": "yes",
                    "ecsAutoWithdraw": "probation",
                    "ecsAutoWithdrawOrderTime": "90",
                    "editChangeCondition": "yes",
                    "eip": "yes",
                    "essBalancedDistribution": "yes",
                    "essCreAddInst": "yes",
                    "gatewayHostGroupLimit": "5",
                    "gatewayLoadBalanceLimit": "20",
                    "hansStopInquiry": "probation",
                    "has4NewNatMonitorMetric": "no",
                    "has95ChargeByBgp": "yes",
                    "hasASSupportARM": "yes",
                    "hasAccountAuthVPC": "yes",
                    "hasAccountPermission": "yes",
                    "hasAclControlLB": "yes",
                    "hasAclControlPublicLB": "yes",
                    "hasAclPrefixList": "yes",
                    "hasAclRulesImport": "yes",
                    "hasAdjustEbsLowerSize": "yes",
                    "hasAdvRetentionOps": "yes",
                    "hasAgent": "yes",
                    "hasAlarmBlacklist": "yes",
                    "hasAlb": "yes",
                    "hasAlbMonitor": "yes",
                    "hasAlbSuperII": "yes",
                    "hasAllowReservedCidrRoute": "198.19.128.0/20",
                    "hasAnyGatewayDhcp": "yes",
                    "hasAnyPortLb": "yes",
                    "hasArchitectureARM": "yes",
                    "hasAsRYAlarmIndex": "yes",
                    "hasAsrp": "yes",
                    "hasAutoAddCapacity": "yes",
                    "hasAvailableRegion": "yes",
                    "hasBackupUsedSize": "yes",
                    "hasBandWidthLimit": "yes",
                    "hasBandWidthTurnGB": "yes",
                    "hasBatchCreateElbPG": "yes",
                    "hasBatchCreateIP": "yes",
                    "hasBatchEditDisplayName": "probation",
                    "hasBatchReinstall": "yes",
                    "hasBgpByTraffic": "yes",
                    "hasBindwidthUtilizationRate": "yes",
                    "hasBksDataCheck": "yes",
                    "hasBksDataRendancy": "yes",
                    "hasBksEditRegion": "yes",
                    "hasBksRepoPayNeeded": "yes",
                    "hasBksSupportRunningBms": "yes",
                    "hasBksXSSD": "yes",
                    "hasBmsSupportLavaAndCeph": "yes",
                    "hasCBR": "yes",
                    "hasCDNMonitor": "yes",
                    "hasCHPE": "no",
                    "hasCMCCStaticNetwork": "yes",
                    "hasCMI": "yes",
                    "hasCN2BandWidth": "yes",
                    "hasCPN": "yes",
                    "hasCPNRapidChange": "yes",
                    "hasCPNRateSX": "yes",
                    "hasCPNSupportOTN": "yes",
                    "hasCPNThirdCloud": "yes",
                    "hasCUCCStaticNetwork": "yes",
                    "hasCbrBackup": "yes",
                    "hasCbrFullBackup": "yes",
                    "hasCcseMonitor": "yes",
                    "hasCdaBindCh": "yes",
                    "hasCdaClientRouterBfd": "yes",
                    "hasCdaGatewayRoute": "yes",
                    "hasCdaHealthCheck": "yes",
                    "hasCdaHealthQuery": "yes",
                    "hasCdaInternetPublicIPAddress": "yes",
                    "hasCdaIsAutomation": "yes",
                    "hasCdaPhysicalLineMonitor": "yes",
                    "hasCdaPortFreeCost": "no",
                    "hasCdaVirtualGatewayMonitor": "yes",
                    "hasCerResourcePkg": "yes",
                    "hasCertificateCa": "yes",
                    "hasCertificateEdit": "yes",
                    "hasCertificateNational": "yes",
                    "hasCertificatePlatform": "yes",
                    "hasChAttachBeginRentTime": "yes",
                    "hasChAttachPkg": "probation",
                    "hasChCreate": "no",
                    "hasChCtgChannelStateyun": "yes",
                    "hasChNetworkPerformance": "yes",
                    "hasChRedundantGroup": "yes",
                    "hasChSetMaxBandwidth": "no",
                    "hasChTrafficBeginRentTime": "yes",
                    "hasChTrafficMoPkg": "yes",
                    "hasChTrafficPkg": "no",
                    "hasChVpcSubnetRemoveVerify": "yes",
                    "hasChangeVmKeypair": "yes",
                    "hasClassicElbOffline": "yes",
                    "hasClickHouseMonitor": "yes",
                    "hasClonePm": "yes",
                    "hasCloudAssistant": "yes",
                    "hasCloudBackupMonitor": "yes",
                    "hasCloudLinkerTelnet": "yes",
                    "hasCloudSearch": "yes",
                    "hasCloudServiceMonitor": "yes",
                    "hasCloudhighConnect": "yes",
                    "hasCloudhighThrough": "yes",
                    "hasCmccByGoaspay": "yes",
                    "hasCmccByTraffic": "yes",
                    "hasCmccMonth95Charge": "no",
                    "hasCommercial": "yes",
                    "hasCommonItHeader": "yes",
                    "hasComputeAuditLog": "yes",
                    "hasComputeItHeader": "yes",
                    "hasComputedSupportHistoryData": "yes",
                    "hasConnectionDrain": "yes",
                    "hasContinuousAddress163": "yes",
                    "hasContinuousAddressBgp": "yes",
                    "hasContinuousAddressMobile": "yes",
                    "hasContinuousAddressUnicom": "yes",
                    "hasContinuousBandwidthBillConfirm": "probation",
                    "hasContinuousIPv4ExclusiveAddressBgp": "yes",
                    "hasContinuousIPv4ExclusiveAddressCm": "probation",
                    "hasContinuousIPv4ExclusiveAddressCt": "probation",
                    "hasContinuousIPv4ExclusiveAddressCu": "probation",
                    "hasContinuousIPv4lable": "yes",
                    "hasContinuousIPv6Address163": "yes",
                    "hasContinuousIPv6AddressBgp": "yes",
                    "hasContinuousIPv6AddressMobile": "yes",
                    "hasContinuousIPv6AddressUnicom": "yes",
                    "hasContinuousIPv6ExclusiveAddressBgp": "yes",
                    "hasContinuousIPv6ExclusiveAddressCm": "probation",
                    "hasContinuousIPv6ExclusiveAddressCt": "probation",
                    "hasContinuousIPv6ExclusiveAddressCu": "probation",
                    "hasContinuousIPv6lable": "yes",
                    "hasCreatEipWithElb": "yes",
                    "hasCreatV6": "yes",
                    "hasCreateApplicationEcs": "yes",
                    "hasCreateApplicationEcsVpn": "yes",
                    "hasCreateChPayAmount": "probation",
                    "hasCreateCloudComputer": "yes",
                    "hasCreateDefultRouter": "yes",
                    "hasCreateImsByActive": "yes",
                    "hasCreateImsByBackup": "yes",
                    "hasCreateLiteEcmByApplyIms": "yes",
                    "hasCreateSdwanExample": "yes",
                    "hasCreateVpnExample": "yes",
                    "hasCrossAreaPacketLossRate": "yes",
                    "hasCsbsAdvRetenOps": "yes",
                    "hasCsbsBackupCancel": "yes",
                    "hasCsbsFullBackup": "yes",
                    "hasCsbsRepoPayNeed": "yes",
                    "hasCsbsTask": "yes",
                    "hasCsbsXssd": "yes",
                    "hasCsg": "yes",
                    "hasCsgUpgrade": "yes",
                    "hasCtcssMonitor": "yes",
                    "hasCtydbMonitor": "yes",
                    "hasCuccByGoaspay": "yes",
                    "hasCuccByTraffic": "yes",
                    "hasCuccMonth95Charge": "no",
                    "hasCustomEvent": "yes",
                    "hasCustomMonitor": "yes",
                    "hasCustomProcess": "yes",
                    "hasDNSAccountPermission": "yes",
                    "hasDNSBatchDelete": "yes",
                    "hasDNSImportExport": "yes",
                    "hasDataCheck": "yes",
                    "hasDataDiskOsType": "yes",
                    "hasDataSubscribe": "yes",
                    "hasDateTimePickLog": "yes",
                    "hasDdcMonitor": "no",
                    "hasDecDss": "yes",
                    "hasDetectionFrequency": "yes",
                    "hasDhcpOptionSet": "yes",
                    "hasDhcpOptionSupportDHCPLeaseTime": "yes",
                    "hasDisHighIO": "yes",
                    "hasDisasterRecovery": "yes",
                    "hasDiskAdvRetenOps": "yes",
                    "hasDiskBackupMonitor": "yes",
                    "hasDiskFullBackup": "yes",
                    "hasDiskMonitorWithFourMertic": "yes",
                    "hasDiskUseFullBackup": "yes",
                    "hasDnsLog": "yes",
                    "hasDnsRecordOpenWeightSwitch": "yes",
                    "hasDnsSupportEmpty": "yes",
                    "hasDocDatabaseMonitor": "yes",
                    "hasDrDsMonitor": "yes",
                    "hasDropMetrics": "yes",
                    "hasDwsDorisMonitor": "yes",
                    "hasDynamicRoute": "no",
                    "hasEIPBindRestrictByVCPU": "yes",
                    "hasELBClientIPPreservation": "no",
                    "hasELBSessionTicket": "yes",
                    "hasELBSoldOut": "no",
                    "hasENISourceIPCheck": "yes",
                    "hasENISourceIPCheck333": "yes",
                    "hasENISourcelPCheck": "yes",
                    "hasEbsCreateWithBks": "yes",
                    "hasEbsDefaultBks": "yes",
                    "hasEbsDescription": "yes",
                    "hasEbsDetachWithVm": "probation",
                    "hasEbsFeedback": "yes",
                    "hasEbsFromImage": "yes",
                    "hasEbsGroup": "yes",
                    "hasEbsIsAttachEcm": "yes",
                    "hasEbsNewSoldOut": "yes",
                    "hasEbsRecycle": "yes",
                    "hasEcmAssignPort": "probation",
                    "hasEcmBaseSG": "yes",
                    "hasEcmBatchReinstallByRam": "yes",
                    "hasEcmBatchTurnCycle": "yes",
                    "hasEcmBatchUbsubscribe": "yes",
                    "hasEcmBindDelegation": "yes",
                    "hasEcmChannel1BillMode": "yes",
                    "hasEcmCycleCreateIPv6": "yes",
                    "hasEcmDetailMonitorMultiTables": "yes",
                    "hasEcmDisDelReason": "no",
                    "hasEcmIpNumCheck": "yes",
                    "hasEcmReinstallByKeypair": "yes",
                    "hasEcmReleaseRelatedResource": "yes",
                    "hasEcmReturnInstanceId": "probation",
                    "hasEcmSnapCreIms": "yes",
                    "hasEcmSnapshotDataCheck": "yes",
                    "hasEcmTemplate": "yes",
                    "hasEcsDetailDisplayBackup": "yes",
                    "hasEcsDriver": "yes",
                    "hasEcsFeedback": "yes",
                    "hasEcsNameToDns": "yes",
                    "hasEcsSupportEipFlow": "yes",
                    "hasEfsCifs": "yes",
                    "hasEfsCrossDomainCopy": "yes",
                    "hasEfsIpv6": "yes",
                    "hasEfsLabel": "no",
                    "hasEfsMonitor": "yes",
                    "hasEfsMount": "yes",
                    "hasEfsOverviewMon": "no",
                    "hasEfsPhysicalMount": "probation",
                    "hasEfsSnapshot": "no",
                    "hasEfsTurnCycle": "yes",
                    "hasEfsVolumeLine": "yes",
                    "hasEfsVpce": "probation",
                    "hasEfsadRegion": "yes",
                    "hasEipAdjust": "yes",
                    "hasEipCard": "yes",
                    "hasEipCreateLabel": "yes",
                    "hasEipExclusivePool": "yes",
                    "hasEipFeedback": "yes",
                    "hasEipGlobalQuota": "yes",
                    "hasEipPktsMetrics": "yes",
                    "hasElasticContainerMonitor": "yes",
                    "hasElbAbnormalTarget": "yes",
                    "hasElbAddDomainCert": "yes",
                    "hasElbAutoRenew": "yes",
                    "hasElbBAElb": "yes",
                    "hasElbBackHostPageSizeOver20": "yes",
                    "hasElbBackendHost": "no",
                    "hasElbContainerAndENI": "yes",
                    "hasElbCreateLabel": "yes",
                    "hasElbDeleteProtect": "yes",
                    "hasElbDuplicateName": "yes",
                    "hasElbEciContainer": "yes",
                    "hasElbEditPortsAndWeights": "yes",
                    "hasElbEnableWAF": "yes",
                    "hasElbGzip": "yes",
                    "hasElbListenerMaxTimeout600": "yes",
                    "hasElbListernerNameAllowedRepeat": "yes",
                    "hasElbMachine": "yes",
                    "hasElbMemberEnisContainer": "yes",
                    "hasElbMemberNetworkInterface": "yes",
                    "hasElbMonitor20250318": "yes",
                    "hasElbMonitor20250721": "yes",
                    "hasElbNameOptimization": "yes",
                    "hasElbNat64": "yes",
                    "hasElbPG": "yes",
                    "hasElbPGElbenhancedii": "yes",
                    "hasElbPGElbstandardi": "no",
                    "hasElbPGElbstandardii": "yes",
                    "hasElbPayQuantity": "yes",
                    "hasElbPgEnhanced1": "no",
                    "hasElbPgEnhanced2": "yes",
                    "hasElbPgHigh1": "yes",
                    "hasElbPgStandard2": "yes",
                    "hasElbPgSupper2Application": "yes",
                    "hasElbPgSupper3": "yes",
                    "hasElbPolicyWildcard": "yes",
                    "hasElbRemoteBackend": "yes",
                    "hasElbSink": "no",
                    "hasElbSpeedLimit": "yes",
                    "hasElbStatusCode": "yes",
                    "hasElbSupportVpcRoutes": "yes",
                    "hasElbTSLPolicy": "yes",
                    "hasElbTwoWay": "yes",
                    "hasElbUdpCusConTime": "yes",
                    "hasElbWeightZero": "yes",
                    "hasEnableDiTing": "yes",
                    "hasEssConfigMultiFlavor": "yes",
                    "hasEssCreateLabel": "yes",
                    "hasEssExpectedNumInst": "no",
                    "hasEssForceDel": "yes",
                    "hasEssGroupLabel": "yes",
                    "hasEsurfConfigProduct": "yes",
                    "hasEvsFloatDoc": "yes",
                    "hasExtIP": "no",
                    "hasFiveTupleSecurityGroupRule": "yes",
                    "hasFlavorForecastPrice": "yes",
                    "hasFlexShareAndLocalCopy": "yes",
                    "hasFloatDoc": "yes",
                    "hasForceRestart": "yes",
                    "hasForceStop": "yes",
                    "hasFreeAndExpired": "yes",
                    "hasGPUCloudMonitoring": "yes",
                    "hasGWLBMonitor": "yes",
                    "hasGatewayLoadBalance": "yes",
                    "hasGpuEcmShelve": "yes",
                    "hasGpuFlavorChange": "yes",
                    "hasGpuQos": "yes",
                    "hasGpuQuantityPay": "yes",
                    "hasGpuTurnCycle": "yes",
                    "hasGre": "yes",
                    "hasGwlbBypassType": "yes",
                    "hasHKQualityByTraffic": "yes",
                    "hasHKQualityNetwork": "yes",
                    "hasHPFS": "probation",
                    "hasHPFSAi": "yes",
                    "hasHPFSBaseline": "yes",
                    "hasHPFSCIFS": "no",
                    "hasHPFSCluster": "yes",
                    "hasHPFSDataflow": "yes",
                    "hasHPFSFeedback": "yes",
                    "hasHPFSFileset": "yes",
                    "hasHPFSFilesetMonitor": "yes",
                    "hasHPFSInodeMonitor": "yes",
                    "hasHPFSMonitor": "yes",
                    "hasHPFSNFS": "yes",
                    "hasHPFSPOSIX": "yes",
                    "hasHPFSPerf": "yes",
                    "hasHPFSProtocolService": "yes",
                    "hasHPFSProtocolServiceMonitor": "yes",
                    "hasHPFSSoldOut": "yes",
                    "hasHPTSBaseline": "yes",
                    "hasHaiguang": "yes",
                    "hasHcAnyportPg": "yes",
                    "hasHealthCheckDomain": "yes",
                    "hasHealthCheckManage": "yes",
                    "hasHealthCheckMonitor": "yes",
                    "hasHealthWarmupTime": "yes",
                    "hasHostBackupMonitor": "yes",
                    "hasHostRecordTab": "yes",
                    "hasHybGatewayMonitor": "yes",
                    "hasHybridBackupLicense": "yes",
                    "hasHybridBackupStorage": "yes",
                    "hasHybridPrometheusMonitor": "yes",
                    "hasIAAS": "yes",
                    "hasIEProgressInterrupt": "no",
                    "hasIMSExportFormat": "yes",
                    "hasIMSFileSupportLabel": "yes",
                    "hasIPBasicBillByBandWidthEIP": "yes",
                    "hasIPv6Acl": "yes",
                    "hasISO": "yes",
                    "hasImagesManagedbyGlance": "probation",
                    "hasImpExpImgGlance": "yes",
                    "hasImsCopytoAnotherRegion": "yes",
                    "hasImsDeprecated": "yes",
                    "hasImsIntegrityCheck": "yes",
                    "hasInstanceReleaseEbs": "yes",
                    "hasIntelligentPatrol": "yes",
                    "hasIntelligentPredict": "yes",
                    "hasInternetChannel": "yes",
                    "hasIntranetDnsMonitor": "yes",
                    "hasIopsAndThruput": "yes",
                    "hasIpv4netgate": "yes",
                    "hasIpv6": "yes",
                    "hasIpv6163": "yes",
                    "hasIpv6AutoRenew": "yes",
                    "hasIpv6BandWidth": "yes",
                    "hasIpv6BandWidthPayNeed": "yes",
                    "hasIpv6CidrSupportIspAllocate": "yes",
                    "hasIpv6ExclusivePool": "yes",
                    "hasIpv6GWSupportCreateName": "yes",
                    "hasIpv6GWSupportModifyName": "no",
                    "hasIpv6MultiLineBGP": "yes",
                    "hasIpv6NetgateRoute": "yes",
                    "hasIpv6SupportSelfBGP3": "yes",
                    "hasIpv6SupportSelfCM": "yes",
                    "hasIpv6SupportSelfCU": "yes",
                    "hasIpv6SupportSelfProCrossLine": "yes",
                    "hasIpv6cn2": "yes",
                    "hasIpv6no163": "no",
                    "hasIstack": "yes",
                    "hasIstackUrl": "/compute/index/#/istack/istackList",
                    "hasKafkaMonitor": "yes",
                    "hasKeyOpCheckSensitive": "no",
                    "hasKeyOperationValid": "no",
                    "hasKmsMonitor": "yes",
                    "hasKunpeng": "yes",
                    "hasKylinOS": "yes",
                    "hasL2GWFee": "yes",
                    "hasL2GWGSYPay": "yes",
                    "hasL2GWPrepay": "yes",
                    "hasL2gw": "yes",
                    "hasL2gwBasicSpecification": "yes",
                    "hasL2gwEnhancedSpecification": "yes",
                    "hasL2gwStandardSpecification": "yes",
                    "hasLITE1": "yes",
                    "hasLITE1Band": "yes",
                    "hasLabel": "yes",
                    "hasLabelFilter": "yes",
                    "hasLabelReverseFilter": "yes",
                    "hasLegacyStopFree": "no",
                    "hasLinuxNonRoot": "yes",
                    "hasLinuxRoot": "yes",
                    "hasListenerQuicPg": "yes",
                    "hasLiteEcmEbsUnsubscribe": "yes",
                    "hasLiteEcmIPv6": "yes",
                    "hasLiveResize": "yes",
                    "hasLoackDiskPhon": "yes",
                    "hasLoackDiskPhone": "no",
                    "hasLocalBackup": "no",
                    "hasLogServerElb": "yes",
                    "hasLsOpenCloseRedirect": "no",
                    "hasMarketImages": "yes",
                    "hasMemberENI": "yes",
                    "hasMemberENICrossVPCAttach": "yes",
                    "hasMemberENIInheritTrunkENIMAC": "yes",
                    "hasMemberEniBindBm": "yes",
                    "hasMemberEniBindEip": "yes",
                    "hasMemberEniBindNat": "yes",
                    "hasMemberEniShowOwner": "yes",
                    "hasMetalFileIms": "yes",
                    "hasMetalIms": "yes",
                    "hasMetalSubnet": "yes",
                    "hasMetalSubnetSupportSunbnetRoute": "no",
                    "hasMetalSubnetSupportVIP": "yes",
                    "hasModifyDefaultSecurityGroupName": "probation",
                    "hasModifyDnsServerDefaultValue": "100.95.0.1",
                    "hasMonitorErrorTip": "yes",
                    "hasMonitorItHeaderLayoutV2": "yes",
                    "hasMonitorNoticeTemplate": "yes",
                    "hasMonth95Charge": "yes",
                    "hasMoreNextJump": "yes",
                    "hasMseMonitor": "yes",
                    "hasMulEcmCycleCreateIPv6": "yes",
                    "hasMultiLineBGP": "yes",
                    "hasMultiLineIpv6Addr": "yes",
                    "hasMultiVpcIpv6Cidr": "yes",
                    "hasMulticast": "yes",
                    "hasMulticastDuplicateName": "no",
                    "hasMulticastFee": "yes",
                    "hasMulticastMonitor": "yes",
                    "hasMysqlMonitor": "yes",
                    "hasNASFileSystem": "yes",
                    "hasNVIDIAGPUInstalldriver": "yes",
                    "hasNVMeOfPrivateImage": "yes",
                    "hasNatMonitor": "yes",
                    "hasNatMonitorsessConnectLimitDropRate": "yes",
                    "hasNatPayNeed": "yes",
                    "hasNatSessionLog": "yes",
                    "hasNatSetting": "yes",
                    "hasNatStandardSpec1000w": "yes",
                    "hasNatStandardSpec2000w": "yes",
                    "hasNatStandardSpec200w": "yes",
                    "hasNatStandardSpec300w": "yes",
                    "hasNatStandardSpec500w": "yes",
                    "hasNatSubnet": "yes",
                    "hasNatWithFlavors": "yes",
                    "hasNetworkAnalysis": "yes",
                    "hasNetworkItHeader": "no",
                    "hasNetworkPerformance": "yes",
                    "hasNetworkQuality": "yes",
                    "hasNewChMonitor": "yes",
                    "hasNewNamingConvention": "yes",
                    "hasNewUpgradeRules": "yes",
                    "hasNextJumpLocation": "no",
                    "hasNicBindRestrictByVCPU": "yes",
                    "hasNicMultiIpv6Cidr": "yes",
                    "hasNicSupportCrossVpcBind": "probation",
                    "hasNoElbBAElb": "yes",
                    "hasNoOssImage": "yes",
                    "hasNotConsistentEcmSnap": "yes",
                    "hasNotificationPolicy": "yes",
                    "hasOSSAccessTimeTracing": "yes",
                    "hasOSSAcl": "yes",
                    "hasOSSBucketACLWrite": "yes",
                    "hasOSSBucketDomain": "yes",
                    "hasOSSBucketInventory": "yes",
                    "hasOSSBucketPolicy": "yes",
                    "hasOSSBucketPolicyNew": "yes",
                    "hasOSSBucketQuota": "yes",
                    "hasOSSCDN": "yes",
                    "hasOSSDataProcess": "yes",
                    "hasOSSGetS3URI": "yes",
                    "hasOSSIam": "yes",
                    "hasOSSImageProcess": "yes",
                    "hasOSSJSONPolicy": "no",
                    "hasOSSMirror": "yes",
                    "hasOSSObjectLock": "yes",
                    "hasOSSSymlink": "yes",
                    "hasOSSTakebackPackage": "yes",
                    "hasOSSUpdate": "yes",
                    "hasOSSUrlList": "yes",
                    "hasObsFeedback": "yes",
                    "hasOceanFS": "yes",
                    "hasOceanFSCluster": "probation",
                    "hasOceanFSCrossAzCopy": "yes",
                    "hasOceanFSDualStack": "no",
                    "hasOceanFSFeedback": "yes",
                    "hasOceanFSInodeMonitor": "yes",
                    "hasOceanFSPerf": "probation",
                    "hasOceanFSSnapshot": "yes",
                    "hasOceanFSVPCE": "yes",
                    "hasOceanFSVolumeLine": "yes",
                    "hasOceanFSadRegion": "yes",
                    "hasOceanFsActualUsage": "probation",
                    "hasOceanFsCrossDomainCopy": "yes",
                    "hasOceanfsMonitor": "yes",
                    "hasOfflinePassworReset": "yes",
                    "hasOmsCreate": "yes",
                    "hasOssDirectAccess": "yes",
                    "hasOssInventory": "yes",
                    "hasOssLabel": "yes",
                    "hasOssMaz": "yes",
                    "hasOssMazIa": "yes",
                    "hasOssMonitor": "yes",
                    "hasOssYLCTIAM": "yes",
                    "hasP2PMonitor": "yes",
                    "hasPMBindEip": "yes",
                    "hasPaasMonitor": "yes",
                    "hasPartFromRemotePM": "probation",
                    "hasPassMonitor": "yes",
                    "hasPathAnalyzer": "yes",
                    "hasPathEncryption": "yes",
                    "hasPay": "yes",
                    "hasPeerToPeerConnect": "yes",
                    "hasPgsqlMonitor": "yes",
                    "hasPheAIassistant": "yes",
                    "hasPhyBackup": "no",
                    "hasPmAdaptation???已删": "yes",
                    "hasPmAddInquiryParams": "yes",
                    "hasPmAgent": "yes",
                    "hasPmDesc": "yes",
                    "hasPmEditProps": "yes",
                    "hasPmForceRestart": "yes",
                    "hasPmForceStop": "yes",
                    "hasPmIops": "yes",
                    "hasPmLocalizationCpu": "yes",
                    "hasPmPayOnDemand": "yes",
                    "hasPmReleaseRelatedResource": "yes",
                    "hasPmSupportFastSSD": "yes",
                    "hasPmUserData": "yes",
                    "hasPodMonitor": "no",
                    "hasPortExempt": "yes",
                    "hasPrefix": "yes",
                    "hasPrefixClone": "yes",
                    "hasPrefixSupportCTEC": "yes",
                    "hasPrivateImsDeleteInCreating": "yes",
                    "hasPrivateImsKms": "yes",
                    "hasPrivateNat": "yes",
                    "hasPrivateNatMonitor": "no",
                    "hasProtocolPortList": "yes",
                    "hasPublicDnatPortSgementAnyport": "yes",
                    "hasPublicIpContinuousAddress": "yes",
                    "hasPublicNatDefaultRoute": "yes",
                    "hasPublicNatSessionExpireTime": "yes",
                    "hasQosLimit": "yes",
                    "hasQualityNetwork": "yes",
                    "hasQuantityRetention": "yes",
                    "hasQueryPortOptimized": "no",
                    "hasRabbitMqMonitor": "yes",
                    "hasRamConfig": "yes",
                    "hasRedisMonitor": "yes",
                    "hasRemote": "no",
                    "hasRemoteProductJump": "yes",
                    "hasResPkg": "yes",
                    "hasRescourceGroup": "yes",
                    "hasResourceUnbindProject": "yes",
                    "hasRmoteConnection": "yes",
                    "hasRootEbsKms": "yes",
                    "hasRoute10064": "probation",
                    "hasRouteEIPFirst": "yes",
                    "hasRouteEIPFirstFw": "probation",
                    "hasRouteMoreNextHop": "yes",
                    "hasRouteNameId": "yes",
                    "hasRouteRuleSurV4": "yes",
                    "hasRoutingTable": "yes",
                    "hasRtbRelatePrefixlist": "yes",
                    "hasSFSFeedback": "yes",
                    "hasSFSFreeze": "no",
                    "hasSLGatewayMonitor": "yes",
                    "hasSMSAlarm": "yes",
                    "hasSSLVPN": "yes",
                    "hasSbwFeedback": "yes",
                    "hasSdwanAccount": "yes",
                    "hasSdwanCreateEdgeNat": "yes",
                    "hasSdwanFlowLog": "yes",
                    "hasSdwanMonitor": "yes",
                    "hasSdwanQlinksSafeFw": "yes",
                    "hasSdwanSafetyTube": "yes",
                    "hasSecAddRules": "no",
                    "hasSecCopy": "no",
                    "hasSecInstancePm": "yes",
                    "hasSecRuleCopy": "no",
                    "hasSecRulesSupportMulDelete": "no",
                    "hasSecondLevelMonitor": "yes",
                    "hasSecurityRulesImport": "no",
                    "hasServiceIpInVPC": "yes",
                    "hasSharePrefixList": "yes",
                    "hasShareSubnet": "no",
                    "hasSharedEVSSupportBKS": "yes",
                    "hasSharedEVSSupportKMS": "yes",
                    "hasShelveStop": "yes",
                    "hasShoppingCart": "yes",
                    "hasShowConnectExampleV4": "yes",
                    "hasShowRec": "yes",
                    "hasSimplePolicy": "yes",
                    "hasSnapDataCheck": "yes",
                    "hasSnapReleaseEbs": "yes",
                    "hasSnapshotPolicy": "yes",
                    "hasSoldOutCheck": "yes",
                    "hasSpecialLineStorage": "yes",
                    "hasSpecialLineStorageEfs": "no",
                    "hasSpecialMulticastGroupsWhite": "yes",
                    "hasSplitCompute": "yes",
                    "hasSplitMonitor": "yes",
                    "hasSplitNetwork": "yes",
                    "hasSplitSdwan": "yes",
                    "hasSplitStorage": "yes",
                    "hasSqlServerMonitor": "yes",
                    "hasSslRestAndCustomPwd": "yes",
                    "hasStaOpti": "yes",
                    "hasStopWarning": "probation",
                    "hasStorageDashboard": "yes",
                    "hasSubNicBfd": "yes",
                    "hasSubnetChange": "yes",
                    "hasSubnetCidrMask8": "yes",
                    "hasSubnetDNS": "yes",
                    "hasSubnetOpenapi": "no",
                    "hasSubsCreateVpc": "probation",
                    "hasSupCancel": "yes",
                    "hasSupportARM": "yes",
                    "hasSupportBandwidthAs": "probation",
                    "hasSupportEditCert": "yes",
                    "hasSupportOrgVpn": "no",
                    "hasSysDiskMountOrUnmount": "yes",
                    "hasSysDiskXSSD": "yes",
                    "hasTCPSSLPg": "yes",
                    "hasTargetGroupAttachElb": "yes",
                    "hasTargetGroupReuseMoreElb": "yes",
                    "hasTaskList": "yes",
                    "hasTaskProgress": "yes",
                    "hasTeleAgent": "yes",
                    "hasTeleCloudShell": "yes",
                    "hasThreadsPerCore": "yes",
                    "hasTopology": "yes",
                    "hasTracePolicy": "yes",
                    "hasTrafficMirror": "yes",
                    "hasTrafficMirrorFilterIpType": "yes",
                    "hasTrafficMirrorNoCharge": "no",
                    "hasTrafficMirrorPortListOptimization": "yes",
                    "hasTrafficMirrorSaleOut": "no",
                    "hasTrafficMirrorSupportBMSelfNic": "yes",
                    "hasTrafficMirrorSupportELB": "yes",
                    "hasTrafficMirrorSupportENI": "yes",
                    "hasTrafficMirrorSupportFullPacket": "yes",
                    "hasTrafficMirrorSupportPacketLength": "yes",
                    "hasTrafficMirrorSupportsChange": "yes",
                    "hasTranscoding": "yes",
                    "hasTurnCycle": "yes",
                    "hasUEFI": "yes",
                    "hasUdpHcRequestResponse": "yes",
                    "hasUdpQuickIdHash": "yes",
                    "hasUpdateSubnet": "yes",
                    "hasUrlParamsEncryption": "yes",
                    "hasVPNFloatDoc": "yes",
                    "hasVailablePartition": "no",
                    "hasVip": "yes",
                    "hasVmGroupDetailGPU": "yes",
                    "hasVncCopy": "yes",
                    "hasVnetMrgwMirror": "yes",
                    "hasVoicePackage": "yes",
                    "hasVolumeMulticluster": "yes",
                    "hasVpcDefaultRouteSupportCustomCenCdaVpn": "yes",
                    "hasVpcFlowLog": "yes",
                    "hasVpcRouteDefaultSupportSubnetLocal": "yes",
                    "hasVpcRouteSupportSubnetLocal": "yes",
                    "hasVpcSupportCtyunIPv6CidrUserdefined": "yes",
                    "hasVpce": "yes",
                    "hasVpceCtyunctService": "yes",
                    "hasVpceIPaddressService": "yes",
                    "hasVpceIpv6": "yes",
                    "hasVpceMonitor": "yes",
                    "hasVpceMustEnableDns": "no",
                    "hasVpceNewSessionRateMonitor": "yes",
                    "hasVpceReverseRedirect": "yes",
                    "hasVpceSessionUsageMonitor": "yes",
                    "hasVpceSupportGatewayLB": "no",
                    "hasVpceSupportPolicyZos": "yes",
                    "hasVpnAddSmallGateway": "yes",
                    "hasVpnConnectQOS": "yes",
                    "hasVpnMonitor": "yes",
                    "hasVpnOnDemand": "yes",
                    "hasVpnRouteAddressValidate": "yes",
                    "hasVpnSmallGateway": "yes",
                    "hasVpnSslClient": "yes",
                    "hasWebAppFirewallMonitor": "yes",
                    "hasXSSD": "yes",
                    "hasXSSDEbsKms": "yes",
                    "hasXSSDShare": "yes",
                    "hasXSSDUpdate": "yes",
                    "hasXssdCMI": "probation",
                    "hasZMSTool": "no",
                    "hasZosFloatDoc": "no",
                    "hasZosMgr": "no",
                    "hasZsync": "no",
                    "hasZsyncDestPrefix": "yes",
                    "hasZsyncFloatDoc": "yes",
                    "hasZsyncStartTask": "yes",
                    "hasZsyncV2": "yes",
                    "hasmodifydefaultRTBname": "yes",
                    "hasrecoverOrder": "yes",
                    "hastrustSystem": "yes",
                    "hostGroupAdjustable": "yes",
                    "ims": "yes",
                    "internetChannel": "probation",
                    "intranetDns": "yes",
                    "ipsectConnectLog": "yes",
                    "ipv6Bw": "no",
                    "isCloseUnauthUserDelete": "probation",
                    "isDiscount": "no",
                    "isLimitCertBanWidth": "no",
                    "isMaz": "yes",
                    "isMultiZone": "yes",
                    "isSaleOutLargePrivateNat": "no",
                    "isSaleOutMediumPrivateNat": "no",
                    "isSaleOutSmallPrivateNat": "no",
                    "isSaleOutXlarge": "no",
                    "isSaleOutXlargePrivateNat": "no",
                    "isShowCh": "yes",
                    "isSupportCloudBGP": "yes",
                    "isSupportCnpInstanceBindVpc": "yes",
                    "isSupportCustomBandWidth": "yes",
                    "isSupportHealCheck": "yes",
                    "isSupportMD5AndDES": "yes",
                    "isSupportRedeployVm": "yes",
                    "isSupportRemoteSec": "yes",
                    "isSupportRoute": "yes",
                    "isSupportSM1": "yes",
                    "isSupportSSLMultifactor": "yes",
                    "isSupportSha1": "yes",
                    "isSupportVpnMonitorBandwidthUsage": "yes",
                    "isSupprotDownLoadConfig": "yes",
                    "isbytesCDNSendUpdate": "probation",
                    "istack": "yes",
                    "keypair": "yes",
                    "lat": "no",
                    "lbVersion": "3.0",
                    "liteecm": "yes",
                    "liteecmUrl": "yes",
                    "liveSpeedup": "yes",
                    "liveSpeedupSgt": "no",
                    "liveSpeedupSgtUrl": "https://cdn.ctyun.cn/h5/live/index.html#/",
                    "lng": "no",
                    "managermentIdentityandaccess": "yes",
                    "middlewarePaasArms": "yes",
                    "middlewarePaasArmsUrl": "https://arms.ctyun.cn/dy/arms/",
                    "middlewarePaasCls": "yes",
                    "middlewarePaasClsUrl": "https://als.ctyun.cn/dy/als/",
                    "middlewarePaasCsm": "yes",
                    "middlewarePaasMsap": "yes",
                    "middlewarePaasRcc": "yes",
                    "middlewarePaasRccUrl": "https://mse.ctyun.cn/dy/mse/",
                    "middlewarePaasTas": "yes",
                    "monitorPAAS": "middleware_paas_rcc,middleware_paas_msap,computed_paas_crs,computed_paas_ccse,db_paas_rds,db_paas_redis,db_paas_pgsql,db_paas_drds,middleware_paas_mq,middleware_paas_rabbit,middleware_paas_kafka",
                    "monitorPT": "ALL",
                    "newAbcSgt": "probation",
                    "obs": "yes",
                    "online": "yes",
                    "osFe": "yes",
                    "osFeUrl": "https://xstore.ctyun.cn/store",
                    "osProject": "admin",
                    "paas": {},
                    "paasMazUrlOnline": "yes",
                    "pfsIsNone": "yes",
                    "project": "vip",
                    "queryBatchNum": "3000",
                    "region": "cn-huhehaote-t11",
                    "regionCode": "cn-neimeng-8",
                    "regionName": "内蒙演示环境",
                    "remoteIDIsAny": "yes",
                    "resourceSoldout": "yes",
                    "routeRuleLooseCheck": "yes",
                    "sdwanCreateEdge": "yes",
                    "securityBgp": "yes",
                    "securityCafirewall": "no",
                    "securityCloudParse": "yes",
                    "securityCloudaudit": "yes",
                    "securityCloudauditPageEventtrack": "yes",
                    "securityCloudauditUrl": "http://staging-cns.test.ctyun.cn:28114/",
                    "securityCloudfirewall": "yes",
                    "securityCms": "yes",
                    "securityCmsUrl": "https://www.baidu.com",
                    "securityCsg": "yes",
                    "securityCsp": "yes",
                    "securityCspUrl": "https://ctcss.ctyun.cn/csp/overview/index",
                    "securityCtwt": "yes",
                    "securityDatabase": "yes",
                    "securityDatasecurityzone": "yes",
                    "securityDns": "yes",
                    "securityDoubleAuth": "yes",
                    "securityEasycoding": "no",
                    "securityEasycodingUrl": "https://rdc.easycoding.ctyun.cn/rdcloud/",
                    "securityGroup": "yes",
                    "securityGuard": "probation",
                    "securityGuardUrl": "http://www.ctyun.cn/orderconsole/ssg/console/list",
                    "securityKms": "yes",
                    "securityKmsUrl": "https://staging-cns.test.ctyun.cn:28108/kms/keys/index",
                    "securityLogAudit": "yes",
                    "securityMdr": "yes",
                    "securityMdrUrl": "https://ctcss.ctyun.cn/mdr",
                    "securityMif": "yes",
                    "securityMifUrl": "https://www.ctyun.cn/orderconsole/mif/console/public",
                    "securityOsm": "yes",
                    "securitySslCertificate": "probation",
                    "securitySslCertificateUrl": "probation",
                    "securityUsergroup": "yes",
                    "securityUsergroupUrl": "https://www.ctyun.cn/document/10345725",
                    "securityVss": "yes",
                    "securityWaf": "no",
                    "securityWafUrl": "https://ctcss.ctyun.cn/v2/waf",
                    "securityWebfirelwall": "yes",
                    "securityWebtamper": "yes",
                    "serviceUrl": "http://55.242.31.55:19000",
                    "setDiskReleaseWithPm": "yes",
                    "setDiskReleaseWithVm": "yes",
                    "snapshotCreateDisk": "yes",
                    "snatSupportCustomCidr": "yes",
                    "sslConfigLogs": "yes",
                    "sslIsSupportCert": "yes",
                    "state": 1,
                    "supportBindNum": "probation",
                    "supportVPCNatLimit": "yes",
                    "tagUpdateCtiamSwitch": "probation",
                    "test1Sgt": "yes",
                    "testMigSit": "yes",
                    "testProdMigSit": "yes",
                    "testWww": "probation",
                    "testzxh1": "yes",
                    "trustImage": "CTyunOS 23.01 64位-UEFI-仅支持可信云主机,CTyunOS-22.06-x86_64-UEFI-241103-B4-new",
                    "trustImageos": "CTyunOS",
                    "vmPreCreateOpen": "yes",
                    "vmPreCreateWhiteUserList": "[\"95c863b8e24746b5b257958df5661d76\"]",
                    "vpc": "yes",
                    "vpnConnectionTargetCountLimit": "yes",
                    "zabbixPwd": "Sdz8gqxQCsgktdtP",
                    "zabbixUrl": "http://10.150.66.248:1780/zabbix_guangxi2/",
                    "zabbixUser": "Admin_qd",
                    "zoneId": "public",
                    "zoneIdAzName": "public"
                },
                "paas": {
                    "dbPaasDrds": "yes",
                    "dbPaasDrdsUrl": "https://teledb.ctyun.cn/teledb-console/teledb-drds/instance-list",
                    "dbPaasHbase": "yes",
                    "dbPaasHbaseUrl": "http://10.150.66.12:18080/PAAS/",
                    "dbPaasMongodb": "yes",
                    "dbPaasMongodbUrl": "http://10.150.66.12:18080/PAAS/",
                    "dbPaasPgsql": "no",
                    "dbPaasPgsqlUrl": "https://teledb.ctyun.cn/teledb-console/teledb-pg/index",
                    "dbPaasRds": "no",
                    "dbPaasRdsUrl": "https://teledb.ctyun.cn/teledb-app/teledb-mysql",
                    "dbPaasRedis": "yes",
                    "dbPaasRedisUrl": "https://redis.ctyun.cn/dy/dcs2/",
                    "middlewarePaasKafka": "yes",
                    "middlewarePaasKafkaUrl": "https://www.baidu.com",
                    "middlewarePaasMq": "yes",
                    "middlewarePaasMqUrl": "https://www.baidu.com",
                    "middlewarePaasMqtt": "no",
                    "middlewarePaasMqttUrl": "https://www.baidu.com",
                    "middlewarePaasRabbit": "yes",
                    "middlewarePaasRabbitUrl": "https://www.baidu.com"
                },
                "pm": {
                    "PmVnc": "yes",
                    "azPmVncDomain": "yes",
                    "hasPMMultiNic": "yes",
                    "hasPmAdaptation": "yes",
                    "hasPmBindNic": "yes",
                    "hasPmChangeVpc": "yes",
                    "hasPmGpu": "yes",
                    "hasPmKeypair": "yes",
                    "pm": "yes",
                    "pmVncDomainName": "az_pm_vnc_domain"
                },
                "rds": {
                    "hasRDSReadnode": "yes"
                },
                "saas": {
                    "middlewareSaasServicestage": "yes",
                    "middlewareSaasServicestageUrl": "www.baidu.com"
                },
                "scaling": {
                    "hasEss": "yes"
                },
                "sdwan": {
                    "hasQos": "yes",
                    "hasSdwan": "yes",
                    "hasSdwanAclEdit": "yes",
                    "hasSdwanApply": "yes",
                    "hasSdwanCreateEdge": "yes",
                    "hasSdwanIpv6": "yes",
                    "hasSdwanOspf": "yes",
                    "hasSdwanQuickOffice": "yes",
                    "hasSdwanSingleArm": "yes"
                },
                "securitySafe": {
                    "securitySafe": "yes",
                    "securitySafeUrl": "https://staging-cns.test.ctyun.cn:28115/eShieldV2"
                },
                "sfs": {
                    "fileSystem": "yes"
                },
                "vpc": {
                    "dns1": "8.8.8.7",
                    "dns2": "114.114.114.115",
                    "hasCnp": "yes",
                    "hasIpv6netgate": "yes",
                    "hasMultiCidr4VPC": "yes",
                    "hasNat": "yes",
                    "hasNatIPPool": "yes",
                    "hasP2P": "yes",
                    "hasSharedBw": "yes",
                    "hasV6Nic": "yes",
                    "hasV6NicMonitor": "yes",
                    "hasVPCRouter": "yes",
                    "hasVPN": "yes",
                    "hasVirtualIp": "no",
                    "ipv6": "yes",
                    "isCnp": "yes",
                    "storageNetworkId": "827ddce3-96e0-463a-a2df-b5ff7ca0fafa",
                    "subnetOfferingIdWithNosnat": "public",
                    "subnetPoolId": "6b574493-5b78-4ed7-8878-969fdb9e0b1f",
                    "vpcOfferingId": "yes",
                    "vpcOfferingIdWithNosnat": "public"
                },
                "waf": {
                    "hasWaf": "yes"
                }
            },
            "statusCode": 800
        }
        with patch.object(self.client, 'get') as mock_get:
            mock_get.return_value.json.return_value = mock_response
            api = self.apis.ctecsqueryproductsinregionv41api
            response = api.do(self.credential, self.client, self.endpoint, request)

            # 验证结果
            self.assertIsInstance(response, CtecsQueryProductsInRegionV41Response)
            self.assertEqual(response.statusCode, 800)
            self.assertIsNotNone(response.returnObj)
            self.assertEqual(response.returnObj.acl.hasAcl, "yes")
            self.assertEqual(response.returnObj.caas.computedCaas, "yes")
            self.assertEqual(response.returnObj.cda.hasCda, "no")
            self.assertEqual(response.returnObj.cda.hasCdaMonitor, "yes")
            self.assertEqual(response.returnObj.ch.hasCh, "yes")
            self.assertEqual(response.returnObj.cnssl.hasCnssl, "no")
            self.assertEqual(response.returnObj.dec.hasDec, "yes")
            self.assertEqual(response.returnObj.ebs.hasBks, "yes")
            self.assertIsInstance(response.returnObj.ebs.storageType, list)
            self.assertEqual(len(response.returnObj.ebs.storageType), 7)
            self.assertEqual(response.returnObj.ebs.storageType[0].name, "普通IO")
            self.assertEqual(response.returnObj.ebs.storageType[0].type, "SATA")
            self.assertEqual(response.returnObj.ecs.hasAddNic, "yes")
            self.assertIsInstance(response.returnObj.ecs.flavorTypes.c, list)
            self.assertEqual(len(response.returnObj.ecs.flavorTypes.c), 5)
            self.assertEqual(response.returnObj.efs.hasEfsKms, "yes")
            self.assertEqual(response.returnObj.eip.hasEipMonitor, "yes")
            self.assertEqual(response.returnObj.hpc.computedHpc, "no")
            self.assertEqual(response.returnObj.image.hasMakeDiskImage, "yes")
            self.assertEqual(response.returnObj.kms.hasKms, "yes")
            self.assertEqual(response.returnObj.lb.hasElb, "yes")
            self.assertEqual(response.returnObj.monitor.hasMonitor, "yes")
            self.assertEqual(response.returnObj.order.hasAutoRenew, "yes")
            self.assertEqual(response.returnObj.oss.hasOss, "yes")
            self.assertEqual(response.returnObj.paas.dbPaasDrds, "yes")
            self.assertEqual(response.returnObj.pm.pm, "yes")
            self.assertEqual(response.returnObj.rds.hasRDSReadnode, "yes")
            self.assertIsNone(response.returnObj.rds.rdsStorage)
            self.assertEqual(response.returnObj.saas.middlewareSaasServicestage, "yes")
            self.assertEqual(response.returnObj.scaling.hasEss, "yes")
            self.assertEqual(response.returnObj.sdwan.hasSdwan, "yes")
            self.assertEqual(response.returnObj.securitySafe.securitySafe, "yes")
            self.assertEqual(response.returnObj.sfs.fileSystem, "yes")
            self.assertEqual(response.returnObj.vpc.hasVPN, "yes")
            self.assertEqual(response.returnObj.other.hasPmForceStop, "yes")
            self.assertIsInstance(response.returnObj.azList, list)
            self.assertEqual(len(response.returnObj.azList), 3)
            self.assertEqual(response.returnObj.azList[0].azName, "az1")
            self.assertEqual(response.returnObj.azList[0].azDisplayName, "西北-内蒙演示1")
            self.assertIsInstance(response.returnObj.azList[0].details.storageType, list)
            self.assertEqual(len(response.returnObj.azList[0].details.storageType), 7)
            self.assertEqual(response.returnObj.azList[0].details.storageType[0].type, "SATA")
            self.assertEqual(response.returnObj.azList[0].details.storageType[0].name, "普通IO")

    def test_failed_request(self):
        """测试失败的API请求"""
        request = CtecsQueryProductsInRegionV41Request(regionID='invalid_region_id')

        # Mock失败响应
        mock_response = {
            "message": "region info empty",
            "description": "资源池信息为空",
            "error": "Unknown.RegionInfo.Empty",
            "errorCode": "Unknown.RegionInfo.Empty",
            "returnObj": None,
            "statusCode": 900
        }

        with patch.object(self.client, 'get') as mock_get:
            mock_get.return_value.json.return_value = mock_response
            api = self.apis.ctecsqueryproductsinregionv41api
            response = api.do(self.credential, self.client, self.endpoint, request)

            # 验证错误响应
            self.assertEqual(response.statusCode, 900)
            self.assertEqual(response.errorCode, 'Unknown.RegionInfo.Empty')
            self.assertEqual(response.message, 'region info empty')
            self.assertEqual(response.description, '资源池信息为空')
            self.assertEqual(response.error, 'Unknown.RegionInfo.Empty')
            self.assertIsNone(response.returnObj)

    def test_invalid_credentials(self):
        """测试无效凭证"""
        invalid_credential = Credential('invalid_ak', 'invalid_sk')
        request = CtecsQueryProductsInRegionV41Request(regionID='81f7728662dd11ec810800155d307d5b')

        try:
            api = CtecsQueryProductsInRegionV41Api()
            api.set_endpoint(self.endpoint)
            response = api.do(invalid_credential, self.client, self.endpoint, request)
            self.assertIsNotNone(response)  # 验证响应不为空
            print(f'Response: {response}')  # 打印响应内容
        except CtyunRequestException as e:
            pass

    def test_request_validation(self):
        """测试请求参数验证"""
        with self.assertRaises(TypeError):
            # 缺少必填参数regionID
            CtecsQueryProductsInRegionV41Request()

        # 测试有效的请求参数
        valid_request = CtecsQueryProductsInRegionV41Request(regionID='valid_region_id')
        self.assertEqual(valid_request.regionID, 'valid_region_id')

    def test_empty_response_handling(self):
        """测试空响应处理"""
        with self.assertRaises(ValueError):
            CtecsQueryProductsInRegionV41Response.from_json({})

    def test_api_instance(self):
        """验证API实例是否正确初始化"""
        self.assertIsNotNone(self.apis)
        self.assertIsNotNone(self.apis.ctecsqueryproductsinregionv41api)

        # 验证API方法是否可用
        api = self.apis.ctecsqueryproductsinregionv41api
        self.assertTrue(callable(api.do))
        self.assertTrue(hasattr(api, 'set_endpoint'))


if __name__ == '__main__':
    unittest.main()
