from _typeshed import Incomplete
from ydata.characteristics import ColumnCharacteristic

logger: Incomplete

def get_n_unique_from_one(gen, n, max_iter: int | None = None, unique: bool = True): ...
def regex_generator(regex: str): ...
def id_generator(initial_value: int = 1): ...
def vat_generator(locale: str): ...
def phone_generator(locale: str): ...
def get_generator(characteristic: ColumnCharacteristic, locale: str = 'en'): ...
def convert_characteristic_to_int(data: list[str]) -> list[int]: ...
def convert_characteristic_to_float(data: list[str]) -> list[float]: ...
