from _typeshed import Incomplete
from sklearn.base import BaseEstimator, TransformerMixin
from ydata.__serializer import SerializerMixin

class BasePreprocessor(BaseEstimator, TransformerMixin, SerializerMixin):
    def __init__(self, metadata) -> None: ...
    @property
    def pipeline(self): ...
    @property
    def metadata(self): ...
    def fit(self, X, y: Incomplete | None = None, **kwargs) -> None: ...
    def transform(self, X) -> None: ...
    def inverse_transform(self, X) -> None: ...
