# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.dbu.v0 import dbuapi_pb2 as ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DbuApiStub(object):
    """Api

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetVersion = channel.unary_unary(
                '/ansys.api.dbu.v0.dbuapi.DbuApi/SetVersion',
                request_serializer=ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.SetVersionRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.SetVersionResponse.FromString,
                )
        self.GetVersion = channel.unary_unary(
                '/ansys.api.dbu.v0.dbuapi.DbuApi/GetVersion',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.GetVersionResponse.FromString,
                )


class DbuApiServicer(object):
    """Api

    """

    def SetVersion(self, request, context):
        """Sets the current scripting version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Sets the current scripting version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DbuApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVersion,
                    request_deserializer=ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.SetVersionRequest.FromString,
                    response_serializer=ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.SetVersionResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.dbu.v0.dbuapi.DbuApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DbuApi(object):
    """Api

    """

    @staticmethod
    def SetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.dbu.v0.dbuapi.DbuApi/SetVersion',
            ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.SetVersionRequest.SerializeToString,
            ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.SetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.dbu.v0.dbuapi.DbuApi/GetVersion',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ansys_dot_api_dot_dbu_dot_v0_dot_dbuapi__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
