# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.dbu.v0 import dbuwebmodels_pb2 as ansys_dot_api_dot_dbu_dot_v0_dot_dbuwebmodels__pb2
from ansys.api.dbu.v0 import sessionmanager_pb2 as ansys_dot_api_dot_dbu_dot_v0_dot_sessionmanager__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SessionManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/ansys.api.dbu.v0.sessionmanager.SessionManager/Start',
                request_serializer=ansys_dot_api_dot_dbu_dot_v0_dot_sessionmanager__pb2.StartRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_dbu_dot_v0_dot_sessionmanager__pb2.StartResponse.FromString,
                )
        self.Stop = channel.unary_unary(
                '/ansys.api.dbu.v0.sessionmanager.SessionManager/Stop',
                request_serializer=ansys_dot_api_dot_dbu_dot_v0_dot_dbuwebmodels__pb2.Session.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SessionManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=ansys_dot_api_dot_dbu_dot_v0_dot_sessionmanager__pb2.StartRequest.FromString,
                    response_serializer=ansys_dot_api_dot_dbu_dot_v0_dot_sessionmanager__pb2.StartResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=ansys_dot_api_dot_dbu_dot_v0_dot_dbuwebmodels__pb2.Session.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.dbu.v0.sessionmanager.SessionManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.dbu.v0.sessionmanager.SessionManager/Start',
            ansys_dot_api_dot_dbu_dot_v0_dot_sessionmanager__pb2.StartRequest.SerializeToString,
            ansys_dot_api_dot_dbu_dot_v0_dot_sessionmanager__pb2.StartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.dbu.v0.sessionmanager.SessionManager/Stop',
            ansys_dot_api_dot_dbu_dot_v0_dot_dbuwebmodels__pb2.Session.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
