# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/dbu/v0/streaming.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ansys/api/dbu/v0/streaming.proto\x12\x10\x61nsys.api.dbu.v0\"{\n\rStreamPackage\x12\x14\n\x0c\x63ontent_type\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\r\n\x05index\x18\x03 \x01(\x05\x12\x12\n\ntotal_size\x18\x04 \x01(\x05\x12\x14\n\x0cpackage_size\x18\x05 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x42\x1d\xaa\x02\x1a\x41nsys.Api.Dbu.V0.Streamingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ansys.api.dbu.v0.streaming_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\032Ansys.Api.Dbu.V0.Streaming'
  _STREAMPACKAGE._serialized_start=54
  _STREAMPACKAGE._serialized_end=177
# @@protoc_insertion_point(module_scope)
