import pandas as pd
from _typeshed import Incomplete
from sklearn.base import BaseEstimator, TransformerMixin

def forward_fill_strategy(df: pd.DataFrame): ...
def backward_fill_strategy(df: pd.DataFrame): ...
def linear_interpolation_strategy(df: pd.DataFrame): ...
def spline_interpolation_strategy(df: pd.DataFrame): ...
def knn_mean_strategy(df: pd.DataFrame): ...
def seasonal_mean_strategy(df: pd.DataFrame): ...
def calc_strategy_error(df: pd.DataFrame, df_implaced: pd.DataFrame): ...

class TimeSeriesImputer(BaseEstimator, TransformerMixin):
    cols_to_impute: Incomplete
    best_imputer: Incomplete
    def __init__(self, cols_to_impute) -> None: ...
    def fit(self, X): ...
    def fit_column(self, X): ...
    def transform(self, X, y: Incomplete | None = None): ...
    def inverse_transform(self, X): ...
