class DaskCluster:
    """Singleton class used to store the Dask cluster reference and its
    auxiliary functions."""
    def __init__(self) -> None: ...
    def memory_collect(self) -> None: ...
    @property
    def cluster(self): ...
    @property
    def client(self): ...
