from _typeshed import Incomplete
from ydata.characteristics import ColumnCharacteristic as ColumnCharacteristic
from ydata.utils.data_types import DataType, VariableType

class Column:
    name: Incomplete
    def __init__(self, name: str, datatype: DataType, vartype: VariableType, characteristics: tuple[ColumnCharacteristic, ...] = None) -> None: ...
    @property
    def datatype(self): ...
    @property
    def vartype(self): ...
    @property
    def characteristics(self) -> tuple[ColumnCharacteristic, ...]: ...
    @characteristics.setter
    def characteristics(self, characteristics: tuple[ColumnCharacteristic, ...]): ...
    @datatype.setter
    def datatype(self, value: DataType): ...
    @vartype.setter
    def vartype(self, vartype: VariableType) -> VariableType: ...
