"""Core functionality for quotely - motivational quotes library."""

import random as _random
from typing import List, Optional, Tuple

__all__ = ["Quote", "RandomQuote", "QuoteMarker", "random", "quote", "get_random_quote"]

ALL_QUOTES: List[Tuple[str, str]] = [
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    ("Everything you've ever wanted is on the other side of fear.", "George Addair"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
    ("Hardships often prepare ordinary people for an extraordinary destiny.", "C.S. Lewis"),
    ("Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", "Roy T. Bennett"),
    ("I learned that courage was not the absence of fear, but the triumph over it.", "Nelson Mandela"),
    ("There is only one thing that makes a dream impossible to achieve: the fear of failure.", "Paulo Coelho"),
    ("It's not whether you get knocked down, it's whether you get up.", "Vince Lombardi"),
    ("Your limitation—it's only your imagination.", "Unknown"),
    ("Great things never come from comfort zones.", "Unknown"),
    ("Dream it. Wish it. Do it.", "Unknown"),
    ("Success doesn't just find you. You have to go out and get it.", "Unknown"),
    ("The harder you work for something, the greater you'll feel when you achieve it.", "Unknown"),
    ("Dream bigger. Do bigger.", "Unknown"),
    ("Don't stop when you're tired. Stop when you're done.", "Unknown"),
    ("Wake up with determination. Go to bed with satisfaction.", "Unknown"),
    ("Do something today that your future self will thank you for.", "Unknown"),
    ("Little things make big days.", "Unknown"),
    ("The only true wisdom is in knowing you know nothing.", "Socrates"),
    ("The unexamined life is not worth living.", "Socrates"),
    ("Whereof one cannot speak, thereof one must be silent.", "Ludwig Wittgenstein"),
    ("I think, therefore I am.", "René Descartes"),
    ("He who has a why to live can bear almost any how.", "Friedrich Nietzsche"),
    ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"),
    ("The only thing I know is that I know nothing.", "Socrates"),
    ("In the middle of difficulty lies opportunity.", "Albert Einstein"),
    ("Life can only be understood backwards; but it must be lived forwards.", "Søren Kierkegaard"),
    ("The mind is everything. What you think you become.", "Buddha"),
    ("Turn your wounds into wisdom.", "Oprah Winfrey"),
    ("The only impossible journey is the one you never begin.", "Tony Robbins"),
    ("Change your thoughts and you change your world.", "Norman Vincent Peale"),
    ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    ("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", "Mark Twain"),
    ("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
    ("An unexamined life is not worth living.", "Socrates"),
    ("Knowledge speaks, but wisdom listens.", "Jimi Hendrix"),
    ("The fool doth think he is wise, but the wise man knows himself to be a fool.", "William Shakespeare"),
    ("Reality is merely an illusion, albeit a very persistent one.", "Albert Einstein"),
    ("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"),
    ("The way to get started is to quit talking and begin doing.", "Walt Disney"),
    ("Don't be afraid to give up the good to go for the great.", "John D. Rockefeller"),
    ("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"),
    ("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
    ("Opportunities don't happen. You create them.", "Chris Grosser"),
    ("Don't be distracted by criticism. Remember, the only taste of success some people get is to take a bite out of you.", "Zig Ziglar"),
    ("Success is walking from failure to failure with no loss of enthusiasm.", "Winston Churchill"),
    ("I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite.", "G.K. Chesterton"),
    ("Success seems to be connected with action. Successful people keep moving.", "Conrad Hilton"),
    ("The secret of success is to do the common thing uncommonly well.", "John D. Rockefeller Jr."),
    ("I never dreamed about success, I worked for it.", "Estée Lauder"),
    ("Success is not how high you have climbed, but how you make a positive difference to the world.", "Roy T. Bennett"),
    ("Fall seven times and stand up eight.", "Japanese Proverb"),
    ("The road to success and the road to failure are almost exactly the same.", "Colin R. Davis"),
    ("If you are not willing to risk the usual, you will have to settle for the ordinary.", "Jim Rohn"),
    ("Try not to become a man of success. Rather become a man of value.", "Albert Einstein"),
    ("A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", "David Brinkley"),
    ("Things work out best for those who make the best of how things work out.", "John Wooden"),
    ("Success is liking yourself, liking what you do, and liking how you do it.", "Maya Angelou"),
    ("Perseverance is not a long race; it is many short races one after the other.", "Walter Elliot"),
    ("It's not that I'm so smart, it's just that I stay with problems longer.", "Albert Einstein"),
    ("Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas Edison"),
    ("Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", "Thomas Edison"),
    ("Never give in except to convictions of honour and good sense.", "Winston Churchill"),
    ("A river cuts through rock, not because of its power, but because of its persistence.", "Jim Watkins"),
    ("Perseverance, secret of all triumphs.", "Victor Hugo"),
    ("The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", "Vince Lombardi"),
    ("Character consists of what you do on the third and fourth tries.", "James A. Michener"),
    ("You may have to fight a battle more than once to win it.", "Margaret Thatcher"),
    ("I am not discouraged, because every wrong attempt discarded is another step forward.", "Thomas Edison"),
    ("Through perseverance many people win success out of what seemed destined to be certain failure.", "Benjamin Disraeli"),
    ("Courage is not having the strength to go on; it is going on when you don't have the strength.", "Theodore Roosevelt"),
    ("The only guarantee for failure is to stop trying.", "John C. Maxwell"),
    ("Success is the sum of small efforts repeated day in and day out.", "Robert Collier"),
    ("It always seems impossible until it's done.", "Nelson Mandela"),
    ("You just can't beat the person who never gives up.", "Babe Ruth"),
    ("The man who moves a mountain begins by carrying away small stones.", "Confucius"),
    ("Perseverance is failing 19 times and succeeding the 20th.", "Julie Andrews"),
    ("Creativity is intelligence having fun.", "Albert Einstein"),
    ("The desire to create is one of the deepest yearnings of the human soul.", "Dieter F. Uchtdorf"),
    ("Creativity takes courage.", "Henri Matisse"),
    ("Every artist was first an amateur.", "Ralph Waldo Emerson"),
    ("Creativity is contagious, pass it on.", "Albert Einstein"),
    ("You can't use up creativity. The more you use, the more you have.", "Maya Angelou"),
    ("The chief enemy of creativity is good sense.", "Pablo Picasso"),
    ("Imagination is more important than knowledge.", "Albert Einstein"),
    ("The worst enemy to creativity is self-doubt.", "Sylvia Plath"),
    ("Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!", "Dr. Seuss"),
    ("Creativity is seeing what others see and thinking what no one else ever thought.", "Albert Einstein"),
    ("To live a creative life, we must lose our fear of being wrong.", "Joseph Chilton Pearce"),
    ("There is no doubt that creativity is the most important human resource of all.", "Edward de Bono"),
    ("Creativity is inventing, experimenting, growing, taking risks, breaking rules, making mistakes, and having fun.", "Mary Lou Cook"),
    ("Logic will get you from A to B. Imagination will take you everywhere.", "Albert Einstein"),
    ("Creativity requires the courage to let go of certainties.", "Erich Fromm"),
    ("The creative adult is the child who survived.", "Ursula K. Le Guin"),
    ("Don't think. Thinking is the enemy of creativity.", "Ray Bradbury"),
    ("An essential aspect of creativity is not being afraid to fail.", "Edwin Land"),
    ("The true sign of intelligence is not knowledge but imagination.", "Albert Einstein"),
    ("Life is what happens when you're busy making other plans.", "John Lennon"),
    ("The purpose of our lives is to be happy.", "Dalai Lama"),
    ("Life is really simple, but we insist on making it complicated.", "Confucius"),
    ("In the end, it's not the years in your life that count. It's the life in your years.", "Abraham Lincoln"),
    ("Life is either a daring adventure or nothing at all.", "Helen Keller"),
    ("Life isn't about finding yourself. Life is about creating yourself.", "George Bernard Shaw"),
    ("The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", "Henry Ford"),
    ("Not how long, but how well you have lived is the main thing.", "Seneca"),
    ("Life is made of ever so many partings welded together.", "Charles Dickens"),
    ("Your time is limited, don't waste it living someone else's life.", "Steve Jobs"),
    ("Live in the sunshine, swim the sea, drink the wild air.", "Ralph Waldo Emerson"),
    ("Life is a succession of lessons which must be lived to be understood.", "Helen Keller"),
    ("You only live once, but if you do it right, once is enough.", "Mae West"),
    ("Life is ten percent what happens to you and ninety percent how you respond to it.", "Charles R. Swindoll"),
    ("Keep smiling, because life is a beautiful thing and there's so much to smile about.", "Marilyn Monroe"),
    ("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"),
    ("Life is short, and it is up to you to make it sweet.", "Sarah Louise Delany"),
    ("The biggest adventure you can take is to live the life of your dreams.", "Oprah Winfrey"),
    ("Life is not a problem to be solved, but a reality to be experienced.", "Søren Kierkegaard"),
    ("Be yourself; everyone else is already taken.", "Oscar Wilde"),
    ("Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "Albert Einstein"),
    ("Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.", "Bernard M. Baruch"),
    ("Be the change that you wish to see in the world.", "Mahatma Gandhi"),
    ("If you tell the truth, you don't have to remember anything.", "Mark Twain"),
    ("A friend is someone who knows all about you and still loves you.", "Elbert Hubbard"),
    ("To live is the rarest thing in the world. Most people exist, that is all.", "Oscar Wilde"),
    ("Without music, life would be a mistake.", "Friedrich Nietzsche"),
    ("We accept the love we think we deserve.", "Stephen Chbosky"),
    ("It is better to be hated for what you are than to be loved for what you are not.", "André Gide"),
    ("Insanity is doing the same thing, over and over again, but expecting different results.", "Albert Einstein"),
    ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
    ("The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.", "Jane Austen"),
    ("Good friends, good books, and a sleepy conscience: this is the ideal life.", "Mark Twain"),
    ("Life is what we make it, always has been, always will be.", "Grandma Moses"),
    ("The only way out of the labyrinth of suffering is to forgive.", "John Green"),
    ("Do one thing every day that scares you.", "Eleanor Roosevelt"),
    ("It is our choices that show what we truly are, far more than our abilities.", "J.K. Rowling"),
    ("Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", "Neil Gaiman"),
    ("Everything you can imagine is real.", "Pablo Picasso"),
    ("When one door of happiness closes, another opens.", "Helen Keller"),
    ("You cannot protect yourself from sadness without protecting yourself from happiness.", "Jonathan Safran Foer"),
    ("I may not have gone where I intended to go, but I think I have ended up where I needed to be.", "Douglas Adams"),
    ("The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.", "Mark Twain"),
    ("A day without sunshine is like, you know, night.", "Steve Martin"),
    ("This life's hard, but it's harder if you're stupid.", "George V. Higgins"),
    ("So many books, so little time.", "Frank Zappa"),
    ("A room without books is like a body without a soul.", "Marcus Tullius Cicero"),
    ("You know you're in love when you can't fall asleep because reality is finally better than your dreams.", "Dr. Seuss"),
    ("Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", "Marilyn Monroe"),
    ("There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", "Albert Einstein"),
    ("Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", "Bill Keane"),
    ("I solemnly swear that I am up to no good.", "J.K. Rowling"),
    ("Friendship is born at that moment when one person says to another: 'What! You too? I thought I was the only one.", "C.S. Lewis"),
    ("If you can't explain it to a six year old, you don't understand it yourself.", "Albert Einstein"),
    ("The opposite of love is not hate, it's indifference.", "Elie Wiesel"),
    ("It is not a lack of love, but a lack of friendship that makes unhappy marriages.", "Friedrich Nietzsche"),
    ("As he read, I fell in love the way you fall asleep: slowly, and then all at once.", "John Green"),
    ("I like nonsense, it wakes up the brain cells.", "Dr. Seuss"),
    ("I may not agree with you, but I will defend to the death your right to make an ass of yourself.", "Oscar Wilde"),
    ("Never put off till tomorrow what may be done day after tomorrow just as well.", "Mark Twain"),
    ("Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", "Lao Tzu"),
    ("It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", "J.K. Rowling"),
    ("To the well-organized mind, death is but the next great adventure.", "J.K. Rowling"),
    ("Have you ever been in love? Horrible isn't it?", "Neil Gaiman"),
    ("The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.", "Bob Marley"),
    ("Not all those who wander are lost.", "J.R.R. Tolkien"),
    ("Do not pity the dead. Pity the living, and, above all those who live without love.", "J.K. Rowling"),
    ("There is nothing I would not do for those who are really my friends.", "Jane Austen"),
    ("This above all: to thine own self be true.", "William Shakespeare"),
    ("If you judge people, you have no time to love them.", "Mother Teresa"),
    ("Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.", "Garrison Keillor"),
    ("Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.", "Jim Henson"),
    ("I am enough of an artist to draw freely upon my imagination.", "Albert Einstein"),
    ("The more that you read, the more things you will know. The more that you learn, the more places you'll go.", "Dr. Seuss"),
    ("It is never too late to be what you might have been.", "George Eliot"),
    ("You can never get a cup of tea large enough or a book long enough to suit me.", "C.S. Lewis"),
    ("You believe lies so you eventually learn to trust no one but yourself.", "Marilyn Monroe"),
    ("A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left.", "Marilyn Monroe"),
    ("If you don't stand for something you will fall for anything.", "Gordon A. Eadie"),
    ("All you need is love. But a little chocolate now and then doesn't hurt.", "Charles M. Schulz"),
    ("We read to know we're not alone.", "William Nicholson"),
    ("Any fool can know. The point is to understand.", "Albert Einstein"),
    ("I have always imagined that Paradise will be a kind of library.", "Jorge Luis Borges"),
    ("It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.", "Maurice Switzer"),
    ("Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.", "Groucho Marx"),
    ("The reason I talk to myself is because I'm the only one whose answers I accept.", "George Carlin"),
    ("The truth will set you free, but first it will piss you off.", "Joe Klaas"),
    ("You talk when you cease to be at peace with your thoughts.", "Kahlil Gibran"),
    ("May you live every day of your life.", "Jonathan Swift"),
    ("I am free of all prejudice. I hate everyone equally.", "W.C. Fields"),
    ("The question isn't who is going to let me; it's who is going to stop me.", "Ayn Rand"),
    ("To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson"),
    ("Whenever you find yourself on the side of the majority, it is time to reform.", "Mark Twain"),
    ("The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", "Albert Camus"),
    ("Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", "Rumi"),
    ("What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it.", "Maya Angelou"),
    ("The wound is the place where the Light enters you.", "Rumi"),
    ("Don't walk in front of me… I may not follow. Don't walk behind me… I may not lead. Walk beside me… just be my friend.", "Albert Camus"),
    ("No one can make you feel inferior without your consent.", "Eleanor Roosevelt"),
    ("If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", "J.K. Rowling"),
    ("I'm not afraid of death; I just don't want to be there when it happens.", "Woody Allen"),
    ("This is your life and it's ending one moment at a time.", "Chuck Palahniuk"),
    ("The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", "Isaac Asimov"),
    ("All that is gold does not glitter, not all those who wander are lost.", "J.R.R. Tolkien"),
    ("You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.", "A.A. Milne"),
    ("Some people never go crazy. What truly horrible lives they must lead.", "Charles Bukowski"),
    ("We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde"),
    ("Never doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has.", "Margaret Mead"),
    ("It does not do to dwell on dreams and forget to live.", "J.K. Rowling"),
    ("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
    ("We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "Plato"),
    ("Do I not destroy my enemies when I make them my friends?", "Abraham Lincoln"),
    ("Sometimes the questions are complicated and the answers are simple.", "Dr. Seuss"),
    ("How wonderful it is that nobody need wait a single moment before starting to improve the world.", "Anne Frank"),
    ("Today you are You, that is truer than true. There is no one alive who is Youer than You.", "Dr. Seuss"),
    ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    ("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
    ("Don't let yesterday take up too much of today.", "Will Rogers"),
    ("Life isn't about getting and having, it's about giving and being.", "Kevin Kruse"),
    ("Whatever the mind of man can conceive and believe, it can achieve.", "Napoleon Hill"),
    ("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
    ("Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", "Robert Frost"),
    ("I attribute my success to this: I never gave or took any excuse.", "Florence Nightingale"),
    ("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    ("I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan"),
    ("The most difficult thing is the decision to act, the rest is merely tenacity.", "Amelia Earhart"),
    ("Every strike brings me closer to the next home run.", "Babe Ruth"),
    ("Definiteness of purpose is the starting point of all achievement.", "W. Clement Stone"),
    ("We must balance conspicuous consumption with conscious capitalism.", "Kevin Kruse"),
    ("We become what we think about.", "Earl Nightingale"),
    ("Life is 10% what happens to me and 90% of how I react to it.", "Charles Swindoll"),
    ("The most common way people give up their power is by thinking they don't have any.", "Alice Walker"),
    ("Eighty percent of success is showing up.", "Woody Allen"),
    ("Winning isn't everything, but wanting to win is.", "Vince Lombardi"),
    ("I am not a product of my circumstances. I am a product of my decisions.", "Stephen Covey"),
    ("Every child is an artist. The problem is how to remain an artist once he grows up.", "Pablo Picasso"),
    ("You can never cross the ocean until you have the courage to lose sight of the shore.", "Christopher Columbus"),
    ("I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "Maya Angelou"),
    ("Either you run the day, or the day runs you.", "Jim Rohn"),
    ("Whether you think you can or you think you can't, you're right.", "Henry Ford"),
    ("The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"),
    ("Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "Johann Wolfgang von Goethe"),
    ("The best revenge is massive success.", "Frank Sinatra"),
    ("People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "Zig Ziglar"),
    ("Life shrinks or expands in proportion to one's courage.", "Anais Nin"),
    ("If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "Vincent Van Gogh"),
    ("There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "Aristotle"),
    ("Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", "Jesus"),
    ("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    ("Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"),
    ("When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "Erma Bombeck"),
    ("Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "Booker T. Washington"),
    ("Certain things catch your eye, but pursue only those that capture the heart.", "Ancient Indian Proverb"),
    ("Teach thy tongue to say, 'I do not know,' and thous shalt progress.", "Maimonides"),
    ("When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down 'happy'. They told me I didn't understand the assignment, and I told them they didn't understand life.", "John Lennon"),
    ("When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", "Helen Keller"),
    ("Everything has beauty, but not everyone can see.", "Confucius"),
    ("When I let go of what I am, I become what I might be.", "Lao Tzu"),
    ("Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "Maya Angelou"),
    ("Happiness is not something readymade. It comes from your own actions.", "Dalai Lama"),
    ("If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", "Sheryl Sandberg"),
    ("First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.", "Aristotle"),
    ("If the wind will not serve, take to the oars.", "Latin Proverb"),
    ("You can't fall if you don't climb. But there's no joy in living your whole life on the ground.", "Unknown"),
    ("We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", "Marie Curie"),
    ("Too many of us are not living our dreams because we are living our fears.", "Les Brown"),
    ("Challenges are what make life interesting and overcoming them is what makes life meaningful.", "Joshua J. Marine"),
    ("If you want to lift yourself up, lift up someone else.", "Booker T. Washington"),
    ("I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", "Leonardo da Vinci"),
    ("Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", "Jamie Paolinetti"),
    ("You take your life in your own hands, and what happens? A terrible thing, no one to blame.", "Erica Jong"),
    ("What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", "Bob Dylan"),
    ("I didn't fail the test. I just found 100 ways to do it wrong.", "Benjamin Franklin"),
    ("In order to succeed, your desire for success should be greater than your fear of failure.", "Bill Cosby"),
    ("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    ("The person who says it cannot be done should not interrupt the person who is doing it.", "Chinese Proverb"),
    ("There are no traffic jams along the extra mile.", "Roger Staubach"),
    ("You become what you believe.", "Oprah Winfrey"),
    ("I would rather die of passion than of boredom.", "Vincent van Gogh"),
    ("A truly rich man is one whose children run into his arms when his hands are empty.", "Unknown"),
    ("It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.", "Ann Landers"),
    ("If you want your children to turn out well, spend twice as much time with them, and half as much money.", "Abigail Van Buren"),
    ("Build your own dreams, or someone else will hire you to build theirs.", "Farrah Gray"),
    ("The battles that count aren't the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that's where it's at.", "Jesse Owens"),
    ("Education costs money. But then so does ignorance.", "Sir Claus Moser"),
    ("I have learned over the years that when one's mind is made up, this diminishes fear.", "Rosa Parks"),
    ("If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "Oprah Winfrey"),
    ("Remember that not getting what you want is sometimes a wonderful stroke of luck.", "Dalai Lama"),
    ("Dream big and dare to fail.", "Norman Vaughan"),
    ("Our lives begin to end the day we become silent about things that matter.", "Martin Luther King Jr."),
    ("Do what you can, where you are, with what you have.", "Teddy Roosevelt"),
    ("If you do what you've always done, you'll get what you've always gotten.", "Tony Robbins"),
    ("Dreaming, after all, is a form of planning.", "Gloria Steinem"),
    ("It's your place in the world; it's your life. Go on and do all you can with it, and make it the life you want to live.", "Mae Jemison"),
    ("You may be disappointed if you fail, but you are doomed if you don't try.", "Beverly Sills"),
    ("Remember no one can make you feel inferior without your consent.", "Eleanor Roosevelt"),
    ("When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", "Henry Ford"),
    ("It's not the years in your life that count. It's the life in your years.", "Abraham Lincoln"),
    ("Either write something worth reading or do something worth writing.", "Benjamin Franklin"),
    ("Nothing is impossible, the word itself says, 'I'm possible!'", "Audrey Hepburn"),
    ("If you can dream it, you can achieve it.", "Zig Ziglar"),
    ("A goal is a dream with a deadline.", "Napoleon Hill"),
    ("A house divided against itself cannot stand.", "Abraham Lincoln"),
    ("A prudent question is one half of wisdom.", "Francis Bacon"),
    ("A really great talent finds its happiness in execution.", "Johann Wolfgang von Goethe"),
    ("A rolling stone gathers no moss.", "Publilius Syrus"),
    ("A short saying oft contains much wisdom.", "Sophocles"),
    ("A short saying often contains much wisdom.", "Sophocles"),
    ("A weed is no more than a flower in disguise.", "James Lowell"),
    ("All know the way; few actually walk it.", "Bodhidharma"),
    ("All our knowledge has its origins in our perceptions.", "Leonardo da Vinci"),
    ("All serious daring starts from within.", "Harriet Beecher Stowe"),
    ("Anticipate the difficult by managing the easy.", "Lao Tzu"),
    ("Argue for your limitations, and sure enough theyre yours.", "Richard Bach"),
    ("Autumn is a second spring when every leaf is a flower.", "Albert Camus"),
    ("Be as you wish to seem.", "Socrates"),
    ("Be great in act, as you have been in thought.", "William Shakespeare"),
    ("Be kind whenever possible. It is always possible.", "Dalai Lama"),
    ("Be the chief but never the lord.", "Lao Tzu"),
    ("Begin to weave and God will give you the thread.", "German proverb"),
    ("Better be ignorant of a matter than half know it.", "Publilius Syrus"),
    ("Bite off more than you can chew, then chew it.", "Ella Williams"),
    ("Blaze with the fire that is never extinguished.", "Luisa Sigea"),
    ("Character develops itself in the stream of life.", "Johann Wolfgang von Goethe"),
    ("Change in all things is sweet.", "Aristotle"),
    ("Courage is going from failure to failure without losing enthusiasm.", "Winston Churchill"),
    ("Difficulties are things that show a person what they are.", "Epictetus"),
    ("Difficulties increase the nearer we get to the goal.", "Johann Wolfgang von Goethe"),
    ("Do something wonderful, people may imitate it.", "Albert Schweitzer"),
    ("Do, or do not. There is no try.", "Yoda"),
    ("Do more than dream: work.", "William Arthur Ward"),
    ("Doing nothing is better than being busy doing nothing.", "Lao Tzu"),
    ("Don't compromise yourself. You are all you've got.", "Janis Joplin"),
    ("Don't cry because it's over. Smile because it happened.", "Dr. Seuss"),
    ("Don't ruin the present with the ruined past.", "Ellen Gilchrist"),
    ("Don't wait. The time will never be just right.", "Napoleon Hill"),
    ("Each day provides its own gifts.", "Marcus Aurelius"),
    ("Efficiency is doing things right; effectiveness is doing the right things.", "Peter Drucker"),
    ("Either you run the day or the day runs you.", "Jim Rohn"),
    ("Everything in life is luck.", "Donald Trump"),
    ("Experience is simply the name we give our mistakes.", "Oscar Wilde"),
    ("Faith in oneself is the best and safest course.", "Michelangelo"),
    ("Fate is in your hands and no one elses", "Byron Pulsifer"),
    ("Fears are nothing more than a state of mind.", "Napoleon Hill"),
    ("Follow your instincts. That is where true wisdom manifests itself.", "Oprah Winfrey"),
    ("Fortune befriends the bold.", "John Dryden"),
    ("Fortune favours the brave.", "Virgil"),
    ("Freedom is the right to live as we wish.", "Epictetus"),
    ("From error to error one discovers the entire truth.", "Sigmund Freud"),
    ("From little acorns mighty oaks do grow.", "American proverb"),
    ("Genius is one percent inspiration and ninety-nine percent perspiration.", "Thomas Edison"),
    ("God always takes the simplest way.", "Albert Einstein"),
    ("Goals are the fuel in the furnace of achievement.", "Brian Tracy"),
    ("Good luck is another name for tenacity of purpose.", "Ralph Emerson"),
    ("Great talent finds happiness in execution.", "Johann Wolfgang von Goethe"),
    ("Growth itself contains the germ of happiness.", "Pearl Buck"),
    ("Happiness is found in doing, not merely possessing.", "Napoleon Hill"),
    ("Having nothing, nothing can he lose.", "William Shakespeare"),
    ("He is able who thinks he is able.", "Buddha"),
    ("He that is giddy thinks the world turns round.", "William Shakespeare"),
    ("He who is contented is rich.", "Lao Tzu"),
    ("He who talks more is sooner exhausted.", "Lao Tzu"),
    ("I allow my intuition to lead my path.", "Manuel Puig"),
    ("I believe in one thing only, the power of human will.", "Joseph Stalin"),
    ("I believe that every person is born with talent.", "Maya Angelou"),
    ("Ideas are the beginning points of all fortunes.", "Napoleon Hill"),
    ("I destroy my enemies when I make them my friends.", "Abraham Lincoln"),
    ("If the shoe doesn't fit, must we change the foot?", "Gloria Steinem"),
    ("If you can dream it, you can do it.", "Walt Disney"),
    ("If you cannot be silent be brilliant and thoughtful.", "Byron Pulsifer"),
    ("If you surrender to the wind, you can ride it.", "Toni Morrison"),
    ("If you wish to be a writer, write.", "Epictetus"),
    ("Imagination rules the world.", "Napoleon Bonaparte"),
    ("Important principles may, and must, be inflexible.", "Abraham Lincoln"),
    ("In order to win, you must expect to win.", "Richard Bach"),
    ("Inspiration exists, but it has to find us working.", "Pablo Picasso"),
    ("Intuition will tell the thinking mind where to look next.", "Jonas Salk"),
    ("It is better to travel well than to arrive.", "Buddha"),
    ("Keep true to the dreams of thy youth.", "Friedrich von Schiller"),
    ("Keep yourself to the sunshine and you cannot see the shadow.", "Helen Keller"),
    ("Kind words do not cost much. Yet they accomplish much.", "Blaise Pascal"),
    ("Kind words will unlock an iron door.", "Turkish proverb"),
    ("Knowing is not enough; we must apply!", "Johann Wolfgang von Goethe"),
    ("Learn from yesterday, live for today, hope for tomorrow.", "Albert Einstein"),
    ("Learning is a treasure that will follow its owner everywhere", "Chinese proverb"),
    ("Life is a learning experience, only if you learn.", "Yogi Berra"),
    ("Life is a movement-we breathe, we eat, we walk, we move!", "John Pierrakos"),
    ("Life is just a chance to grow a soul.", "A. Powell Davies"),
    ("Life is the flower for which love is the honey.", "Victor Hugo"),
    ("Life is change. Growth is optional. Choose wisely.", "Karen Clark"),
    ("Light tomorrow with today!", "Elizabeth Browning"),
    ("Loss is nothing else but change,and change is Natures delight.", "Marcus Aurelius"),
    ("Love all, trust a few, do wrong to none.", "William Shakespeare"),
    ("Love is the flower you've got to let grow.", "John Lennon"),
    ("Luck is what happens when preparation meets opportunity.", "Seneca"),
    ("May our hearts garden of awakening bloom with hundreds of flowers.", "Thich Nhat Hanh"),
    ("The mind unlearns with difficulty what it has long learned.", "Seneca"),
    ("Mountains cannot be surmounted except by winding paths.", "Johann Wolfgang von Goethe"),
    ("Nature takes away any faculty that is not used.", "William R. Inge"),
    ("Never ignore a gut feeling, but never believe that it's enough.", "Robert Heller"),
    ("Never mistake activity for achievement.", "John Wooden"),
    ("No alibi will save you from accepting the responsibility.", "Napoleon Hill"),
    ("No garden is without its weeds.", "Thomas Fuller"),
    ("No is easier to do. Yes is easier to say.", "Jason Fried"),
    ("No man was ever wise by chance.", "Seneca"),
    ("No snowflake in an avalanche ever feels responsible.", "Voltaire"),
    ("Nobody will believe in you unless you believe in yourself.", "Liberace"),
    ("Nothing happens unless first we dream.", "Carl Sandburg"),
    ("Nothing strengthens authority so much as silence.", "Leonardo da Vinci"),
    ("Once we accept our limits, we go beyond them.", "Albert Einstein"),
    ("Once you choose hope, anythings possible.", "Christopher Reeve"),
    ("One fails forward toward success.", "Charles Kettering"),
    ("One faces the future with ones past.", "Pearl Buck"),
    ("One today is worth two tomorrows.", "Benjamin Franklin"),
    ("Only do what your heart tells you.", "Princess Diana"),
    ("Our distrust is very expensive.", "Ralph Emerson"),
    ("Our intention creates our reality.", "Wayne Dyer"),
    ("Our strength grows out of our weaknesses.", "Ralph Waldo Emerson"),
    ("Patience is the companion of wisdom.", "Saint Augustine"),
    ("Peace comes from within. Do not seek it without.", "Buddha"),
    ("Pick battles big enough to matter, small enough to win.", "Jonathan Kozol"),
    ("Problems are only opportunities with thorns on them.", "Hugh Miller"),
    ("Rainbows apologize for angry skies.", "Sylvia Voirol"),
    ("Real magic in relationships means an absence of judgement of others.", "Wayne Dyer"),
    ("Reality does not conform to the ideal, but confirms it.", "Gustave Flaubert"),
    ("Reality leaves a lot to the imagination.", "John Lennon"),
    ("Self-complacency is fatal to progress.", "Margaret Sangster"),
    ("Set your goals high, and don't stop till you get there.", "Bo Jackson"),
    ("Silence is a fence around wisdom.", "German proverb"),
    ("Silence is deep as Eternity, Speech is shallow as Time.", "Carlyle"),
    ("Silence is a true friend who never betrays.", "Confucius"),
    ("Skill to do comes of doing.", "Ralph Emerson"),
    ("Smile, breathe, and go slowly.", "Thich Nhat Hanh"),
    ("Society develops wit, but its contemplation alone forms genius.", "Madame de Stael"),
    ("Someone is special only if you tell them.", "Byron Pulsifer"),
    ("Speak low, if you speak love.", "William Shakespeare"),
    ("Strong beliefs win strong men, and then make them stronger.", "Richard Bach"),
    ("Study the past, if you would divine the future.", "Confucius"),
    ("Talk doesn't cook rice.", "Chinese proverb"),
    ("The best teacher is experience learned from failures.", "Byron Pulsifer"),
    ("The best way out is always through.", "Robert Frost"),
    ("The cause is hidden. The effect is visible to all.", "Ovid"),
    ("The greatest remedy for anger is delay.", "Seneca"),
    ("The heart has its reasons which reason knows not of.", "Blaise Pascal"),
    ("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    ("The more you know yourself, the more you forgive yourself.", "Confucius"),
    ("The only real valuable thing is intuition.", "Albert Einstein"),
    ("The path to success is to take massive, determined action.", "Tony Robbins"),
    ("The shortest answer is doing.", "Lord Herbert"),
    ("The simplest things are often the truest.", "Richard Bach"),
    ("The two most powerful warriors are patience and time.", "Leo Tolstoy"),
    ("The truest wisdom is a resolute determination.", "Napoleon Bonaparte"),
    ("The undertaking of a new action brings new strength.", "Richard Evans"),
    ("The world is always in movement.", "V. Naipaul"),
    ("The years teach much which the days never know.", "Ralph Emerson"),
    ("There is no failure except in no longer trying.", "Elbert Hubbard"),
    ("There is no greater harm than that of time wasted.", "Michelangelo"),
    ("There is no way to happiness, happiness is the way.", "Thich Nhat Hanh"),
    ("There is no way to prosperity, prosperity is the way.", "Wayne Dyer"),
    ("Think how hard physics would be if particles could think.", "Murray Gell-Mann"),
    ("Those who are free of resentful thoughts surely find peace.", "Buddha"),
    ("Time is the most valuable thing a man can spend.", "Theophrastus"),
    ("Time is the wisest counsellor of all.", "Pericles"),
    ("To accomplish great things, we must dream as well as act.", "Anatole France"),
    ("To be wrong is nothing unless you continue to remember it.", "Confucius"),
    ("To bring anything into your life, imagine that it's already there.", "Richard Bach"),
    ("To enjoy life, we must touch much of it lightly.", "Voltaire"),
    ("To fly, we have to have resistance.", "Maya Lin"),
    ("To lead people walk behind them.", "Lao Tzu"),
    ("To succeed, we must first believe that we can.", "Michael Korda"),
    ("Trouble is only opportunity in work clothes.", "Henry J. Kaiser"),
    ("Trust yourself. You know more than you think you do.", "Benjamin Spock"),
    ("Trusting our intuition often saves us from disaster.", "Anne Wilson Schaef"),
    ("Truth is powerful and it prevails.", "Sojourner Truth"),
    ("Victory belongs to the most persevering.", "Napoleon Bonaparte"),
    ("We can only learn to love by loving.", "Iris Murdoch"),
    ("We choose our destiny in the way we treat others.", "Wit"),
    ("We must become the change we want to see.", "Mahatma Gandhi"),
    ("Well begun is half done.", "Aristotle"),
    ("Well done is better than well said.", "Benjamin Franklin"),
    ("What we achieve inwardly will change outer reality.", "Plutarch"),
    ("What we think, we become.", "Buddha"),
    ("What worries you masters you.", "Haddon Robinson"),
    ("What you fear is that which requires action to overcome.", "Byron Pulsifer"),
    ("What you give is what you get.", "Byron Pulsifer"),
    ("Whatever happens, take responsibility.", "Tony Robbins"),
    ("Whatever we expect with confidence becomes our own self-fulfilling prophecy.", "Brian Tracy"),
    ("When deeds speak, words are nothing.", "African proverb"),
    ("When performance exceeds ambition, the overlap is called success.", "Cullen Hightower"),
    ("When you doubt your power, you give power to your doubt.", "Honore de Balzac"),
    ("Wherever you go, go with all your heart.", "Confucius"),
    ("While we stop to think, we often miss our opportunity.", "Publilius Syrus"),
    ("Who looks outside, dreams; who looks inside, awakes.", "Carl Jung"),
    ("Who sows virtue reaps honour.", "Leonardo da Vinci"),
    ("Wisdom begins in wonder.", "Socrates"),
    ("Wisdom is the supreme part of happiness.", "Sophocles"),
    ("Without courage, wisdom bears no fruit.", "Baltasar Gracian"),
    ("Without faith, nothing is possible. With it, nothing is impossible.", "Mary Bethune"),
    ("Work out your own salvation. Do not depend on others.", "Buddha"),
    ("Write your plans in pencil and give God the eraser.", "Paulo Coelho"),
    ("Yesterday I dared to struggle. Today I dare to win.", "Bernadette Devlin"),
    ("Yesterdays home runs don't win today's games.", "Babe Ruth"),
    ("You can do it if you believe you can!", "Napoleon Hill"),
    ("You can observe a lot just by watching.", "Yogi Berra"),
    ("You can't stop the waves, but you can learn to surf.", "Jon Kabat-Zinn"),
    ("You give before you get.", "Napoleon Hill"),
    ("You have to believe in yourself.", "Sun Tzu"),
    ("You'll see it when you believe it.", "Wayne Dyer"),
    ("You're never a loser until you quit trying.", "Mike Ditka"),
]


class Quote:
    """Quote object providing structured access to quote text and author.
    
    Attributes:
        name: Author name
    """
    
    __slots__ = ("_text", "_author", "name")
    
    def __init__(self, text: str, author: str) -> None:
        self._text = text
        self._author = author
        self.name = author
    
    def __str__(self) -> str:
        return self._text
    
    def __repr__(self) -> str:
        return f'"{self._text}" - {self._author}'


class RandomQuote:
    """Random quote generator with callable interface.
    
    Provides two methods:
        - __call__(): Returns quote text only
        - name(): Returns quote with author attribution
    """
    
    __slots__ = ()
    
    def __call__(self, _: Optional[object] = None) -> str:
        """Return random quote text.
        
        Args:
            _: Optional marker parameter (ignored)
            
        Returns:
            Random quote text
        """
        text, _ = _random.choice(ALL_QUOTES)
        return text
    
    def name(self, _: Optional[object] = None) -> str:
        """Return random quote with author attribution.
        
        Args:
            _: Optional marker parameter (ignored)
            
        Returns:
            Formatted string: "quote text" - Author Name
        """
        text, author = _random.choice(ALL_QUOTES)
        return f'"{text}" - {author}'


class QuoteMarker:
    """Marker class for API convention."""
    
    __slots__ = ()


random = RandomQuote()
quote = QuoteMarker()


def get_random_quote() -> Quote:
    """Generate a new random Quote object.
    
    Returns:
        Quote instance with text and author
    """
    text, author = _random.choice(ALL_QUOTES)
    return Quote(text, author)
