#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from enum import StrEnum


_CLIENT_ERROR_PREFIX = "C"
_SERVER_ERROR_PREFIX = "S"
_REMOTE_ERROR_PREFIX = "R"


class ErrorCode(StrEnum):
    # Client error
    CLIENT_ERROR = _CLIENT_ERROR_PREFIX + "0000"
    CLIENT_PARAM_ERROR = _CLIENT_ERROR_PREFIX + "0001"
    LOGIN_FAILED = _CLIENT_ERROR_PREFIX + "0002"
    QUEUE_FULL = _CLIENT_ERROR_PREFIX + "0003"
    UNSUPPORTED_MODE = _CLIENT_ERROR_PREFIX + "0004"
    UNSUPPORTED_CONFIG_TYPE = _CLIENT_ERROR_PREFIX + "0005"

    # Server error
    SERVER_ERROR = _SERVER_ERROR_PREFIX + "0000"
    PLUGIN_NOT_FOUND = _SERVER_ERROR_PREFIX + "0001"
    DETECT_CURRENT_MODE_FAILED = _SERVER_ERROR_PREFIX + "0002"
    DETECT_CURRENT_VSYS_FAILED = _SERVER_ERROR_PREFIX + "0003"

    # Remote error
    REMOTE_ERROR = _REMOTE_ERROR_PREFIX + "0000"
    # 0X Connection
    CONNECT_TIMEOUT = _REMOTE_ERROR_PREFIX + "0001"
    CONNECT_FAILED = _REMOTE_ERROR_PREFIX + "0002"
    SESSION_INIT_FAILED = _REMOTE_ERROR_PREFIX + "0003"
    # 1X Execute command error
    EXEC_CMD_ERROR = _REMOTE_ERROR_PREFIX + "0010"
    EXEC_CMD_TIMEOUT = _REMOTE_ERROR_PREFIX + "0011"
    CHANNEL_ERROR = _REMOTE_ERROR_PREFIX + "0012"
    CHANNEL_READ_TIMEOUT = _REMOTE_ERROR_PREFIX + "0013"
    SWITCH_VSYS_FAILED = _REMOTE_ERROR_PREFIX + "0014"
    ENABLE_FAILED = _REMOTE_ERROR_PREFIX + "0015"
    DISABLE_FAILED = _REMOTE_ERROR_PREFIX + "0016"
    CONFIG_FAILED = _REMOTE_ERROR_PREFIX + "0017"
    EXIT_CONFIG_FAILED = _REMOTE_ERROR_PREFIX + "0018"
    EXEC_CMD_PARTIAL_ERROR = _REMOTE_ERROR_PREFIX + "0019"
    GET_PROMPT_FAILED = _REMOTE_ERROR_PREFIX + "0020"
    # 2X Update config error
    UPDATE_CONIFG_ERROR = _REMOTE_ERROR_PREFIX + "0020"
    UPDATE_CONFIG_TIMEOUT = _REMOTE_ERROR_PREFIX + "0021"
    PULL_CONFIG_ERROR = _REMOTE_ERROR_PREFIX + "0022"
    TEXTFSM_TEMPLATE_ERROR = _REMOTE_ERROR_PREFIX + "0023"
    TEXTFSM_PARSE_ERROR = _REMOTE_ERROR_PREFIX + "0024"
    SAVE_REPO_ERROR = _REMOTE_ERROR_PREFIX + "0022"
