from _typeshed import Incomplete
from sklearn.base import BaseEstimator, TransformerMixin

class ColumnSelector(BaseEstimator, TransformerMixin):
    """Select only specified columns."""
    columns: Incomplete
    def __init__(self, columns) -> None: ...
    def fit(self, X, y: Incomplete | None = None): ...
    def transform(self, X): ...
    def inverse_transform(self, X): ...
