
class PyAmpResult:
    title: str
    url: str
    click_url: str
    impression_url: str
    advertiser: str
    block_id: int
    iab_category: str
    serp_categories: list[int]
    icon: str
    full_keyword: str

    def __init__(self,
                 title: str,
                 url: str,
                 click_url: str,
                 impression_url: str,
                 advertiser: str,
                 block_id: int,
                 iab_category: str,
                 serp_categories: list[int],
                 icon: str,
                 full_keyword: str): ...
    @property
    def title(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def click_url(self) -> str: ...
    @property
    def impression_url(self) -> str: ...
    @property
    def advertiser(self) -> str: ...
    @property
    def block_id(self) -> int: ...
    @property
    def iab_category(self) -> str: ...
    @property
    def serp_categories(self) -> list[int]: ...
    @property
    def icon(self) -> str: ...
    @property
    def full_keyword(self) -> str: ...


class AmpIndexManager:
    def __init__(self): ...
    def build_from_file(self, index_name: str, file_path: str): ...
    def build(self, index_name: str, data: str | bytes): ...
    def query(self, index_name: str, query: str) -> list[PyAmpResult]: ...
    def delete(self, index_name: str): ...
    def list(self) -> list[str]: ...
    def has(self, index_name: str) -> bool: ...
    def list_icons(self, index_name: str) -> list[str]: ...
    def stats(self, index_name: str) -> dict[str, int]: ...
