# coding: utf-8

"""
    Kowabunga API documentation

    Kvm Orchestrator With A BUNch of Goods Added

    The version of the OpenAPI document: 0.52.5
    Contact: maintainers@kowabunga.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kowabunga.models.kaktus import Kaktus

class TestKaktus(unittest.TestCase):
    """Kaktus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Kaktus:
        """Test Kaktus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Kaktus`
        """
        model = Kaktus()
        if include_optional:
            return Kaktus(
                id = '',
                name = '',
                description = '',
                cpu_cost = {price=0.8008282, currency=currency},
                memory_cost = {price=0.8008282, currency=currency},
                overcommit_cpu_ratio = 56,
                overcommit_memory_ratio = 56,
                agents = [
                    ''
                    ]
            )
        else:
            return Kaktus(
                name = '',
                agents = [
                    ''
                    ],
        )
        """

    def testKaktus(self):
        """Test Kaktus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
