# coding: utf-8

"""
    Kowabunga API documentation

    Kvm Orchestrator With A BUNch of Goods Added

    The version of the OpenAPI document: 0.52.5
    Contact: maintainers@kowabunga.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kowabunga.api.adapter_api import AdapterApi


class TestAdapterApi(unittest.TestCase):
    """AdapterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdapterApi()

    def tearDown(self) -> None:
        pass

    def test_delete_adapter(self) -> None:
        """Test case for delete_adapter

        """
        pass

    def test_list_adapters(self) -> None:
        """Test case for list_adapters

        """
        pass

    def test_read_adapter(self) -> None:
        """Test case for read_adapter

        """
        pass

    def test_update_adapter(self) -> None:
        """Test case for update_adapter

        """
        pass


if __name__ == '__main__':
    unittest.main()
