# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import enum

import winrt.system
from winui3._winui3_microsoft_windows_ai_machinelearning import (
    ExecutionProvider,
    ExecutionProviderCatalog,
    ExecutionProviderReadyResult,
)

__all__ = [
    "ExecutionProviderCertification",
    "ExecutionProviderReadyResultState",
    "ExecutionProviderReadyState",
    "ExecutionProvider",
    "ExecutionProviderCatalog",
    "ExecutionProviderReadyResult",
]

class ExecutionProviderCertification(enum.IntEnum):
    UNKNOWN = 0
    CERTIFIED = 1
    UNCERTIFIED = 2

class ExecutionProviderReadyResultState(enum.IntEnum):
    IN_PROGRESS = 0
    SUCCESS = 1
    FAILURE = 2

class ExecutionProviderReadyState(enum.IntEnum):
    READY = 0
    NOT_READY = 1
    NOT_PRESENT = 2

