key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIDQK/ozBPYdUxs3uATvIrm4S50rvqI75H/oy7xf7vTQDoAoGCCqGSM49
AwEHoUQDQgAEwnTpFe4WBm1AK7D3wsy57MQWFLJwc0ROp/wfILr+Ph8N//A5CGJj
bsCGmBvMstVL4H0fhiHttV71XzXKVNnczA==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6TCCAY8CFDx5sqBAEood2FlSyOitvvzqd6htMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTEwMTgxNDI2MDRaFw0zNTEwMTYxNDI2
MDRaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABMJ06RXuFgZtQCuw98LMuezEFhSycHNETqf8HyC6/j4fDf/wOQhiY27A
hpgbzLLVS+B9H4Yh7bVe9V81ylTZ3MwwCgYIKoZIzj0EAwIDSAAwRQIhAJJcSvg8
DPiCKw+oNlMWmLBMbgcf78YTvR5zsMD/mzpwAiBmbfPK0Cda4mIqJBe3Ts/e03mm
R71Im7FZg+vYvMmDYQ==
-----END CERTIFICATE-----
"""