"""
db4e/Constants/DLabel.py

    Database 4 Everything
    Author: Nadim-Daniel Ghaznavi
    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
    GitHub: https://github.com/NadimGhaznavi/db4e
    License: GPL 3.0
"""

from db4e.Modules.ConstGroup import ConstGroup


class DLabel(ConstGroup):
    ABORT: str = "Abort"
    ACTIVE_MINERS: str = "Active Miners"
    ALL_TIME: str = "All Available"
    APPLY: str = "Apply"
    ANY_IP: str = "Listen on IP"
    API: str = "API"
    BLOCKCHAIN: str = "Blockchain"
    BLOCKCHAIN_DIR: str = "Blockchain Directory"
    BLOCKS: str = "Blocks"
    BLOCKS_FOUND: str = "Blocks Found"
    CHAIN: str = "Chain"
    CHAIN_STATS: str = "Chain Stats"
    CONFIG: str = "Configuration"
    CONFIG_FILE: str = "Configuration File"
    CURRENT: str = "Current"
    DAYS: str = "Days"
    DB4E: str = "Db4E Core"
    DB4E_LONG: str = "Database 4 Everything"
    DB4E_GROUP: str = "Db4E Group"
    DB4E_USER: str = "Db4E User"
    DELETE: str = "Delete"
    DETAILS: str = "Details"
    DEPLOYMENTS: str = "Deployments"
    DISABLE: str = "Disable"
    DONATIONS: str = "Donations"
    DONATIONS_WALLET: str = "Donations Wallet"
    ENABLE: str = "Enable"
    ENABLED: str = "Enabled"
    ELEMENT_TYPE: str = "Component"
    END: str = "End"
    ERROR: str = "Error"
    EVENT: str = "Event"
    GROUP: str = "Group"
    H_PER_S: str = "H/s"
    HASHRATE: str = "Hashrate"
    HASHRATES: str = "Hashrates"
    HEALTH: str = "Health Checks"
    HEALTH_MSGS: str = "Health Checks"
    IN_PEERS: str = "Incoming Peer Connections"
    INITIAL_SETUP: str = "Initial Setup"
    INSTALL_DIR: str = "Install Directory"
    INSTANCE: str = "Instance"
    IP_ADDR: str = "Hostname/IP Address"
    LOCAL_TIMESTAMP: str = "Localtime Timestamp"
    LOCAL_SOFTWARE_SYSTEM: str = "Local Software System"
    LOG: str = "Log"
    LOG_FILE: str = "Log File"
    LOG_LEVEL: str = "Log Level"
    LOG_ROTATE_CONFIG: str = "logrotate Configuration"
    LOG_VIEWER: str = "Log Viewer"
    MACHINE: str = "Host"
    MAIN_CHAIN: str = "Main"
    MINI_CHAIN: str = "Mini"
    MAX_LOG_FILES: str = "Maximum Number of Log Files"
    MAX_LOG_SIZE: str = "Maximum Log File Size"
    MESSAGE: str = "Message"
    METRICS: str = "Metrics"
    MONEROD: str = "Monero Daemon"
    MONEROD_REMOTE: str = "Remote Monero Daemon"
    MONEROD_REMOTE_SHORT: str = "Remote Monero"
    MONEROD_SHORT: str = "Monero"
    MONTH_1: str = "One Month"
    MONTHS_3: str = "Three Months"
    MONTHS_6: str = "Six Months"
    NANO_CHAIN: str = "Nano"
    NEW: str = "New"
    NUM_THREADS: str = "Number of Threads"
    OBJECT_ID: str = "Object ID"
    OPERATION: str = "Operation"
    OPS_MGR: str = "Ops Manager"
    OUT_PEERS: str = "Outgoing Peer Connections"
    P2P_PORT: str = "P2P Port"
    P2P_BIND_PORT: str = "P2P Bind Port"
    P2POOL: str = "P2Pool Daemon"
    P2POOL_INTERNAL: str = "Internal P2Pool Daemon"
    P2POOL_INTERNAL_SHORT: str = "Internal P2Pool"
    P2POOL_REMOTE: str = "Remote P2Pool Daemon"
    P2POOL_REMOTE_SHORT: str = "Remote P2Pool"
    P2POOL_SHORT: str = "P2Pool"
    P2POOL_WATCHER: str = "P2Pool Watcher"
    PARENT: str = "Parent"
    PARENT_ID: str = "Parent ID"
    PAYMENTS: str = "Payments"
    PLOT: str = "Plot"
    PRIMARY_SERVER: str = "Primary Server"
    PRIORITY_NODE_1: str = "Priority Node 1"
    PRIORITY_NODE_2: str = "Priority Node 2"
    PRIORITY_PORT_1: str = "Priority Port 1"
    PRIORITY_PORT_2: str = "Priority Port 2"
    PROCEED: str = "Proceed"
    REMOTE: str = "Remote"
    RESTART: str = "Restart"
    RESULTS: str = "Results"
    RPC_BIND_PORT: str = "RPC Bind Port"
    RUNTIME: str = "Run Time"
    RUNTIME_LOG: str = "Runtime Log"
    SHARES: str = "Shares"
    SHARES_FOUND: str = "Shares Found"
    SHOW_TIME_STATS: str = "Show Time Stats"
    SOFTWARE_SYSTEM: str = "Software System"
    START: str = "Start"
    START_STOP_LOG: str = "Start/Stop Log"
    STATUS: str = "Status"
    STARTUP_SCRIPT: str = "Startup Script"
    STATS_MOD: str = "API stats_mod"
    STDIN_PATH: str = "Standard Input FIFO"
    STOP: str = "Stop"
    STRATUM_PORT: str = "Stratum Port"
    TABLES: str = "Tables"
    TIMESTAMP: str = "Timestamp"
    TOTAL: str = "Total"
    TUI_LOG: str = "Console Log"
    TYPE: str = "Type"
    UPDATE: str = "Update"
    UPTIME: str = "Uptime"
    UPSTREAM_MONERO: str = "Upstream Monero"
    UPSTREAM_P2POOL: str = "Upstream P2Pool"
    USER: str = "User"
    USER_WALLET: str = "Monero User Wallet"
    VENDOR_DIR: str = "Deployment Directory"
    VERSION: str = "Version"
    VIEW_LOG: str = "View Log"
    WEEK_1: str = "One Week"
    WEEKS_2: str = "Two Weeks"
    WELCOME: str = "Welcome"
    WALLET: str = "Monero Wallet"
    XMRIG: str = "XMRig Miner"
    XMRIG_SHORT: str = "XMRig"
    XMRIG_REMOTE: str = "Remote XMRig Miner"
    XMRIG_REMOTE_SHORT: str = "Remote XMRig"
    XMRIG_SHORT: str = "XMRig"
    ZMQ_PUB_PORT: str = "ZMQ Pub Port"
    ZMQ_RPC_PORT: str = "ZMQ RPC Port"
