from .imageTask import ImageTask
from .siteTask import SiteTask
from .cr2Task import Cr2Task
from .dayPageTask import DayPageTask
from .geojsonTask import GeojsonTask
from .galleryTask import GalleryTask
from .journalTask import JournalTask
from .textTask import TextTask
from .markdownTask import MarkdownTask
from .audioTask import AudioTask
from .gpxTask import GPXTask
from .qstarzTask import QstarzTask
from .tagsTask import TagsTask
