PROVIDER_MAP = {
    'id': 'uuid4',
    'uuid': 'uuid4',
    'tenantid': 'uuid4',
    'topicid': 'uuid4',
    'ativo': 'pybool',
    'data_criacao': 'past_datetime',
    'data_modificacao': 'past_datetime',
    'data_cadastro': 'past_date',
    'data_aniversario': 'date_of_birth',
    'data_hora_emissao': 'past_datetime',
    'data_hora_fechamento': 'past_datetime',
    'validade': 'future_date',
    'data': 'past_datetime',
    'createdat': 'past_datetime',
    'updatedat': 'past_datetime',
    'deletedat': 'past_datetime',

    'nome_completo': 'name',
    'nome': 'first_name',
    'sobrenome': 'last_name',
    'cpf': 'cpf',
    'rg': 'rg',
    'data_nascimento': 'date_of_birth',
    'idade': ('pyint', {'min_value': 18, 'max_value': 90}),
    'email': 'safe_email',
    'telefone_fixo': 'phone_number',
    'celular': 'phone_number',
    'telefone_celular': 'phone_number',
    'whatsapp': 'phone_number',
    'nome_usuario': 'user_name',
    'senha': ('password', {'length': 12}),
    'password': ('password', {'length': 12}),
    'privatekey': ('password', {'length': 64}),
    
    'cnpj_cpf': 'cpf_ou_cnpj',
    'ie_rg': 'rg',
    'conjuge_cpf': 'cpf',
    'avalista_cpf': 'cpf',
    'conjuge_nascimento': 'date_of_birth',

    'endereco_completo': 'address',
    'endereco': 'address',
    'logradouro': 'street_name',
    'rua': 'street_name',
    'numero': 'building_number',
    'complemento': 'building_number',
    'bairro': 'bairro',
    'cidade': 'city',
    'estado': 'state',
    'sigla_estado': 'state_abbr',
    'uf': 'state_abbr',
    'cep': 'postcode',
    'ibge': ('numerify', {'text': '#######'}),
    'ibge_uf': ('numerify', {'text': '##'}),

    'sku': ('bothify', {'text': 'SKU-???-#####'}),
    'nome_produto': 'word',
    'descricao': 'text',
    'descricao_complementar': 'sentence',
    'fabricante': 'company',
    'referencia': ('bothify', {'text': 'REF-???-####'}),
    'marca': 'company',
    'unidade': ('random_element', {'elements': ['UN', 'KG', 'MT', 'LT', 'CX', 'PC']}),
    'preco_venda': ('pydecimal', {'left_digits': 3, 'right_digits': 2, 'positive': True}),
    'preco_custo': ('pydecimal', {'left_digits': 3, 'right_digits': 2, 'positive': True}),
    'ean13': 'ean13',
    'quantidade_estoque': ('pyint', {'min_value': 0, 'max_value': 1000}),
    'localizacao_estoque': ('bothify', {'text': 'Setor?-##'}),
    'peso_kg': ('pyfloat', {'min_value': 0.1, 'max_value': 50, 'right_digits': 3}),
    'cor': 'color_name',
    'tamanho': 'tamanho_roupa',
    'tecido': 'tecido_roupa',
    'colecao': 'nome_colecao',
    
    'title': 'sentence',
    'content': 'text',
    'observacoes': 'text',
    'descricao_item_conserto': 'sentence',
    'servico_afazer': 'sentence',
    'solicitante': 'name',
    'contato_nome': 'name',
    
    'razao_social': 'company',
    'razao': 'company',
    'fantasia': 'company',
    'cnpj': 'cnpj',
    'cliente_nome': 'name',
    'cliente_email': 'safe_email',
    'cliente_telefone': 'phone_number',
    'codigo_empresa': ('pyint', {'min_value': 1, 'max_value': 999}),
    'codigo_cliente': ('pyint', {'min_value': 1, 'max_value': 99999}),
    'codigo_vendedor': ('pyint', {'min_value': 1, 'max_value': 999}),
    'vendedor_padrao': ('pyint', {'min_value': 1, 'max_value': 999}),
    'forma_pagamento': 'forma_pagamento_erp',
    'status_pagamento': 'status_pagamento_erp',
    'numero_parcelas': ('pyint', {'min_value': 1, 'max_value': 12}),
    'data_vencimento': 'future_date',

    'chave_acesso_nfe': ('numerify', {'text': '#' * 44}),
    'numero_nfe': ('pyint', {'min_value': 1000, 'max_value': 99999}),
    'serie_nfe': ('pyint', {'min_value': 1, 'max_value': 3}),
    'ncm': ('numerify', {'text': '########'}),
    'trib_ncm': ('numerify', {'text': '########'}),
    'trib_cnpj_fabr': 'cnpj',
    'cfop': 'cfop_venda',
    'status_pedido': 'status_pedido_ecommerce',
    'codigo_rastreamento': 'codigo_rastreamento_br',
    
    'valor_frete': ('pydecimal', {'left_digits': 4, 'right_digits': 2, 'positive': True}),
    'valor_seguro': ('pydecimal', {'left_digits': 4, 'right_digits': 2, 'positive': True}),
    'valor_outros': ('pydecimal', {'left_digits': 4, 'right_digits': 2, 'positive': True}),
    'valor_produtos': ('pydecimal', {'left_digits': 5, 'right_digits': 2, 'positive': True}),
    'valor_servicos': ('pydecimal', {'left_digits': 5, 'right_digits': 2, 'positive': True}),
    'valor_total': ('pydecimal', {'left_digits': 6, 'right_digits': 2, 'positive': True}),
    'valor_desconto': ('pydecimal', {'left_digits': 4, 'right_digits': 2, 'positive': True}),
    'valor': ('pydecimal', {'left_digits': 5, 'right_digits': 2, 'positive': True}),
    'desconto': ('pydecimal', {'left_digits': 3, 'right_digits': 2, 'positive': True}),
    'multa': ('pydecimal', {'left_digits': 3, 'right_digits': 2, 'positive': True}),
    'juros': ('pydecimal', {'left_digits': 3, 'right_digits': 2, 'positive': True}),
    
    'chave': ('numerify', {'text': '#' * 44}),
    'protocolo': ('numerify', {'text': '###############'}),
    'cpfcnpj_cliente': 'cnpj',
    'data_emissao': 'past_date',
    'data_envio': 'past_date',
    'numero': ('pyint', {'min_value': 1, 'max_value': 999999}),
    'serie': ('pyint', {'min_value': 1, 'max_value': 999}),
    'modelo_documento': ('pyint', {'min_value': 55, 'max_value': 65}),
}