from _typeshed import Incomplete
from pandas import DataFrame as pdDataFrame
from ydata.quality.outlier.prototype import BaseOperator

class StandardDeviationRepresentation(BaseOperator):
    sigma: Incomplete
    threshold: Incomplete
    def __init__(self, sigma: float = 3, threshold: float = 0.5) -> None: ...
    def fit_transform(self, X: pdDataFrame) -> pdDataFrame: ...
    def fit(self, X: pdDataFrame): ...
    def transform(self, X: pdDataFrame) -> pdDataFrame: ...
    def plot(self, X: pdDataFrame, ax: Incomplete | None = None): ...
    def summary(self) -> dict: ...
