from ydata.dataset.dataset import Dataset as Dataset
from ydata.metadata.metadata import Metadata as Metadata

def is_entity(col: str, m: Metadata): ...
def get_categorical_vars(dataset: Dataset, meta: Metadata): ...
def get_numerical_vars(dataset: Dataset, meta: Metadata): ...
