# Generated by Django 5.1.6 on 2025-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfchelseru', '0019_payment_created_at_payment_status_payment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
