# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from do_sdk_platform.models.data_post_request_schema_dto_data_description_inner_validate_file import DataPostRequestSchemaDtoDataDescriptionInnerValidateFile
from do_sdk_platform.models.data_post_request_schema_dto_data_description_inner_validate_string import DataPostRequestSchemaDtoDataDescriptionInnerValidateString
from typing import Optional, Set
from typing_extensions import Self

class DataPostRequestSchemaDtoDataDescriptionInnerValidate(BaseModel):
    """
    DataPostRequestSchemaDtoDataDescriptionInnerValidate
    """ # noqa: E501
    file: Optional[DataPostRequestSchemaDtoDataDescriptionInnerValidateFile] = None
    string: Optional[DataPostRequestSchemaDtoDataDescriptionInnerValidateString] = None
    __properties: ClassVar[List[str]] = ["file", "string"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataPostRequestSchemaDtoDataDescriptionInnerValidate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of file
        if self.file:
            _dict['file'] = self.file.to_dict()
        # override the default output from pydantic by calling `to_dict()` of string
        if self.string:
            _dict['string'] = self.string.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataPostRequestSchemaDtoDataDescriptionInnerValidate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file": DataPostRequestSchemaDtoDataDescriptionInnerValidateFile.from_dict(obj["file"]) if obj.get("file") is not None else None,
            "string": DataPostRequestSchemaDtoDataDescriptionInnerValidateString.from_dict(obj["string"]) if obj.get("string") is not None else None
        })
        return _obj


