from .color import Color

def lighten(color: Color, factor: float) -> Color: ...
def darken(color: Color, factor: float) -> Color: ...
def invert(color: Color) -> Color: ...
def grayscale(color: Color) -> Color: ...
def mix(color1: Color, color2: Color, factor: float = 0.5) -> Color: ...
def clamp(color: Color) -> Color: ...
def distance(c1: Color, c2: Color) -> float: ...
def to_ansi256(color: Color) -> int: ...
def color_text(text: str, color: Color) -> str: ...
def highlight_text(text: str, color: Color) -> str: ...
def color_highlight_text(text: str, fg: Color, bg: Color) -> str: ...