from _typeshed import Incomplete

MAX_IPV4: Incomplete
MAX_IPV6: Incomplete
MAX_ITER: int

def random_ipv4(): ...
def random_ipv6(): ...
def get_one_regex(regex): ...
def get_n_unique_from_one(gen, n, max_iter: int | None = None, unique: bool = True): ...
