from dataclasses import dataclass
from typing import Any, Callable
from ydata.preprocessors.methods.anonymization import AnonymizerType

@dataclass
class ColumnAnonymizerConfiguration:
    type: AnonymizerType | str
    cols: list[str]
    params: dict[str, Any] = ...
    locale: str | None = ...
    def get_anonymizer(self): ...
    def from_dict(key: str, config: dict | str | int | AnonymizerType | Callable | list, default_locale: str | None = None, validate: bool = True) -> ColumnAnonymizerConfiguration: ...
    def to_dict(self): ...
    def __init__(self, type, cols, params=..., locale=...) -> None: ...
