from _typeshed import Incomplete
from pandas import DataFrame as pdDataFrame
from ydata.quality.outlier.prototype import BaseDetectionOperator

class StandardDeviation(BaseDetectionOperator):
    sigma: Incomplete
    threshold: Incomplete
    def __init__(self, sigma: float = 3, threshold: float = 0.5) -> None: ...
    def fit_predict(self, X: pdDataFrame) -> pdDataFrame: ...
    def fit(self, X: pdDataFrame): ...
    def predict(self, X: pdDataFrame) -> pdDataFrame: ...
    def summary(self) -> dict: ...
